import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer';
import type { HealthDossierData } from '@/services/healthDossier/buildHealthDossierData';

const COLORS = {
  forest: '#1c2b1d',
  forestDeep: '#111a12',
  forestInk: '#080d09',
  gold: '#a8833a',
  goldBright: '#e6c577',
  parchment: '#f7f1e6',
  muted: '#5c554d',
  line: '#d9d0c3',
  white: '#ffffff',
};

const styles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingBottom: 56,
    paddingHorizontal: 40,
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: COLORS.forestInk,
    backgroundColor: COLORS.parchment,
  },
  headerBar: {
    backgroundColor: COLORS.forest,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 22,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brand: {
    color: COLORS.goldBright,
    fontSize: 9,
    letterSpacing: 2.4,
    textTransform: 'uppercase',
    fontFamily: 'Helvetica-Bold',
  },
  headerMeta: {
    color: COLORS.parchment,
    fontSize: 8,
    letterSpacing: 0.6,
  },
  kicker: {
    color: COLORS.gold,
    fontSize: 8,
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 6,
    fontFamily: 'Helvetica-Bold',
  },
  h1: {
    fontSize: 26,
    color: COLORS.forest,
    marginBottom: 6,
    fontFamily: 'Helvetica-Bold',
  },
  lead: {
    fontSize: 10,
    color: COLORS.muted,
    marginBottom: 18,
    lineHeight: 1.45,
  },
  sectionTitle: {
    fontSize: 12,
    color: COLORS.forest,
    marginTop: 14,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gold,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.4,
  },
  idRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
  },
  photoWrap: {
    width: 88,
    height: 88,
    backgroundColor: COLORS.forestDeep,
    borderWidth: 1,
    borderColor: COLORS.gold,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  photo: {
    width: 88,
    height: 88,
    objectFit: 'cover',
  },
  photoFallback: {
    color: COLORS.goldBright,
    fontSize: 22,
    fontFamily: 'Helvetica-Bold',
  },
  idGrid: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  field: {
    width: '50%',
    marginBottom: 8,
    paddingRight: 8,
  },
  fieldLabel: {
    fontSize: 7,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: COLORS.gold,
    marginBottom: 2,
    fontFamily: 'Helvetica-Bold',
  },
  fieldValue: {
    fontSize: 10,
    color: COLORS.forestInk,
    lineHeight: 1.35,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: COLORS.forest,
    paddingVertical: 6,
    paddingHorizontal: 6,
  },
  tableHeaderCell: {
    color: COLORS.goldBright,
    fontSize: 7,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    fontFamily: 'Helvetica-Bold',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
    paddingVertical: 6,
    paddingHorizontal: 6,
  },
  tableRowAlt: {
    backgroundColor: 'rgba(168, 131, 58, 0.06)',
  },
  cell: {
    fontSize: 8,
    color: COLORS.forestInk,
    paddingRight: 4,
    lineHeight: 1.3,
  },
  empty: {
    fontSize: 9,
    color: COLORS.muted,
    fontStyle: 'italic',
    marginTop: 4,
  },
  footer: {
    position: 'absolute',
    left: 40,
    right: 40,
    bottom: 22,
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
    paddingTop: 8,
  },
  footerText: {
    fontSize: 7,
    color: COLORS.muted,
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  pageNumber: {
    fontSize: 7,
    color: COLORS.gold,
    textAlign: 'center',
    marginTop: 3,
  },
  listItem: {
    marginBottom: 8,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
  },
  listTitle: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    color: COLORS.forest,
    marginBottom: 2,
  },
  listMeta: {
    fontSize: 8,
    color: COLORS.muted,
    marginBottom: 2,
  },
  listNotes: {
    fontSize: 8,
    color: COLORS.forestInk,
    lineHeight: 1.35,
  },
});

const FOOTER_COPY =
  'Official Digital Health Dossier - Generated by PetClues Concierge (https://petclues.com)';

function PageFooter({ pageLabel }: { pageLabel: string }) {
  return (
    <View style={styles.footer} fixed>
      <Text style={styles.footerText}>{FOOTER_COPY}</Text>
      <Text style={styles.pageNumber}>{pageLabel}</Text>
    </View>
  );
}

function HeaderBar({ subtitle }: { subtitle: string }) {
  return (
    <View style={styles.headerBar}>
      <Text style={styles.brand}>PetClues Concierge</Text>
      <Text style={styles.headerMeta}>{subtitle}</Text>
    </View>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.field}>
      <Text style={styles.fieldLabel}>{label}</Text>
      <Text style={styles.fieldValue}>{value}</Text>
    </View>
  );
}

type HealthDossierTemplateProps = {
  data: HealthDossierData;
};

/**
 * Multi-page Official Digital Health Dossier for @react-pdf/renderer.
 */
export function HealthDossierTemplate({ data }: HealthDossierTemplateProps) {
  const initials = data.petName
    .split(/\s+/)
    .map((part) => part[0])
    .join('')
    .slice(0, 2)
    .toUpperCase();

  return (
    <Document
      title={`${data.petName} Health Dossier`}
      author="PetClues Concierge"
      subject="Official Digital Health Dossier"
      creator="PetClues Concierge"
    >
      {/* Page 1 - Cover & Identification */}
      <Page size="A4" style={styles.page}>
        <HeaderBar subtitle="Official Digital Health Dossier" />
        <Text style={styles.kicker}>Cover & identification</Text>
        <Text style={styles.h1}>{data.petName}</Text>
        <Text style={styles.lead}>
          Permanent clinical identity packet for guardians, clinics, and relocation partners.
          Generated {data.generatedAtLabel}.
        </Text>

        <View style={styles.idRow}>
          <View style={styles.photoWrap}>
            {data.photoUrl ? (
              // eslint-disable-next-line jsx-a11y/alt-text -- react-pdf Image
              <Image src={data.photoUrl} style={styles.photo} />
            ) : (
              <Text style={styles.photoFallback}>{initials || 'PC'}</Text>
            )}
          </View>
          <View style={styles.idGrid}>
            <Field label="Legal name" value={data.petName} />
            <Field label="Breed" value={data.breed} />
            <Field label="Species" value={data.species} />
            <Field label="Date of birth" value={data.dateOfBirth} />
            <Field label="Gender" value={data.gender} />
            <Field label="Weight" value={data.weight} />
            <Field label="Microchip ID" value={data.microchipId} />
            <Field label="Blood type" value={data.bloodType} />
          </View>
        </View>

        <Text style={styles.sectionTitle}>Emergency owner contact</Text>
        <View style={styles.idGrid}>
          <Field label="Guardian" value={data.owner.name} />
          <Field label="Email" value={data.owner.email} />
          <Field label="Phone" value={data.owner.phone || 'Not recorded'} />
        </View>

        <PageFooter pageLabel="Page 1 of 3 · Identification" />
      </Page>

      {/* Page 2 - Vaccination & Titer Matrix */}
      <Page size="A4" style={styles.page}>
        <HeaderBar subtitle={`${data.petName} · Vaccination matrix`} />
        <Text style={styles.kicker}>Immunization archive</Text>
        <Text style={styles.h1}>Vaccination & titer matrix</Text>
        <Text style={styles.lead}>
          Chronological record of verified vaccines, administering clinics, batch identifiers, and
          expiration / next-due dates.
        </Text>

        <View style={styles.tableHeader}>
          <Text style={[styles.tableHeaderCell, { width: '28%' }]}>Vaccine</Text>
          <Text style={[styles.tableHeaderCell, { width: '14%' }]}>Date</Text>
          <Text style={[styles.tableHeaderCell, { width: '14%' }]}>Expires</Text>
          <Text style={[styles.tableHeaderCell, { width: '22%' }]}>Clinic</Text>
          <Text style={[styles.tableHeaderCell, { width: '22%' }]}>Batch / lot</Text>
        </View>

        {data.vaccinations.length === 0 ? (
          <Text style={styles.empty}>No vaccination records on file for this pet.</Text>
        ) : (
          data.vaccinations.map((row, index) => (
            <View
              key={`${row.title}-${row.dateRecorded}-${index}`}
              style={[styles.tableRow, index % 2 === 1 ? styles.tableRowAlt : {}]}
              wrap={false}
            >
              <Text style={[styles.cell, { width: '28%' }]}>{row.title}</Text>
              <Text style={[styles.cell, { width: '14%' }]}>{row.dateRecorded}</Text>
              <Text style={[styles.cell, { width: '14%' }]}>{row.nextDueDate || '-'}</Text>
              <Text style={[styles.cell, { width: '22%' }]}>{row.clinic || '-'}</Text>
              <Text style={[styles.cell, { width: '22%' }]}>{row.batchNumber || '-'}</Text>
            </View>
          ))
        )}

        <PageFooter pageLabel="Page 2 of 3 · Vaccinations" />
      </Page>

      {/* Page 3 - Medical Timeline & Allergies */}
      <Page size="A4" style={styles.page}>
        <HeaderBar subtitle={`${data.petName} · Clinical summary`} />
        <Text style={styles.kicker}>Clinical continuum</Text>
        <Text style={styles.h1}>Medical timeline & allergies</Text>
        <Text style={styles.lead}>
          High-level surgical history, chronic conditions, active medications, and allergy alerts for
          rapid clinical handoff.
        </Text>

        <Text style={styles.sectionTitle}>Surgical history</Text>
        {data.surgeries.length === 0 ? (
          <Text style={styles.empty}>No surgical history recorded.</Text>
        ) : (
          data.surgeries.map((item, index) => (
            <View key={`surgery-${index}`} style={styles.listItem} wrap={false}>
              <Text style={styles.listTitle}>{item.title}</Text>
              <Text style={styles.listMeta}>
                {item.dateRecorded}
                {item.severity ? ` · Severity ${item.severity}` : ''}
              </Text>
              {item.notes ? <Text style={styles.listNotes}>{item.notes}</Text> : null}
            </View>
          ))
        )}

        <Text style={styles.sectionTitle}>Chronic conditions & diagnoses</Text>
        {data.conditions.length === 0 ? (
          <Text style={styles.empty}>No chronic conditions recorded.</Text>
        ) : (
          data.conditions.map((item, index) => (
            <View key={`condition-${index}`} style={styles.listItem} wrap={false}>
              <Text style={styles.listTitle}>{item.title}</Text>
              <Text style={styles.listMeta}>
                {item.dateRecorded}
                {item.severity ? ` · Severity ${item.severity}` : ''}
              </Text>
              {item.notes ? <Text style={styles.listNotes}>{item.notes}</Text> : null}
            </View>
          ))
        )}

        <Text style={styles.sectionTitle}>Active medications</Text>
        {data.medications.length === 0 ? (
          <Text style={styles.empty}>No active medications recorded.</Text>
        ) : (
          data.medications.map((item, index) => (
            <View key={`med-${index}`} style={styles.listItem} wrap={false}>
              <Text style={styles.listTitle}>{item.title}</Text>
              <Text style={styles.listMeta}>{item.dateRecorded}</Text>
              {item.notes ? <Text style={styles.listNotes}>{item.notes}</Text> : null}
            </View>
          ))
        )}

        <Text style={styles.sectionTitle}>Allergies</Text>
        {data.allergies.length === 0 ? (
          <Text style={styles.empty}>No allergies recorded.</Text>
        ) : (
          data.allergies.map((item, index) => (
            <View key={`allergy-${index}`} style={styles.listItem} wrap={false}>
              <Text style={styles.listTitle}>{item.title}</Text>
              <Text style={styles.listMeta}>
                {item.dateRecorded}
                {item.severity ? ` · Severity ${item.severity}` : ''}
              </Text>
              {item.notes ? <Text style={styles.listNotes}>{item.notes}</Text> : null}
            </View>
          ))
        )}

        <PageFooter pageLabel="Page 3 of 3 · Clinical timeline" />
      </Page>
    </Document>
  );
}
