import type { BlogCategoryId } from '@/data/blogCategories';
import type { BlogArticleCluster, ExpandedBlogConfig } from './buildBlogArticle';

type BlogSeed = {
  slug: string;
  title: string;
  excerpt: string;
  category: BlogCategoryId;
  tags: string[];
  cluster: BlogArticleCluster;
  focus: string;
  audience: string;
  keyDocuments: string[];
  faq1: string;
  faq1a: string;
  faq2: string;
  faq2a: string;
  faq3: string;
  faq3a: string;
};

function makeConfig(seed: BlogSeed, relatedSlugs: string[], relatedLearnSlugs?: string[]): ExpandedBlogConfig {
  return {
    slug: seed.slug,
    title: seed.title,
    excerpt: seed.excerpt,
    category: seed.category,
    tags: seed.tags,
    cluster: seed.cluster,
    focus: seed.focus,
    audience: seed.audience,
    keyDocuments: seed.keyDocuments,
    relatedSlugs,
    relatedLearnSlugs,
    faqs: [
      { question: seed.faq1, answer: seed.faq1a },
      { question: seed.faq2, answer: seed.faq2a },
      { question: seed.faq3, answer: seed.faq3a },
      {
        question: `How does PetClues help with ${seed.focus}?`,
        answer:
          'PetClues stores documents, sends reminders for due dates, and keeps an emergency passport ready to share with vets, sitters, or family.',
      },
      {
        question: `How often should I update ${seed.focus}?`,
        answer:
          'Update after every vet visit, medication change, or new document. A monthly 10-minute review catches gaps before they become problems.',
      },
      {
        question: 'Can I share records with a sitter or co-parent?',
        answer:
          'Yes. Shared access keeps everyone aligned on doses, allergies, and upcoming appointments without forwarding screenshots.',
      },
      {
        question: 'What is the fastest way to get started?',
        answer:
          'Upload your latest vet document, add the next due date as a reminder, and fill in emergency contacts. Expand history over time.',
      },
      {
        question: 'Do digital records replace my veterinarian?',
        answer:
          'No. Records support better conversations with your vet. Always confirm medical decisions with a licensed professional.',
      },
    ],
  };
}

const VACCINATION_SEEDS: BlogSeed[] = [
  {
    slug: 'adult-dog-vaccination-booster-schedule-guide',
    title: 'Adult Dog Vaccination Booster Schedule: What to Track After Year One',
    excerpt:
      'Complete guide to adult dog vaccine boosters - DHPP, rabies, Bordetella, and lifestyle shots with reminder tips so boosters never lapse.',
    category: 'dog-health',
    tags: ['adult dog vaccines', 'booster schedule', 'pet vaccination reminder'],
    cluster: 'vaccinations',
    focus: 'adult dog vaccination boosters',
    audience: 'Dog parents managing boosters after the puppy series',
    keyDocuments: ['vaccine certificates', 'clinic invoices with lot numbers', 'rabies tags', 'boarding requirement forms'],
    faq1: 'How often do adult dogs need DHPP boosters?',
    faq1a: 'Many vets recommend every 1-3 years depending on local guidelines and your dog’s risk profile.',
    faq2: 'Is rabies on a different schedule than other vaccines?',
    faq2a: 'Yes. Rabies timing follows local law and may be annual or every three years based on the product used.',
    faq3: 'What proof do boarding facilities need?',
    faq3a: 'Most want dated vaccine certificates, especially rabies and Bordetella, with clinic contact information.',
  },
  {
    slug: 'kitten-core-vaccine-timeline-first-year',
    title: 'Kitten Vaccination Schedule: Core Shots for the First 12 Months',
    excerpt:
      'Month-by-month kitten vaccine timeline for FVRCP, rabies, and optional FeLV with record-keeping tips for new cat parents.',
    category: 'cat-health',
    tags: ['kitten vaccines', 'cat vaccination schedule', 'FVRCP'],
    cluster: 'vaccinations',
    focus: 'kitten core vaccinations',
    audience: 'New kitten parents building a first-year vaccine plan',
    keyDocuments: ['FVRCP certificates', 'rabies certificates', 'FeLV test results', 'adoption medical summaries'],
    faq1: 'When do kittens get their first FVRCP shot?',
    faq1a: 'Often around 6-8 weeks, then every 3-4 weeks until about 16 weeks.',
    faq2: 'Do indoor kittens need rabies vaccines?',
    faq2a: 'Many regions require rabies vaccination regardless of indoor lifestyle.',
    faq3: 'Should FeLV vaccination be on my timeline?',
    faq3a: 'Your vet may recommend FeLV based on exposure risk, multi-cat homes, or outdoor access.',
  },
  {
    slug: 'rabies-vaccine-record-requirements-by-state',
    title: 'Rabies Vaccine Records for Dogs and Cats: What to Keep and Why',
    excerpt:
      'How to store rabies certificates, tags, and renewal dates for travel, licensing, and boarding - plus reminder workflows.',
    category: 'pet-records',
    tags: ['rabies certificate', 'pet travel', 'vaccination records'],
    cluster: 'vaccinations',
    focus: 'rabies vaccination documentation',
    audience: 'Pet parents who need rabies proof for licensing or travel',
    keyDocuments: ['rabies certificates', 'county license receipts', 'tag numbers', 'vet clinic contact cards'],
    faq1: 'Is a rabies tag enough proof?',
    faq1a: 'Tags help identification but facilities usually require the official certificate with date and product details.',
    faq2: 'When should I renew rabies reminders?',
    faq2a: 'Set alerts 30 and 7 days before expiration so you can book before license or travel deadlines.',
    faq3: 'What if I adopted a pet with unknown rabies history?',
    faq3a: 'Your vet can advise on appropriate vaccination timing and how to document the new series.',
  },
  {
    slug: 'bordetella-vaccine-boarding-daycare-guide',
    title: 'Bordetella Vaccine for Boarding and Daycare: Timing, Records, and Reminders',
    excerpt:
      'Everything dog parents need for Bordetella requirements - how far in advance to vaccinate, what records to bring, and how to track boosters.',
    category: 'dog-health',
    tags: ['bordetella', 'kennel cough', 'pet boarding vaccines'],
    cluster: 'vaccinations',
    focus: 'Bordetella vaccination for boarding',
    audience: 'Dog parents using boarding, daycare, or group training',
    keyDocuments: ['Bordetella certificates', 'boarding health forms', 'daycare vaccine policies'],
    faq1: 'How soon before boarding should Bordetella be given?',
    faq1a: 'Facilities often require vaccination 1-2 weeks before check-in - confirm with your kennel.',
    faq2: 'Is Bordetella oral, nasal, or injectable?',
    faq2a: 'All forms exist. Your vet chooses based on age, health, and facility rules.',
    faq3: 'How long does Bordetella protection last?',
    faq3a: 'Many protocols use 6-12 month boosters depending on exposure risk.',
  },
  {
    slug: 'leptospirosis-vaccine-risk-lifestyle-guide',
    title: 'Leptospirosis Vaccine: Lifestyle Risk Guide and Record Checklist',
    excerpt:
      'When leptospirosis vaccination makes sense for dogs, how to track the two-dose series, and what to save for your pet health records.',
    category: 'dog-health',
    tags: ['leptospirosis', 'dog vaccines', 'lifestyle vaccines'],
    cluster: 'vaccinations',
    focus: 'leptospirosis vaccination planning',
    audience: 'Dog parents in wildlife-heavy or wet-climate areas',
    keyDocuments: ['lepto vaccine receipts', 'series completion notes', 'titer discussions with your vet'],
    faq1: 'Which dogs benefit most from lepto vaccines?',
    faq1a: 'Dogs with pond, lake, puddle, or wildlife exposure often have higher risk.',
    faq2: 'Does lepto require a booster series?',
    faq2a: 'Yes. Initial protection usually needs two doses weeks apart, then annual boosters.',
    faq3: 'Should I log vaccine reactions?',
    faq3a: 'Always note lethargy, vomiting, or soreness so future visits can adjust timing or products.',
  },
  {
    slug: 'canine-influenza-vaccine-outbreak-prep',
    title: 'Canine Influenza Vaccine: Outbreak Prep and Documentation for Dog Parents',
    excerpt:
      'How to decide on canine flu vaccination, track boosters, and keep proof ready for daycare closures or travel changes.',
    category: 'dog-health',
    tags: ['canine influenza', 'dog flu vaccine', 'outbreak prep'],
    cluster: 'vaccinations',
    focus: 'canine influenza vaccination records',
    audience: 'Urban dog parents and daycare users in outbreak-prone regions',
    keyDocuments: ['canine influenza certificates', 'daycare outbreak notices', 'vet clinic advisories'],
    faq1: 'Is canine flu required for boarding?',
    faq1a: 'Some facilities require it during outbreaks or year-round in high-density regions.',
    faq2: 'How many doses does canine influenza need?',
    faq2a: 'Most protocols start with two doses weeks apart for naive dogs, then annual boosters.',
    faq3: 'Can records help if daycare closes suddenly?',
    faq3a: 'Yes. Proof of vaccination speeds entry to alternate facilities with similar policies.',
  },
  {
    slug: 'vaccine-reaction-documentation-for-vets',
    title: 'How to Document Pet Vaccine Reactions for Future Vet Visits',
    excerpt:
      'Template for logging vaccine reactions in your pet medical records - symptoms, timing, and what to share before the next booster.',
    category: 'pet-records',
    tags: ['vaccine reaction', 'pet medical records', 'vet documentation'],
    cluster: 'vaccinations',
    focus: 'vaccine reaction documentation',
    audience: 'Pet parents whose pets had mild or moderate vaccine reactions',
    keyDocuments: ['post-vaccine symptom notes', 'clinic discharge instructions', 'prior reaction timelines'],
    faq1: 'What counts as a vaccine reaction worth logging?',
    faq1a: 'Lethargy, swelling, hives, vomiting, or behavior changes within 48 hours should be documented.',
    faq2: 'Should I still booster if my pet reacted before?',
    faq2a: 'Only your veterinarian can decide after reviewing the documented reaction and severity.',
    faq3: 'Where should reaction notes live?',
    faq3a: 'Attach them to the specific vaccine event in your digital timeline, not a loose note.',
  },
];

const HEALTH_RECORDS_SEEDS: BlogSeed[] = [
  {
    slug: 'digital-pet-health-record-template-guide',
    title: 'Digital Pet Health Record Template: Fields Every Owner Should Track',
    excerpt:
      'A practical digital pet health record template - vaccines, labs, meds, and visit notes - plus how to keep it searchable year after year.',
    category: 'pet-records',
    tags: ['pet health records', 'digital records', 'vet organization'],
    cluster: 'health-records',
    focus: 'digital pet health record templates',
    audience: 'Pet parents moving from paper folders to a structured system',
    keyDocuments: ['wellness summaries', 'lab PDFs', 'vaccine certificates', 'prescription labels'],
    faq1: 'What fields belong in a pet health record template?',
    faq1a: 'Date, provider, diagnosis or service, medications, follow-up dates, and attached source files.',
    faq2: 'Should I keep raw PDFs or typed summaries?',
    faq2a: 'Keep both. PDFs are proof; short summaries make scanning faster.',
    faq3: 'How do templates help multi-pet homes?',
    faq3a: 'Separate profiles prevent mixed timelines while shared reminder habits stay consistent.',
  },
  {
    slug: 'pet-lab-results-tracking-normal-ranges',
    title: 'How to Track Pet Lab Results and Normal Ranges Over Time',
    excerpt:
      'Learn to log bloodwork, urinalysis, and thyroid panels with trend notes so you and your vet spot changes early.',
    category: 'pet-records',
    tags: ['pet lab results', 'bloodwork', 'health tracking'],
    cluster: 'health-records',
    focus: 'pet lab result tracking',
    audience: 'Owners managing chronic conditions or senior wellness panels',
    keyDocuments: ['lab PDFs', 'reference range printouts', 'vet interpretation notes'],
    faq1: 'Why track labs if my vet has them?',
    faq1a: 'Trends across years reveal gradual shifts single reports can miss.',
    faq2: 'Which values matter most to log?',
    faq2a: 'Kidney, liver, thyroid, glucose, and CBC highlights are common priorities for seniors.',
    faq3: 'How often should seniors repeat labs?',
    faq3a: 'Many vets recommend annual or semiannual panels depending on health status.',
  },
  {
    slug: 'chronic-condition-pet-record-system',
    title: 'Chronic Condition Pet Records: Build a System That Scales With Treatment',
    excerpt:
      'Organize chronic illness records - diabetes, allergies, epilepsy - with medication logs, flare notes, and specialist visit history.',
    category: 'pet-records',
    tags: ['chronic pet care', 'medical records', 'specialist visits'],
    cluster: 'health-records',
    focus: 'chronic condition record systems',
    audience: 'Owners coordinating long-term treatment plans',
    keyDocuments: ['specialist letters', 'medication logs', 'flare diaries', 'insurance approvals'],
    faq1: 'How detailed should flare notes be?',
    faq1a: 'Date, trigger, symptoms, treatment given, and outcome in 2-3 sentences is enough.',
    faq2: 'Should specialists and primary vets see the same file?',
    faq2a: 'Yes. One timeline prevents conflicting instructions.',
    faq3: 'Can reminders tie to chronic care tasks?',
    faq3a: 'Absolutely - refills, lab rechecks, and weight checks should be automated.',
  },
  {
    slug: 'multi-pet-household-health-records-setup',
    title: 'Multi-Pet Household Health Records: Setup Without Mixing Timelines',
    excerpt:
      'How to organize health records for two or more pets - separate profiles, color coding, and shared family access that prevents mistakes.',
    category: 'pet-records',
    tags: ['multi-pet', 'pet records', 'household organization'],
    cluster: 'health-records',
    focus: 'multi-pet health record organization',
    audience: 'Families with multiple dogs, cats, or mixed species',
    keyDocuments: ['per-pet vaccine charts', 'individual microchip records', 'species-specific diet notes'],
    faq1: 'Should each pet have its own reminder calendar?',
    faq1a: 'Yes. Shared calendars work if events are clearly labeled by pet name.',
    faq2: 'How do I prevent medication mix-ups?',
    faq2a: 'Store photos of each prescription label on the correct pet profile.',
    faq3: 'Can sitters access all pets at once?',
    faq3a: 'Share each pet passport separately or use household access with clear per-pet sections.',
  },
  {
    slug: 'pet-imaging-reports-mri-xray-storage',
    title: 'Storing Pet X-Ray and MRI Reports: What Owners Should Save',
    excerpt:
      'Guide to archiving imaging reports, CD/DICOM exports, and radiologist summaries for orthopedic and oncology follow-ups.',
    category: 'pet-records',
    tags: ['pet x-ray', 'MRI reports', 'imaging records'],
    cluster: 'health-records',
    focus: 'pet imaging report storage',
    audience: 'Owners managing orthopedic injuries or cancer care',
    keyDocuments: ['radiology reports', 'DICOM discs', 'surgeon follow-up notes'],
    faq1: 'Do I need to keep imaging CDs?',
    faq1a: 'Keep reports always; discs help specialists compare lesions over time.',
    faq2: 'Can I photograph x-ray films?',
    faq2a: 'Photos help for quick reference but official reports remain the clinical source.',
    faq3: 'Should imaging tie to symptom notes?',
    faq3a: 'Yes. Link lameness, coughing, or seizure logs to the imaging date.',
  },
  {
    slug: 'pet-dental-records-cleaning-history-guide',
    title: 'Pet Dental Records: Track Cleanings, Extractions, and Home Care',
    excerpt:
      'Build a dental history for dogs and cats - professional cleanings, extractions, home brushing, and when to schedule the next visit.',
    category: 'pet-records',
    tags: ['pet dental care', 'dental cleaning records', 'dog teeth'],
    cluster: 'health-records',
    focus: 'pet dental record keeping',
    audience: 'Owners preventing dental disease with consistent documentation',
    keyDocuments: ['anesthesia dental reports', 'tooth charts', 'home care product notes'],
    faq1: 'How often should dental cleanings be recorded?',
    faq1a: 'After every professional cleaning with before/after notes from your vet.',
    faq2: 'Should home brushing appear in records?',
    faq2a: 'Yes. Frequency and products help your vet adjust prevention plans.',
    faq3: 'Do cats need the same dental tracking?',
    faq3a: 'Yes. Feline dental disease is common and benefits from the same history.',
  },
  {
    slug: 'transferring-pet-records-between-vets',
    title: 'Transferring Pet Records Between Vets: Checklist for a Smooth Handoff',
    excerpt:
      'Step-by-step checklist to transfer pet medical records when you move, switch clinics, or see a specialist.',
    category: 'pet-records',
    tags: ['vet records transfer', 'new veterinarian', 'pet medical history'],
    cluster: 'health-records',
    focus: 'vet record transfers',
    audience: 'Pet parents changing clinics or relocating',
    keyDocuments: ['record release forms', 'full chart exports', 'prescription histories', 'imaging summaries'],
    faq1: 'How long do record transfers take?',
    faq1a: 'Same-day if you have PDFs ready; clinic-to-clinic requests may take several days.',
    faq2: 'Should I bring paper or digital copies?',
    faq2a: 'Digital copies you control are fastest; clinics can request official transfers separately.',
    faq3: 'What if the old clinic is unresponsive?',
    faq3a: 'Use your saved invoices, lab PDFs, and vaccine certificates to rebuild essentials.',
  },
];

const MEDICAL_HISTORY_SEEDS: BlogSeed[] = [
  {
    slug: 'building-complete-pet-medical-history-timeline',
    title: 'How to Build a Complete Pet Medical History Timeline',
    excerpt:
      'Turn scattered vet visits into a chronological medical history timeline that supports better diagnoses and fewer repeated tests.',
    category: 'pet-records',
    tags: ['pet medical history', 'health timeline', 'vet records'],
    cluster: 'medical-history',
    focus: 'pet medical history timelines',
    audience: 'Owners who want a single story of their pet’s health',
    keyDocuments: ['visit summaries', 'diagnosis letters', 'hospitalization records', 'referral notes'],
    faq1: 'How far back should a medical history go?',
    faq1a: 'Start with the last 12-24 months, then add older surgeries or chronic diagnoses.',
    faq2: 'What if I have gaps?',
    faq2a: 'Request records from prior clinics or rebuild from invoices and lab PDFs.',
    faq3: 'Does timeline format help specialists?',
    faq3a: 'Yes. Chronological context speeds consults and reduces duplicate diagnostics.',
  },
  {
    slug: 'pet-surgery-history-documentation-guide',
    title: 'Pet Surgery History Documentation: What to Save After Every Procedure',
    excerpt:
      'Post-surgery documentation guide - discharge instructions, implant cards, suture care, and follow-up imaging in one place.',
    category: 'pet-records',
    tags: ['pet surgery', 'post-op care', 'medical history'],
    cluster: 'medical-history',
    focus: 'pet surgery history documentation',
    audience: 'Owners recovering from orthopedic or soft-tissue surgery',
    keyDocuments: ['discharge packets', 'implant serial cards', 'recheck x-rays', 'physical therapy notes'],
    faq1: 'How long should I keep surgery records?',
    faq1a: 'Indefinitely for implants and major procedures; they affect future anesthesia decisions.',
    faq2: 'Should I photo incision progress?',
    faq2a: 'Daily photos during healing help telehealth triage if concerns arise.',
    faq3: 'What about rehab exercises?',
    faq3a: 'Log prescribed exercises and pain scores alongside official discharge sheets.',
  },
  {
    slug: 'allergy-and-reaction-history-for-pets',
    title: 'Pet Allergy and Adverse Reaction History: Log Template for Vets',
    excerpt:
      'Document food, environmental, and drug reactions with dates and severity so future prescriptions and diets stay safe.',
    category: 'pet-records',
    tags: ['pet allergies', 'adverse reactions', 'medical history'],
    cluster: 'medical-history',
    focus: 'pet allergy and reaction histories',
    audience: 'Owners managing allergic pets or prior drug sensitivities',
    keyDocuments: ['elimination diet logs', 'cytopoint or apoquel records', 'epi-pen equivalents', 'ER visit notes'],
    faq1: 'What belongs in a reaction log?',
    faq1a: 'Trigger, symptoms, onset time, treatment, and resolution date.',
    faq2: 'Should food trials be documented?',
    faq2a: 'Yes. Ingredient lists and trial duration prevent repeating failed diets.',
    faq3: 'Can photos of hives or swelling help?',
    faq3a: 'Photos with timestamps are valuable for telehealth and future visits.',
  },
  {
    slug: 'hereditary-conditions-family-pet-history',
    title: 'Hereditary Conditions in Pets: How to Document Family and Breed History',
    excerpt:
      'Capture breed predispositions, litter mate health, and parent history to inform screening schedules with your vet.',
    category: 'pet-records',
    tags: ['hereditary conditions', 'breed health', 'medical history'],
    cluster: 'medical-history',
    focus: 'hereditary and breed health history',
    audience: 'Owners of purebred or breeder-sourced pets',
    keyDocuments: ['pedigree notes', 'parent screening results', 'breeder health guarantees', 'genetic test reports'],
    faq1: 'Why document relatives if my pet is healthy?',
    faq1a: 'Family patterns guide early screening for hip, heart, or eye conditions.',
    faq2: 'Do genetic tests replace history?',
    faq2a: 'No. Tests plus family notes give the fullest picture.',
    faq3: 'Should I share history with new vets?',
    faq3a: 'Always. It shapes anesthesia, imaging, and wellness plans.',
  },
  {
    slug: 'rescue-pet-unknown-medical-history-guide',
    title: 'Rescue Pet Unknown History: How to Rebuild Medical Records from Scratch',
    excerpt:
      'Adopted with little history? Reconstruct vaccines, spay/neuter status, and baselines using shelter notes and new vet workups.',
    category: 'pet-records',
    tags: ['rescue pet', 'adoption records', 'unknown history'],
    cluster: 'medical-history',
    focus: 'rebuilding unknown pet medical history',
    audience: 'Adopters of shelter or stray pets with incomplete files',
    keyDocuments: ['shelter intake forms', 'foster vet notes', 'baseline lab work', 'new vaccine series'],
    faq1: 'What should the first vet visit cover?',
    faq1a: 'Exam, parasite screening, vaccine plan, and microchip verification.',
    faq2: 'How do I handle unknown vaccine status?',
    faq2a: 'Your vet may restart or titer; document the chosen plan clearly.',
    faq3: 'Can I still travel or board quickly?',
    faq3a: 'Plan ahead. Facilities need minimum vaccine windows before entry.',
  },
  {
    slug: 'second-opinion-vet-medical-history-prep',
    title: 'Preparing Pet Medical History for a Second Veterinary Opinion',
    excerpt:
      'Package labs, imaging, and treatment timelines for specialist consults without overwhelming the new clinician.',
    category: 'pet-records',
    tags: ['second opinion', 'specialist vet', 'medical records'],
    cluster: 'medical-history',
    focus: 'second opinion record preparation',
    audience: 'Owners seeking oncology, cardiology, or surgery consults',
    keyDocuments: ['referral letters', 'imaging discs', 'medication history', 'response notes to prior treatments'],
    faq1: 'How much history should I send ahead?',
    faq1a: 'Last 12 months plus anything defining chronic or surgical issues.',
    faq2: 'Should I write a one-page summary?',
    faq2a: 'Yes. Timeline plus current concerns helps specialists prepare.',
    faq3: 'What if records are contradictory?',
    faq3a: 'Note discrepancies and ask both clinics to clarify dates and doses.',
  },
];

const PET_PASSPORT_SEEDS: BlogSeed[] = [
  {
    slug: 'printable-pet-passport-template-emergency',
    title: 'Emergency Pet Passport Template: What to Include Before You Need It',
    excerpt:
      'Build a printable pet passport for emergencies - contacts, allergies, meds, and vet info you can hand to any clinic in seconds.',
    category: 'pet-records',
    tags: ['pet passport', 'emergency pet info', 'printable template'],
    cluster: 'pet-passports',
    focus: 'emergency pet passport templates',
    audience: 'Pet parents preparing for crises before they happen',
    keyDocuments: ['medication list', 'allergy summary', 'rabies certificate copy', 'microchip registration'],
    faq1: 'What is the difference between a passport and full records?',
    faq1a: 'A passport is a one-page critical summary; records hold full history.',
    faq2: 'Should passports live on paper only?',
    faq2a: 'Keep digital and printed copies for power outages or phone failure.',
    faq3: 'How often should passports update?',
    faq3a: 'After any medication, allergy, or contact change.',
  },
  {
    slug: 'pet-passport-for-groomers-and-trainers',
    title: 'Pet Passport for Groomers and Trainers: Share the Right Health Details',
    excerpt:
      'What groomers and trainers need in a pet passport - behavior flags, skin conditions, vaccine proof, and emergency contacts.',
    category: 'pet-records',
    tags: ['pet passport', 'groomer instructions', 'dog trainer'],
    cluster: 'pet-passports',
    focus: 'groomer and trainer pet passports',
    audience: 'Owners using frequent grooming or training services',
    keyDocuments: ['vaccine proof', 'skin condition notes', 'behavior triggers', 'vet authorization for sedated grooms'],
    faq1: 'Do groomers need full medical history?',
    faq1a: 'No. They need vaccines, allergies, and handling notes relevant to grooming.',
    faq2: 'Should anxiety medication appear on passports?',
    faq2a: 'Yes, if it affects appointments or handling safety.',
    faq3: 'Can I update passports after each visit?',
    faq3a: 'Update when coat/skin findings or behavior changes occur.',
  },
  {
    slug: 'pet-passport-allergy-medication-summary',
    title: 'Allergy and Medication Pet Passport: One-Page Summary for Any Caregiver',
    excerpt:
      'Create a focused passport highlighting drug allergies, chronic meds, and emergency protocols for sitters and family.',
    category: 'pet-records',
    tags: ['pet allergies', 'medication summary', 'pet passport'],
    cluster: 'pet-passports',
    focus: 'allergy and medication passports',
    audience: 'Owners of allergic or medicated pets',
    keyDocuments: ['prescription labels', 'allergy test results', 'ER protocols', 'preferred pharmacy'],
    faq1: 'Should food and drug allergies both appear?',
    faq1a: 'Yes. Separate them clearly to avoid confusion.',
    faq2: 'Include PRN emergency meds?',
    faq2a: 'List dose, route, and when your vet advised using them.',
    faq3: 'Who should get passport access?',
    faq3a: 'Anyone who may administer food or medication in your absence.',
  },
  {
    slug: 'multi-pet-passport-household-system',
    title: 'Multi-Pet Passport System: Keep Emergency Summaries Straight',
    excerpt:
      'Organize separate passports for each pet with household-level contacts and evacuation plans that scale.',
    category: 'pet-records',
    tags: ['multi-pet', 'pet passport', 'household emergency'],
    cluster: 'pet-passports',
    focus: 'multi-pet passport systems',
    audience: 'Multi-pet families and shared households',
    keyDocuments: ['per-pet med lists', 'carrier locations', 'species-specific diet notes'],
    faq1: 'Should passports look identical for each pet?',
    faq1a: 'Use the same template but never merge medication lists.',
    faq2: 'How do sitters tell pets apart quickly?',
    faq2a: 'Add photo, collar color, and microchip on each passport header.',
    faq3: 'Can one app manage all passports?',
    faq3a: 'Yes. PetClues supports multiple profiles with individual emergency cards.',
  },
  {
    slug: 'pet-passport-for-relatives-and-neighbors',
    title: 'Pet Passport for Relatives and Neighbors: Lightweight Access That Stays Safe',
    excerpt:
      'Share limited health summaries with nearby helpers - enough for emergencies without oversharing full medical history.',
    category: 'pet-records',
    tags: ['pet passport', 'neighbor pet care', 'family sharing'],
    cluster: 'pet-passports',
    focus: 'relative and neighbor pet passports',
    audience: 'Owners who rely on nearby friends or family for backup care',
    keyDocuments: ['emergency vet choice', 'medication schedule', 'feeding instructions', 'carrier location'],
    faq1: 'What should neighbors not see?',
    faq1a: 'Full financial records or unrelated historical diagnoses.',
    faq2: 'Is text export enough?',
    faq2a: 'A structured passport beats long text threads during stress.',
    faq3: 'How do I revoke access later?',
    faq3a: 'Use app sharing controls instead of static screenshots when possible.',
  },
  {
    slug: 'updating-pet-passport-after-vet-visit',
    title: 'Update Your Pet Passport After Every Vet Visit: 5-Minute Habit',
    excerpt:
      'A fast post-visit routine to refresh medications, weights, and follow-ups in your pet passport before you forget.',
    category: 'pet-records',
    tags: ['pet passport', 'vet visit', 'record update'],
    cluster: 'pet-passports',
    focus: 'post-visit pet passport updates',
    audience: 'Busy pet parents who want accurate emergency cards',
    keyDocuments: ['discharge summary', 'new prescriptions', 'weight from scale', 'recheck dates'],
    faq1: 'When exactly should I update the passport?',
    faq1a: 'In the car or lobby before you leave the clinic parking lot.',
    faq2: 'What if nothing changed?',
    faq2a: 'Still log the visit date and weight for trend tracking.',
    faq3: 'Should sitters get auto-notified?',
    faq3a: 'Re-share or ping sitters when medications change.',
  },
];

const PET_TRAVEL_SEEDS: BlogSeed[] = [
  {
    slug: 'international-pet-travel-health-certificate-guide',
    title: 'International Pet Travel Health Certificates: Timeline and Record Checklist',
    excerpt:
      'Navigate USDA endorsements, rabies timing, and parasite treatments for international pet travel without last-minute panic.',
    category: 'pet-records',
    tags: ['international pet travel', 'health certificate', 'USDA pet travel'],
    cluster: 'pet-travel',
    focus: 'international pet travel health certificates',
    audience: 'Owners planning overseas moves or vacations with pets',
    keyDocuments: ['USDA health certificates', 'rabies serology results', 'microchip proof', 'parasite treatment receipts'],
    faq1: 'How early should I start international paperwork?',
    faq1a: 'Often 30-180 days depending on destination country rules.',
    faq2: 'Does microchip timing matter?',
    faq2a: 'Yes. Many countries require chips before rabies vaccines used for export.',
    faq3: 'Where should I store endorsed certificates?',
    faq3a: 'Digital and printed copies in carry-on luggage plus cloud backup.',
  },
  {
    slug: 'flying-with-cats-health-documents-checklist',
    title: 'Flying With Cats: Health Documents and Carrier Prep Checklist',
    excerpt:
      'Airline-ready checklist for cat parents - vaccines, health forms, calming plans, and records for cabin or cargo travel.',
    category: 'cat-health',
    tags: ['flying with cats', 'airline pet travel', 'cat health forms'],
    cluster: 'pet-travel',
    focus: 'flying with cats documentation',
    audience: 'Cat parents booking flights with in-cabin or cargo options',
    keyDocuments: ['airline vet forms', 'rabies certificates', 'calming medication notes', 'carrier measurements'],
    faq1: 'Do airlines require health certificates for cats?',
    faq1a: 'Many do within 10 days of travel; confirm with your carrier.',
    faq2: 'Should I sedate my cat for flights?',
    faq2a: 'Only with explicit veterinary guidance documented in your records.',
    faq3: 'What if my cat has chronic conditions?',
    faq3a: 'Carry a one-page summary and medication labels in your carry-on.',
  },
  {
    slug: 'cross-country-move-pet-records-guide',
    title: 'Cross-Country Move With Pets: Medical Records and Vet Transition Guide',
    excerpt:
      'Relocating states? Transfer records, refill prescriptions, and find a new vet before moving day.',
    category: 'pet-records',
    tags: ['moving with pets', 'pet records', 'new state vet'],
    cluster: 'pet-travel',
    focus: 'cross-country pet record moves',
    audience: 'Families relocating long distances with dogs or cats',
    keyDocuments: ['full chart export', 'prescription transfers', 'rabies certificates', 'microchip updates'],
    faq1: 'When should I choose a new vet?',
    faq1a: 'Before move day so you have a clinic mapped near your new home.',
    faq2: 'How do I handle prescription refills mid-move?',
    faq2a: 'Request 30-60 day supplies and digital copies of labels.',
    faq3: 'Should travel days appear in health records?',
    faq3a: 'Note long transit, stress behaviors, and any medications given.',
  },
  {
    slug: 'pet-friendly-hotel-documentation-requirements',
    title: 'Pet-Friendly Hotel Stays: Documentation Hotels May Request',
    excerpt:
      'Vaccine proof, policy printouts, and emergency contacts for smooth check-in at pet-friendly hotels.',
    category: 'pet-records',
    tags: ['pet friendly hotel', 'travel with pets', 'vaccination proof'],
    cluster: 'pet-travel',
    focus: 'hotel pet documentation',
    audience: 'Travelers staying in hotels with pets',
    keyDocuments: ['rabies certificates', 'hotel policy confirmations', 'pet fee receipts', 'local vet contacts'],
    faq1: 'Do hotels require rabies proof?',
    faq1a: 'Some do, especially for longer stays or larger pets.',
    faq2: 'Should I bring flea prevention records?',
    faq2a: 'Helpful if policies mention parasite requirements.',
    faq3: 'What about emotional support documentation?',
    faq3a: 'Follow airline and property rules; keep legal documents separate from vaccine files.',
  },
  {
    slug: 'rv-travel-pet-medical-emergency-prep',
    title: 'RV Travel With Pets: Medical Emergency Prep and Records on the Road',
    excerpt:
      'Build a mobile pet health kit for RV trips - nearby vet lookup, medication backups, and offline record access.',
    category: 'pet-records',
    tags: ['RV travel pets', 'road trip pet health', 'emergency prep'],
    cluster: 'pet-travel',
    focus: 'RV travel pet medical prep',
    audience: 'Road-tripping pet parents living out of RVs or vans',
    keyDocuments: ['offline record exports', 'medication backups', 'national vet chains list', 'insurance cards'],
    faq1: 'How do I access records without cell service?',
    faq1a: 'Download PDFs or use an app with offline-friendly summaries.',
    faq2: 'Should I pre-map vets along the route?',
    faq2a: 'Yes. Save 24-hour clinics for each major stop.',
    faq3: 'What belongs in a road emergency kit?',
    faq3a: 'Copies of passports, extra meds, gauze, and hydration supplies.',
  },
];

const MEDICATION_SEEDS: BlogSeed[] = [
  {
    slug: 'split-dose-pet-medication-schedule-guide',
    title: 'Split-Dose Pet Medications: How to Schedule Twice-Daily and Weekly Doses',
    excerpt:
      'Master split dosing for antibiotics, steroids, and chronic meds with reminders that match your household routine.',
    category: 'pet-records',
    tags: ['pet medication schedule', 'split dose', 'medication reminder'],
    cluster: 'medication-management',
    focus: 'split-dose medication scheduling',
    audience: 'Owners juggling twice-daily or complex medication times',
    keyDocuments: ['prescription labels', 'taper schedules', 'pharmacy handouts', 'dose reaction notes'],
    faq1: 'What if I miss a split dose?',
    faq1a: 'Call your vet or pharmacist; do not double doses without guidance.',
    faq2: 'Can reminders align with human routines?',
    faq2a: 'Yes. Anchor doses to breakfast, dinner, or commute times.',
    faq3: 'Should taper instructions be stored separately?',
    faq3a: 'Attach taper charts to the prescription event in your timeline.',
  },
  {
    slug: 'pet-prescription-refill-tracking-system',
    title: 'Pet Prescription Refill Tracking: Never Run Out of Chronic Medications',
    excerpt:
      'Track refills, pharmacy contacts, and authorization expirations for chronic pet prescriptions.',
    category: 'pet-records',
    tags: ['prescription refill', 'pet pharmacy', 'chronic medication'],
    cluster: 'medication-management',
    focus: 'prescription refill tracking',
    audience: 'Owners managing long-term prescriptions',
    keyDocuments: ['refill labels', 'authorization dates', 'compounding pharmacy contacts'],
    faq1: 'How early should I request refills?',
    faq1a: 'Often 5-7 days before the bottle runs out, sooner for compounding.',
    faq2: 'Do online pharmacies need separate records?',
    faq2a: 'Store order confirmations alongside vet authorization notes.',
    faq3: 'What if my vet requires bloodwork before refill?',
    faq3a: 'Set paired reminders for labs and prescription renewal dates.',
  },
  {
    slug: 'compounded-pet-medication-label-guide',
    title: 'Compounded Pet Medications: How to Read Labels and Track Shelf Life',
    excerpt:
      'Understand compounded prescriptions - concentration, beyond-use dates, and storage - with digital label backups.',
    category: 'pet-records',
    tags: ['compounded medication', 'pet pharmacy', 'prescription labels'],
    cluster: 'medication-management',
    focus: 'compounded medication documentation',
    audience: 'Owners using compounding pharmacies for custom doses',
    keyDocuments: ['compound labels', 'beyond-use dates', 'flavoring notes', 'shipping receipts'],
    faq1: 'Why do compounded meds expire faster?',
    faq1a: 'Stability varies without commercial packaging; beyond-use dates are strict.',
    faq2: 'Should I photo every new bottle?',
    faq2a: 'Yes. Labels wear off; photos preserve concentration details.',
    faq3: 'Can I freeze or split compounded liquids?',
    faq3a: 'Only per pharmacist instructions recorded in your notes.',
  },
  {
    slug: 'antibiotic-course-completion-tracking-pets',
    title: 'Finish the Full Antibiotic Course: Tracking Tips for Pet Parents',
    excerpt:
      'Ensure every antibiotic dose is given on schedule until completion with logs that help your vet assess response.',
    category: 'pet-records',
    tags: ['pet antibiotics', 'medication adherence', 'infection treatment'],
    cluster: 'medication-management',
    focus: 'antibiotic course tracking',
    audience: 'Owners treating acute infections at home',
    keyDocuments: ['antibiotic labels', 'dose checklists', 'recheck appointment notes'],
    faq1: 'What if my pet spits out liquid meds?',
    faq1a: 'Log missed doses and call your vet; do not guess replacements.',
    faq2: 'Should I stop early if symptoms improve?',
    faq2a: 'No unless your veterinarian explicitly advises stopping.',
    faq3: 'How do I track multiple pets on meds?',
    faq3a: 'Separate profiles prevent dangerous cross-dosing mistakes.',
  },
  {
    slug: 'pain-management-log-for-recovering-pets',
    title: 'Pet Pain Management Log: Track Comfort During Recovery',
    excerpt:
      'Daily pain and mobility logs for post-surgery or injury recovery help your vet titrate medications safely.',
    category: 'pet-records',
    tags: ['pet pain management', 'post-surgery', 'recovery log'],
    cluster: 'medication-management',
    focus: 'pain management logging',
    audience: 'Owners managing post-operative or chronic pain meds',
    keyDocuments: ['pain scores', 'gabapentin or NSAID schedules', 'physical therapy notes'],
    faq1: 'What scale should I use for pain?',
    faq1a: 'Many vets use 0-10 or simple low/medium/high with behavior notes.',
    faq2: 'Should I log side effects like sedation?',
    faq2a: 'Yes. Sedation patterns guide dose adjustments.',
    faq3: 'How long should I keep pain logs?',
    faq3a: 'Through recovery plus one follow-up visit minimum.',
  },
];

const EMERGENCY_SEEDS: BlogSeed[] = [
  {
    slug: 'pet-first-aid-kit-records-checklist',
    title: 'Pet First Aid Kit Plus Records Checklist for Home and Car',
    excerpt:
      'Combine physical first aid supplies with digital records so emergencies get supplies and history in one grab.',
    category: 'pet-records',
    tags: ['pet first aid', 'emergency kit', 'pet records'],
    cluster: 'emergency-preparedness',
    focus: 'pet first aid and record kits',
    audience: 'Owners building home and car emergency readiness',
    keyDocuments: ['passport printouts', 'insurance cards', 'poison control numbers', 'medication list'],
    faq1: 'What records belong in a first aid kit?',
    faq1a: 'One-page passport, rabies proof, and active prescription summary.',
    faq2: 'How often should kits be refreshed?',
    faq2a: 'Quarterly for supplies; after every medication change for papers.',
    faq3: 'Should kids know where kits live?',
    faq3a: 'Yes, with clear labels and emergency numbers posted nearby.',
  },
  {
    slug: 'natural-disaster-pet-evacuation-records',
    title: 'Natural Disaster Pet Evacuation: Records to Grab in Under 10 Minutes',
    excerpt:
      'Fire, flood, or hurricane prep for pet parents - grab-list for documents, meds, and identifiers when minutes matter.',
    category: 'pet-records',
    tags: ['pet evacuation', 'disaster prep', 'emergency records'],
    cluster: 'emergency-preparedness',
    focus: 'disaster evacuation pet records',
    audience: 'Owners in wildfire, hurricane, or flood-prone regions',
    keyDocuments: ['microchip registrations', 'vaccine folders', 'medication bottles', 'carrier photos'],
    faq1: 'What if I only have time for one item?',
    faq1a: 'Grab medications plus a phone with digital records if charged.',
    faq2: 'Should carriers be labeled with records?',
    faq2a: 'Tape passport summaries inside carrier lids.',
    faq3: 'How do shelters verify ownership?',
    faq3a: 'Microchip registration and photos help reunification.',
  },
  {
    slug: 'pet-poison-control-information-card-guide',
    title: 'Pet Poison Control Card: Numbers, Substances, and History to Pre-Load',
    excerpt:
      'Pre-build a poison exposure card with ASPCA or Pet Poison Helpline details, current weights, and medication lists.',
    category: 'pet-records',
    tags: ['pet poison control', 'emergency card', 'toxicity'],
    cluster: 'emergency-preparedness',
    focus: 'poison control information cards',
    audience: 'Owners who want faster toxicity triage',
    keyDocuments: ['weight history', 'medication list', 'known toxins in home', 'helpline membership receipts'],
    faq1: 'Should chocolate or xylitol risks be listed?',
    faq1a: 'List household-specific hazards you know your pet has accessed.',
    faq2: 'Do I need my pet’s weight on the card?',
    faq2a: 'Yes. Dose guidance depends on accurate weight.',
    faq3: 'When should I call poison control vs my vet?',
    faq3a: 'Call poison control immediately for known ingestions; involve your vet next.',
  },
  {
    slug: 'after-hours-emergency-vet-information-sheet',
    title: 'After-Hours Emergency Vet Sheet: Contacts, Directions, and Records',
    excerpt:
      'Build a one-page sheet for overnight emergencies - ER addresses, triage numbers, and critical health history.',
    category: 'pet-records',
    tags: ['emergency vet', 'after hours vet', 'pet ER'],
    cluster: 'emergency-preparedness',
    focus: 'after-hours emergency vet sheets',
    audience: 'Owners who want faster ER navigation at night',
    keyDocuments: ['ER fee policies', 'blood type or transfusion notes', 'recent lab summaries'],
    faq1: 'Should I map multiple ER clinics?',
    faq1a: 'Yes. Primary and backup options prevent delays if one is on diversion.',
    faq2: 'Include primary vet relationship?',
    faq2a: 'ER staff often contact your regular clinic for history.',
    faq3: 'What meds must be listed prominently?',
    faq3a: 'Blood thinners, steroids, insulin, and seizure medications.',
  },
  {
    slug: 'lost-pet-search-medical-summary-template',
    title: 'Lost Pet Search: Medical Summary Template for Posters and Shelters',
    excerpt:
      'When pets go missing, medical summaries help shelters administer meds and avoid dangerous foods or drugs.',
    category: 'pet-records',
    tags: ['lost pet', 'missing pet', 'medical summary'],
    cluster: 'emergency-preparedness',
    focus: 'lost pet medical summaries',
    audience: 'Owners preparing for worst-case separation scenarios',
    keyDocuments: ['distinctive markings photos', 'medication needs', 'microchip paperwork', 'behavior notes'],
    faq1: 'Should medical needs go on public posters?',
    faq1a: 'Share detailed meds with shelters privately; posters can note “needs daily medication.”',
    faq2: 'How do records speed shelter intake?',
    faq2a: 'Staff can continue prescriptions while you are located.',
    faq3: 'Can PetClues passports help?',
    faq3a: 'Yes. Export a summary while generating search posters.',
  },
  {
    slug: 'household-fire-safety-pet-records-plan',
    title: 'Household Fire Safety for Pets: Records, Stickers, and Evacuation Roles',
    excerpt:
      'Fire safety planning with pet alert stickers, leashes by exits, and cloud-backed records if paper burns.',
    category: 'pet-records',
    tags: ['fire safety pets', 'evacuation plan', 'pet emergency'],
    cluster: 'emergency-preparedness',
    focus: 'fire safety pet record plans',
    audience: 'Homeowners and renters with indoor pets',
    keyDocuments: ['digital record backups', 'pet alert window stickers', 'lease pet policies'],
    faq1: 'Where should leashes and carriers live?',
    faq1a: 'Near exits you use during drills, not only by the bed.',
    faq2: 'Are window stickers still recommended?',
    faq2a: 'Many fire departments appreciate them with pet count noted.',
    faq3: 'How often run evacuation drills with pets?',
    faq3a: 'Twice a year including nighttime scenarios.',
  },
];

const ORGANIZATION_SEEDS: BlogSeed[] = [
  {
    slug: 'monthly-pet-care-admin-routine-guide',
    title: 'Monthly Pet Care Admin Day: Records, Refills, and Reminder Reset',
    excerpt:
      'A repeatable monthly admin routine to audit pet records, confirm refills, and fix reminder gaps in under an hour.',
    category: 'petclues-guides',
    tags: ['pet care routine', 'organization', 'monthly checklist'],
    cluster: 'pet-organization',
    focus: 'monthly pet care admin routines',
    audience: 'Busy owners who want predictable organization time',
    keyDocuments: ['upcoming appointment list', 'refill inventory', 'missing document queue'],
    faq1: 'What day works best for admin time?',
    faq1a: 'Same calendar day each month builds habit faster than random catch-up.',
    faq2: 'Should admin include grooming and supplies?',
    faq2a: 'Yes. Tie supply orders to upcoming seasons or travel.',
    faq3: 'Can PetClues score guide admin day?',
    faq3a: 'PetCare Score highlights gaps to fix first each month.',
  },
  {
    slug: 'pet-supply-inventory-and-medication-sync',
    title: 'Sync Pet Supply Inventory With Medication and Preventive Schedules',
    excerpt:
      'Align food, litter, flea prevention, and prescription inventory so you never scramble the night before a dose.',
    category: 'petclues-guides',
    tags: ['pet supplies', 'inventory', 'medication sync'],
    cluster: 'pet-organization',
    focus: 'supply and medication inventory sync',
    audience: 'Owners ordering supplies online or in bulk',
    keyDocuments: ['auto-ship schedules', 'preventive calendars', 'prescription inventories'],
    faq1: 'How early trigger reorder reminders?',
    faq1a: '7-10 days before run-out for meds; 2 weeks for food.',
    faq2: 'Should flea and heartworm share one calendar?',
    faq2a: 'Link them visually but keep product-specific notes.',
    faq3: 'What about refrigerated meds?',
    faq3a: 'Track fridge inventory separately with beyond-use alerts.',
  },
  {
    slug: 'shared-family-pet-care-calendar-system',
    title: 'Shared Family Pet Care Calendar: Stop Assuming Someone Else Did It',
    excerpt:
      'Coordinate walks, meds, and vet trips across partners and teens with shared calendars tied to health records.',
    category: 'petclues-guides',
    tags: ['family pet care', 'shared calendar', 'pet organization'],
    cluster: 'pet-organization',
    focus: 'shared family pet care calendars',
    audience: 'Households with multiple caregivers',
    keyDocuments: ['task assignments', 'medication checkoffs', 'vet appointment invites'],
    faq1: 'Do calendars replace reminders?',
    faq1a: 'Use both. Calendars plan; reminders nag at the right moment.',
    faq2: 'How handle co-parenting pets?',
    faq2a: 'Shared read access to records prevents conflicting treatments.',
    faq3: 'Should kids get tasks in the system?',
    faq3a: 'Age-appropriate tasks with verification reduce missed doses.',
  },
  {
    slug: 'pet-binder-vs-digital-records-comparison',
    title: 'Pet Binder vs Digital Records: Which System Wins for Your Household',
    excerpt:
      'Compare paper binders and digital pet health apps on search, sharing, reminders, and emergency readiness.',
    category: 'petclues-guides',
    tags: ['pet binder', 'digital pet records', 'organization'],
    cluster: 'pet-organization',
    focus: 'pet binder versus digital records',
    audience: 'Owners debating paper vs app organization',
    keyDocuments: ['binder dividers', 'sheet protectors', 'cloud backups'],
    faq1: 'Are binders bad?',
    faq1a: 'No, but they lack reminders and remote sharing unless paired with digital tools.',
    faq2: 'Can I use both?',
    faq2a: 'Yes. Many owners archive originals digitally and keep slim binders for travel.',
    faq3: 'What wins for emergencies?',
    faq3a: 'Digital passports accessible from your phone.',
  },
  {
    slug: 'end-of-year-pet-health-records-review',
    title: 'End-of-Year Pet Health Records Review: 12-Month Audit Checklist',
    excerpt:
      'Annual review checklist for vaccines, dental, labs, and insurance - close the year with zero surprise gaps.',
    category: 'pet-records',
    tags: ['annual review', 'pet health records', 'year end checklist'],
    cluster: 'pet-organization',
    focus: 'annual pet health record reviews',
    audience: 'Owners who want a yearly reset ritual',
    keyDocuments: ['year of invoices', 'insurance EOBs', 'weight trends', 'vaccine due list'],
    faq1: 'When should the annual review happen?',
    faq1a: 'December or before renewal-heavy months like spring travel.',
    faq2: 'Include financial totals?',
    faq2a: 'Yes for budgeting and insurance planning.',
    faq3: 'What if I found missing boosters?',
    faq3a: 'Book catch-up visits early in the new year.',
  },
];

const BREED_SEEDS: BlogSeed[] = [
  {
    slug: 'golden-retriever-health-records-wellness-guide',
    title: 'Golden Retriever Health Records: Cancers, Hips, and Heart Screening Guide',
    excerpt:
      'Breed-focused wellness tracking for Golden Retrievers - cancer awareness, hip scores, cardiac exams, and weight logs.',
    category: 'dog-health',
    tags: ['golden retriever', 'breed health', 'dog wellness'],
    cluster: 'breed-specific-care',
    focus: 'Golden Retriever health record tracking',
    audience: 'Golden Retriever parents planning proactive screening',
    keyDocuments: ['OFA hip results', 'cardiac auscultation notes', 'lump maps', 'weight charts'],
    faq1: 'Which screenings matter most for Goldens?',
    faq1a: 'Discuss hip, elbow, cardiac, and cancer surveillance with your vet.',
    faq2: 'Should I map skin lumps at home?',
    faq2a: 'Monthly lump checks with photos help early vet evaluation.',
    faq3: 'How do records help oncology consults?',
    faq3a: 'Growth timelines and prior cytology speed decisions.',
  },
  {
    slug: 'labrador-weight-and-joint-care-records',
    title: 'Labrador Health Records: Weight, Joints, and Exercise Logging',
    excerpt:
      'Keep Labs lean with weight trends, joint supplements, and swim therapy notes tied to orthopedic history.',
    category: 'dog-health',
    tags: ['labrador', 'dog weight', 'joint care'],
    cluster: 'breed-specific-care',
    focus: 'Labrador weight and joint record keeping',
    audience: 'Labrador owners preventing obesity-related joint stress',
    keyDocuments: ['body condition scores', 'joint supplement labels', 'PT session notes'],
    faq1: 'How often weigh a Labrador?',
    faq1a: 'Monthly at home; confirm at wellness visits.',
    faq2: 'Should exercise appear in records?',
    faq2a: 'Yes when managing lameness or post-injury rehab.',
    faq3: 'Do Labs need earlier hip screening?',
    faq3a: 'Discuss timing with your vet especially if limping occurs young.',
  },
  {
    slug: 'french-bulldog-respiratory-health-tracking',
    title: 'French Bulldog Health Records: Respiratory, Skin, and Spine Notes',
    excerpt:
      'Document BOAS assessments, skin fold care, and spinal precautions for French Bulldogs in one timeline.',
    category: 'dog-health',
    tags: ['french bulldog', 'BOAS', 'brachycephalic'],
    cluster: 'breed-specific-care',
    focus: 'French Bulldog respiratory health tracking',
    audience: 'Frenchie parents managing breed-specific risks',
    keyDocuments: ['airway exam notes', 'dermatology treatments', 'IVDD precautions'],
    faq1: 'What is BOAS documentation?',
    faq1a: 'Surgical and exam notes about airway obstruction severity.',
    faq2: 'Should temperature sensitivity be noted?',
    faq2a: 'Yes. Heat intolerance guides exercise and travel plans.',
    faq3: 'Track skin fold infections?',
    faq3a: 'Log products used and flare frequency for your dermatologist.',
  },
  {
    slug: 'german-shepherd-hip-health-documentation',
    title: 'German Shepherd Hip and Mobility Health Documentation Guide',
    excerpt:
      'Track hip dysplasia screens, arthritis meds, and mobility aids for German Shepherds across their lifespan.',
    category: 'dog-health',
    tags: ['german shepherd', 'hip dysplasia', 'mobility'],
    cluster: 'breed-specific-care',
    focus: 'German Shepherd hip health documentation',
    audience: 'GSD owners monitoring orthopedic health',
    keyDocuments: ['radiograph reports', 'PennHIP or OFA results', 'NSAID monitoring labs'],
    faq1: 'When should hip screening start?',
    faq1a: 'Discuss timing with your vet if lameness or bunny-hopping appears.',
    faq2: 'Should I log gait videos?',
    faq2a: 'Short videos during flare-ups help remote ortho consults.',
    faq3: 'Include rehab milestones?',
    faq3a: 'Yes for insurance and specialist continuity.',
  },
  {
    slug: 'poodle-grooming-and-health-record-routine',
    title: 'Poodle Grooming and Health Records: Skin, Ears, and Dental Tracking',
    excerpt:
      'Pair professional grooms with ear infection history, dental care, and allergy notes for Standard, Mini, and Toy Poodles.',
    category: 'dog-health',
    tags: ['poodle', 'dog grooming', 'ear infections'],
    cluster: 'breed-specific-care',
    focus: 'Poodle grooming and health routines',
    audience: 'Poodle owners linking coat care to medical issues',
    keyDocuments: ['groomer notes', 'ear cytology', 'dental charts', 'allergy diets'],
    faq1: 'Why tie grooms to health records?',
    faq1a: 'Groomers often spot mats, parasites, and skin changes first.',
    faq2: 'How often document ear issues?',
    faq2a: 'After every infection with prescribed drops and recheck dates.',
    faq3: 'Should dental frequency be breed-specific?',
    faq3a: 'Many Poodles need consistent dental prevention logged yearly.',
  },
  {
    slug: 'maine-coon-cat-health-monitoring-guide',
    title: 'Maine Coon Cat Health Monitoring: Heart, HCM, and Weight Records',
    excerpt:
      'Screening-focused records for Maine Coons - HCM echoes, weight, and joint-friendly exercise notes.',
    category: 'cat-health',
    tags: ['maine coon', 'cat HCM', 'breed health'],
    cluster: 'breed-specific-care',
    focus: 'Maine Coon health monitoring',
    audience: 'Maine Coon parents prioritizing cardiac screening',
    keyDocuments: ['echocardiogram reports', 'genetic test results', 'weight logs'],
    faq1: 'How often echo Maine Coons?',
    faq1a: 'Follow cardiologist guidance; many start in young adulthood.',
    faq2: 'Should weight be tracked more often?',
    faq2a: 'Monthly weights help catch early heart-related changes.',
    faq3: 'Do joint issues appear in Maine Coons?',
    faq3a: 'Log mobility changes especially in large seniors.',
  },
  {
    slug: 'siamese-cat-vaccination-and-wellness-records',
    title: 'Siamese Cat Wellness Records: Dental, Respiratory, and Vaccine History',
    excerpt:
      'Wellness documentation tailored to Siamese cats - dental disease trends, asthma notes, and vaccine timelines.',
    category: 'cat-health',
    tags: ['siamese cat', 'cat wellness', 'feline dental'],
    cluster: 'breed-specific-care',
    focus: 'Siamese cat wellness records',
    audience: 'Siamese cat owners tracking breed-typical issues',
    keyDocuments: ['dental procedure notes', 'inhaler protocols', 'FVRCP history'],
    faq1: 'Are respiratory issues common in Siamese?',
    faq1a: 'Some lines are asthma-prone; document triggers and meds.',
    faq2: 'Should dental cleanings be logged aggressively?',
    faq2a: 'Yes. Early dental disease is common in the breed.',
    faq3: 'Indoor Siamese still need full vaccine records?',
    faq3a: 'Yes for boarding, travel, and regional requirements.',
  },
  {
    slug: 'dachshund-back-health-mobility-tracking',
    title: 'Dachshund Back Health: IVDD Prevention Logs and Recovery Records',
    excerpt:
      'Track ramp use, crate rest, neurologic checks, and surgery history for Dachshunds at risk of IVDD.',
    category: 'dog-health',
    tags: ['dachshund', 'IVDD', 'back health'],
    cluster: 'breed-specific-care',
    focus: 'Dachshund back health tracking',
    audience: 'Dachshund owners preventing and managing IVDD',
    keyDocuments: ['neuro exam notes', 'MRI reports', 'crate rest schedules', 'weight logs'],
    faq1: 'Should I log daily mobility checks?',
    faq1a: 'Brief yes/no checks catch early back pain sooner.',
    faq2: 'Document furniture rules?',
    faq2a: 'Note ramp training and off-limit jumps for sitters.',
    faq3: 'How long keep post-op records?',
    faq3a: 'Lifetime, for any future spinal episode.',
  },
];

const SENIOR_SEEDS: BlogSeed[] = [
  {
    slug: 'senior-cat-medication-and-lab-tracking-guide',
    title: 'Senior Cat Medication and Lab Tracking: Kidney, Thyroid, and Pain Logs',
    excerpt:
      'Organize senior cat labs and medications for CKD, hyperthyroidism, and arthritis with reminder-friendly workflows.',
    category: 'cat-health',
    tags: ['senior cat', 'kidney disease', 'thyroid cat'],
    cluster: 'senior-pet-care',
    focus: 'senior cat medication and lab tracking',
    audience: 'Owners of cats over 10 managing chronic labs',
    keyDocuments: ['SDMA and creatinine trends', 'methimazole doses', 'blood pressure readings'],
    faq1: 'How often should senior cats get labs?',
    faq1a: 'Often every 6-12 months; more frequent with CKD or thyroid disease.',
    faq2: 'Track subcutaneous fluids at home?',
    faq2a: 'Log volume and frequency to share with your vet.',
    faq3: 'Should appetite be part of the record?',
    faq3a: 'Daily appetite notes contextualize lab shifts.',
  },
  {
    slug: 'senior-pet-mobility-pain-journal-template',
    title: 'Senior Pet Mobility Journal: Pain Scores, Good Days, and Med Adjustments',
    excerpt:
      'A simple journal for senior dogs and cats to track stiffness, good/bad days, and response to pain medications.',
    category: 'dog-health',
    tags: ['senior pet', 'mobility', 'pain journal'],
    cluster: 'senior-pet-care',
    focus: 'senior pet mobility journaling',
    audience: 'Owners of aging pets on arthritis protocols',
    keyDocuments: ['pain med schedules', 'laser therapy notes', 'assistive device fittings'],
    faq1: 'What belongs in a mobility journal?',
    faq1a: 'Stairs climbed, walk length, limping yes/no, and sleep quality.',
    faq2: 'How long before vet adjustments?',
    faq2a: 'Bring 2-4 weeks of entries to medication reviews.',
    faq3: 'Include complementary therapies?',
    faq3a: 'Yes. Acupuncture and PT sessions affect outcomes.',
  },
  {
    slug: 'end-of-life-pet-comfort-care-documentation',
    title: 'End-of-Life Pet Comfort Care: Document Wishes Before Crisis Decisions',
    excerpt:
      'Capture quality-of-life scales, hospice meds, and family decisions while your pet is stable enough to plan.',
    category: 'pet-records',
    tags: ['pet hospice', 'quality of life', 'senior pet'],
    cluster: 'senior-pet-care',
    focus: 'end-of-life comfort care documentation',
    audience: 'Families navigating senior pet decline',
    keyDocuments: ['QOL scales', 'hospice vet contacts', 'cremation preferences', 'pain protocols'],
    faq1: 'When start documenting end-of-life wishes?',
    faq1a: 'Early. Calm conversations prevent rushed crisis choices.',
    faq2: 'Should children be included in notes?',
    faq2a: 'Family-aligned wishes reduce conflict later.',
    faq3: 'Are QOL apps useful?',
    faq3a: 'Structured scales help weekly vet conversations.',
  },
  {
    slug: 'senior-pet-cognitive-decline-behavior-log',
    title: 'Senior Pet Cognitive Decline: Behavior Log for CDS and Night Wandering',
    excerpt:
      'Track disorientation, sleep-wake changes, and accidents to discuss canine or feline cognitive dysfunction with your vet.',
    category: 'dog-health',
    tags: ['cognitive dysfunction', 'senior dog', 'senior cat'],
    cluster: 'senior-pet-care',
    focus: 'senior pet cognitive decline logging',
    audience: 'Owners noticing confusion or night waking in seniors',
    keyDocuments: ['CDS medication notes', 'sleep logs', 'house soiling incidents'],
    faq1: 'What behaviors suggest cognitive decline?',
    faq1a: 'Staring, getting stuck, altered sleep, and new anxiety.',
    faq2: 'How detailed should logs be?',
    faq2a: 'Daily one-line notes for 2-3 weeks before vet visits.',
    faq3: 'Can environment changes be tracked?',
    faq3a: 'Yes. Note night lights, crate moves, or puzzle feeders.',
  },
  {
    slug: 'arthritis-management-records-senior-dogs',
    title: 'Arthritis Management Records for Senior Dogs: NSAIDs, Labs, and Rehab',
    excerpt:
      'Monitor NSAID bloodwork, joint supplements, and rehab exercises for arthritic senior dogs with one timeline.',
    category: 'dog-health',
    tags: ['arthritis dogs', 'senior dog', 'NSAID monitoring'],
    cluster: 'senior-pet-care',
    focus: 'senior dog arthritis management records',
    audience: 'Owners of arthritic dogs on long-term pain plans',
    keyDocuments: ['NSAID monitoring labs', 'joint supplement labels', 'underwater treadmill notes'],
    faq1: 'How often repeat NSAID bloodwork?',
    faq1a: 'Per vet protocol, often semiannual for long-term use.',
    faq2: 'Should weight loss appear in arthritis records?',
    faq2a: 'Yes. Weight is a treatment with measurable outcomes.',
    faq3: 'Track good and bad weather days?',
    faq3a: 'Weather-linked stiffness notes help dose conversations.',
  },
  {
    slug: 'senior-pet-nutrition-and-weight-trends',
    title: 'Senior Pet Nutrition Records: Weight Trends, Diets, and Lab Correlations',
    excerpt:
      'Link senior diet changes to weight and lab trends so you and your vet see what is working.',
    category: 'pet-records',
    tags: ['senior pet nutrition', 'weight trends', 'prescription diet'],
    cluster: 'senior-pet-care',
    focus: 'senior pet nutrition documentation',
    audience: 'Owners adjusting senior prescription diets',
    keyDocuments: ['diet transition notes', 'calorie targets', 'BCS charts', 'lab trends'],
    faq1: 'How often weigh senior pets?',
    faq1a: 'Monthly minimum; weekly during intentional weight loss.',
    faq2: 'Should treats be logged?',
    faq2a: 'Yes when managing diabetes, kidney, or weight issues.',
    faq3: 'Can multiple diets be compared in records?',
    faq3a: 'Note start/end dates and associated lab changes.',
  },
  {
    slug: 'hospice-vet-coordination-records-guide',
    title: 'Hospice Vet Coordination: Records to Share Between Primary and Palliative Care',
    excerpt:
      'Coordinate primary vets and hospice teams with medication reconciliation, comfort goals, and after-hours plans.',
    category: 'pet-records',
    tags: ['pet hospice vet', 'palliative care', 'senior pet'],
    cluster: 'senior-pet-care',
    focus: 'hospice veterinary coordination records',
    audience: 'Families using multiple vets for palliative care',
    keyDocuments: ['medication reconciliation lists', 'comfort goal worksheets', 'after-hours protocols'],
    faq1: 'Who owns medication changes in hospice?',
    faq1a: 'Document which clinician authorized each change.',
    faq2: 'Should euthanasia preferences be written?',
    faq2a: 'Yes, while everyone can think clearly.',
    faq3: 'How share updates with family abroad?',
    faq3a: 'Digital timelines beat fragmented texts.',
  },
];

const NEW_PET_SEEDS: BlogSeed[] = [
  {
    slug: 'first-30-days-new-dog-owner-records-guide',
    title: 'First 30 Days as a New Dog Owner: Records, Vets, and Reminders',
    excerpt:
      'Day-by-day record checklist for new dog parents - microchip, vaccines, training, and pet health app setup.',
    category: 'dog-health',
    tags: ['new dog owner', 'puppy records', 'first 30 days'],
    cluster: 'new-pet-owner-guides',
    focus: 'first 30 days dog owner records',
    audience: 'First-time dog parents in the first month',
    keyDocuments: ['adoption contracts', 'vaccine series', 'microchip papers', 'pet insurance quotes'],
    faq1: 'What vet visit happens first?',
    faq1a: 'Within the first week for exam and vaccine plan confirmation.',
    faq2: 'When set up pet insurance?',
    faq2a: 'Ideally before unexpected illnesses; compare during week one.',
    faq3: 'Should training milestones be logged?',
    faq3a: 'Yes. Behavior notes help future trainers and vets.',
  },
  {
    slug: 'first-30-days-new-cat-owner-records-guide',
    title: 'First 30 Days as a New Cat Owner: Vet Visits, Vaccines, and Litter Logs',
    excerpt:
      'New cat parent guide for litter habits, hiding periods, vaccines, and organizing your first vet relationship.',
    category: 'cat-health',
    tags: ['new cat owner', 'kitten records', 'first 30 days'],
    cluster: 'new-pet-owner-guides',
    focus: 'first 30 days cat owner records',
    audience: 'First-time cat parents bringing home a new cat',
    keyDocuments: ['shelter medical notes', 'FVRCP schedule', 'spay/neuter certificate', 'litter logs'],
    faq1: 'How long should hiding last?',
    faq1a: 'Log hiding duration; mention if it exceeds a week without eating.',
    faq2: 'When introduce other pets?',
    faq2a: 'Document slow introductions with dates and setbacks.',
    faq3: 'Track litter box issues from day one?',
    faq3a: 'Yes. Baseline habits help future urinary diagnoses.',
  },
  {
    slug: 'adopting-shelter-pet-medical-records-setup',
    title: 'Adopting a Shelter Pet: Medical Records Setup From Day One',
    excerpt:
      'Translate shelter intake forms into a long-term health timeline with reminders for boosters and follow-ups.',
    category: 'pet-records',
    tags: ['shelter adoption', 'rescue pet records', 'adoption medical'],
    cluster: 'new-pet-owner-guides',
    focus: 'shelter adoption medical record setup',
    audience: 'New adopters from shelters and rescues',
    keyDocuments: ['intake vaccines', 'deworming dates', 'behavior assessments', 'foster vet notes'],
    faq1: 'Are shelter vaccines always complete?',
    faq1a: 'Often partial; your vet completes the series.',
    faq2: 'Should foster notes be saved?',
    faq2a: 'Yes. They reveal triggers and interim treatments.',
    faq3: 'When schedule spay/neuter if not done?',
    faq3a: 'Book promptly per clinic policy and document recovery.',
  },
  {
    slug: 'puppy-socialization-health-record-guide',
    title: 'Puppy Socialization and Health Records: Balance Safety With Exposure',
    excerpt:
      'Log safe socialization milestones alongside vaccine dates so you expand experiences without immunity gaps.',
    category: 'dog-health',
    tags: ['puppy socialization', 'puppy health', 'vaccine timing'],
    cluster: 'new-pet-owner-guides',
    focus: 'puppy socialization health records',
    audience: 'Puppy parents balancing socialization and vaccines',
    keyDocuments: ['vaccine dates', 'class requirements', 'exposure notes', 'trainer contacts'],
    faq1: 'Can socialization appear in health records?',
    faq1a: 'Yes. Stressful events affect wellness and behavior consults.',
    faq2: 'What exposures should be logged?',
    faq2a: 'New dogs, surfaces, sounds, and travel with dates.',
    faq3: 'How tie to vaccine timing?',
    faq3a: 'Note which doses were complete before each exposure.',
  },
  {
    slug: 'kitten-indoor-transition-wellness-checklist',
    title: 'Kitten Indoor Transition Checklist: Wellness, Litter, and Vaccine Records',
    excerpt:
      'Help kittens settle indoors while tracking vaccines, parasite prevention, and first vet relationships.',
    category: 'cat-health',
    tags: ['kitten checklist', 'indoor kitten', 'wellness'],
    cluster: 'new-pet-owner-guides',
    focus: 'kitten indoor transition wellness',
    audience: 'Owners transitioning kittens to permanent indoor homes',
    keyDocuments: ['parasite prevention', 'litter training notes', 'FVRCP boosters', 'microchip registration'],
    faq1: 'When kittens fully vaccinated?',
    faq1a: 'Often by 16-20 weeks for core series; confirm with your vet.',
    faq2: 'Should enrichment be documented?',
    faq2a: 'Optional but helpful for behavior consults.',
    faq3: 'Track weight weekly?',
    faq3a: 'Yes for growing kittens especially after adoption stress.',
  },
  {
    slug: 'new-pet-owner-vet-visit-question-list',
    title: 'New Pet Owner Vet Visit Question List: Records to Bring and Ask',
    excerpt:
      'First vet visit questions and documents for new pet parents so appointments are productive, not overwhelming.',
    category: 'petclues-guides',
    tags: ['vet visit questions', 'new pet owner', 'first vet visit'],
    cluster: 'new-pet-owner-guides',
    focus: 'new pet owner vet visit preparation',
    audience: 'Anyone attending their first pet wellness exam',
    keyDocuments: ['prior records', 'diet labels', 'parasite history', 'behavior notes'],
    faq1: 'What if I forget questions?',
    faq1a: 'Save a template in your pet app and review in the waiting room.',
    faq2: 'Should I record the visit?',
    faq2a: 'Notes or audio (if allowed) beat memory for follow-up tasks.',
    faq3: 'How soon book the next visit?',
    faq3a: 'Before leaving, with reminders set for boosters.',
  },
];

const EXOTIC_SEEDS: BlogSeed[] = [
  {
    slug: 'bearded-dragon-health-log-temperature-tracking',
    title: 'Bearded Dragon Health Log: Temperature, UVB, and Shed Tracking',
    excerpt:
      'Daily habitat logging for bearded dragons - basking temps, UVB changes, appetite, and shed quality in one timeline.',
    category: 'exotic-pets',
    tags: ['bearded dragon', 'reptile care', 'habitat logging'],
    cluster: 'exotic-pets',
    focus: 'bearded dragon health logging',
    audience: 'Bearded dragon keepers maintaining precise habitats',
    keyDocuments: ['temp gun readings', 'UVB bulb change dates', 'fecal exam results', 'calcium schedules'],
    faq1: 'How often log temperatures?',
    faq1a: 'Daily spot checks; weekly logged summaries for trends.',
    faq2: 'Should UVB replacement dates be tracked?',
    faq2a: 'Yes. Bulb age strongly affects calcium metabolism.',
    faq3: 'Do exotics vets need photos?',
    faq3a: 'Habitat photos plus trend logs speed exotic appointments.',
  },
  {
    slug: 'guinea-pig-wellness-weight-records-guide',
    title: 'Guinea Pig Wellness Records: Weight, Teeth, and Vitamin C Logs',
    excerpt:
      'Track guinea pig weights, dental issues, and vitamin C intake with records built for prey-species subtle illness.',
    category: 'exotic-pets',
    tags: ['guinea pig', 'small mammal', 'weight tracking'],
    cluster: 'exotic-pets',
    focus: 'guinea pig wellness record keeping',
    audience: 'Guinea pig parents catching illness early',
    keyDocuments: ['weekly weights', 'dental exam notes', 'vitamin C sources', 'CXR if ordered'],
    faq1: 'Why weekly weights matter?',
    faq1a: 'Guinea pigs hide illness; weight loss is an early red flag.',
    faq2: 'Should vegetables be logged?',
    faq2a: 'Note new foods and GI reactions.',
    faq3: 'How store exotic vet records?',
    faq3a: 'Species-specific profiles prevent confusing with cat/dog files.',
  },
  {
    slug: 'rabbit-vaccination-and-dental-records',
    title: 'Rabbit Vaccination and Dental Records: RHDV, Boosters, and Molar Checks',
    excerpt:
      'Document RHDV vaccines where available, dental floats, and GI stasis episodes for companion rabbits.',
    category: 'exotic-pets',
    tags: ['rabbit care', 'RHDV vaccine', 'rabbit dental'],
    cluster: 'exotic-pets',
    focus: 'rabbit vaccination and dental records',
    audience: 'Rabbit owners in regions with RHDV risk',
    keyDocuments: ['RHDV certificates', 'dental float notes', 'GI stasis protocols', 'hay diet logs'],
    faq1: 'Are rabbit vaccines required everywhere?',
    faq1a: 'Depends on region; document availability and boosters.',
    faq2: 'How often dental checks?',
    faq2a: 'Annual minimum; more if drooling or weight loss occurs.',
    faq3: 'Should stasis episodes be detailed?',
    faq3a: 'Yes. Triggers and treatment response guide future prevention.',
  },
  {
    slug: 'snake-shedding-feeding-health-journal',
    title: 'Snake Care Journal: Shed Cycles, Feeding Refusals, and Humidity Logs',
    excerpt:
      'Keep snake feeding, shed, and humidity records that exotic vets need when appetite drops.',
    category: 'exotic-pets',
    tags: ['snake care', 'reptile feeding', 'shed cycle'],
    cluster: 'exotic-pets',
    focus: 'snake shedding and feeding journals',
    audience: 'Snake keepers tracking cyclical husbandry',
    keyDocuments: ['feed dates and prey size', 'complete shed dates', 'humidity charts', 'mite treatments'],
    faq1: 'What if my snake refuses food?',
    faq1a: 'Log duration and pre-shed signs before calling your exotics vet.',
    faq2: 'How detail humidity?',
    faq2a: 'Daily highs/lows during shed cycles at minimum.',
    faq3: 'Should quarantine periods be recorded?',
    faq3a: 'Yes for new acquisitions introducing disease risk.',
  },
  {
    slug: 'ferret-vaccination-and-adrenal-health-records',
    title: 'Ferret Health Records: Distemper Vaccines, Adrenal Disease, and Insulinoma Notes',
    excerpt:
      'Organize ferret distemper boosters, adrenal symptoms, and glucose monitoring in species-specific records.',
    category: 'exotic-pets',
    tags: ['ferret care', 'ferret vaccines', 'adrenal disease'],
    cluster: 'exotic-pets',
    focus: 'ferret vaccination and disease records',
    audience: 'Ferret owners managing specialized vet care',
    keyDocuments: ['distemper certificates', 'adrenal imaging', 'insulinoma labs', 'deslorelin dates'],
    faq1: 'How often ferrets need distemper vaccines?',
    faq1a: 'Follow exotics vet protocol; boosters are typically annual.',
    faq2: 'Track hair loss patterns?',
    faq2a: 'Photo logs help adrenal monitoring.',
    faq3: 'Should glucose episodes be logged?',
    faq3a: 'Yes with symptoms and recovery time for insulinoma care.',
  },
  {
    slug: 'parrot-annual-avian-wellness-documentation',
    title: 'Parrot Annual Wellness Documentation: Weight, Bloodwork, and Behavior',
    excerpt:
      'Annual avian wellness records for parrots - weights, choanal cultures, and behavior shifts tied to pain or illness.',
    category: 'bird-care',
    tags: ['parrot care', 'avian wellness', 'bird vet'],
    cluster: 'exotic-pets',
    focus: 'parrot annual wellness documentation',
    audience: 'Parrot guardians scheduling yearly avian exams',
    keyDocuments: ['gram stains', 'choanal cultures', 'weight charts', 'diet conversion notes'],
    faq1: 'How often weigh parrots?',
    faq1a: 'Weekly at home; confirm at annual avian visits.',
    faq2: 'Should bloodwork be trended?',
    faq2a: 'Yes. Baselines help when birds hide illness.',
    faq3: 'Document household toxins exposure?',
    faq3a: 'Note Teflon use, candles, and heavy metal risks.',
  },
];

const LEGACY_SLUG_POOL = [
  'puppy-vaccination-schedule-2026',
  'organize-pet-medical-records-online',
  'pet-emergency-information-card-guide',
  'cat-vaccination-schedule-guide',
  'pet-medication-reminder-guide',
  'traveling-with-pets-health-documents-checklist',
];

const LEARN_SLUG_POOL = [
  'build-a-pet-health-record-timeline',
  'create-a-pet-passport-for-sitters',
  'daily-medication-log-for-chronic-pet-care',
  'build-a-pet-emergency-info-card',
  'puppy-vaccine-booster-tracker',
];

function assignRelated(slug: string, index: number, clusterSeeds: BlogSeed[]): string[] {
  const clusterSlugs = clusterSeeds.map((s) => s.slug);
  const rotated = [
    ...clusterSlugs.filter((s) => s !== slug).slice(index % clusterSlugs.length),
    ...clusterSlugs.filter((s) => s !== slug).slice(0, index % clusterSlugs.length),
  ];
  return [...rotated.slice(0, 2), ...LEGACY_SLUG_POOL.slice(index % 3, index % 3 + 2)];
}

function buildClusterConfigs(seeds: BlogSeed[]): ExpandedBlogConfig[] {
  return seeds.map((seed, index) =>
    makeConfig(seed, assignRelated(seed.slug, index, seeds), [
      LEARN_SLUG_POOL[index % LEARN_SLUG_POOL.length],
      LEARN_SLUG_POOL[(index + 2) % LEARN_SLUG_POOL.length],
    ]),
  );
}

export const EXPANDED_BLOG_CONFIGS: ExpandedBlogConfig[] = [
  ...buildClusterConfigs(VACCINATION_SEEDS),
  ...buildClusterConfigs(HEALTH_RECORDS_SEEDS),
  ...buildClusterConfigs(MEDICAL_HISTORY_SEEDS),
  ...buildClusterConfigs(PET_PASSPORT_SEEDS),
  ...buildClusterConfigs(PET_TRAVEL_SEEDS),
  ...buildClusterConfigs(MEDICATION_SEEDS),
  ...buildClusterConfigs(EMERGENCY_SEEDS),
  ...buildClusterConfigs(ORGANIZATION_SEEDS),
  ...buildClusterConfigs(BREED_SEEDS),
  ...buildClusterConfigs(SENIOR_SEEDS),
  ...buildClusterConfigs(NEW_PET_SEEDS),
  ...buildClusterConfigs(EXOTIC_SEEDS),
];

if (EXPANDED_BLOG_CONFIGS.length !== 74) {
  throw new Error(`Expected 74 expanded blog configs, got ${EXPANDED_BLOG_CONFIGS.length}`);
}

const slugSet = new Set(EXPANDED_BLOG_CONFIGS.map((c) => c.slug));
if (slugSet.size !== EXPANDED_BLOG_CONFIGS.length) {
  throw new Error('Duplicate slugs in expanded blog configs');
}
