/**
 * PetClues dominance blog  -  Engine 3: Symptom Triage (topics 61-90).
 * Seed data for article generation; medically accurate triage language.
 */

/** @typedef {{ phrase: string; slug: string }} DominanceInternalLink */
/** @typedef {{ symptoms: string[]; differentialDiagnoses: string[]; whenToGoToER: string[]; homeCare: string[] }} SymptomTriageFacts */
/** @typedef {{ num: number; slug: string; title: string; category: 'symptom-triage'; excerpt: string; tags: string[]; facts: SymptomTriageFacts; relatedSlugs: string[]; internalLinks: DominanceInternalLink[] }} Engine3CatalogEntry */

/** @type {Engine3CatalogEntry[]} */
export const ENGINE_3_CATALOG = [
  {
    num: 61,
    slug: 'dog-throwing-up-yellow-bile-morning',
    title: 'Why is My Dog Throwing Up Yellow Bile in the Morning?',
    category: 'symptom-triage',
    excerpt:
      'Bilious vomiting syndrome causes foamy yellow bile when the stomach sits empty overnight - usually manageable at home unless vomiting is frequent, bloody, or paired with lethargy.',
    tags: ['dog vomiting', 'bilious vomiting', 'yellow bile', 'empty stomach', 'gastritis', 'GI triage'],
    facts: {
      symptoms: [
        'Single episode of yellow or greenish foamy vomit, often before breakfast',
        'Otherwise normal appetite and energy after eating',
        'May occur on a predictable schedule (early morning)',
        'Occasional lip licking, mild nausea, or reduced interest in food until fed',
      ],
      differentialDiagnoses: [
        'Bilious vomiting syndrome (reflux on an empty stomach)',
        'Dietary indiscretion or abrupt food change',
        'Gastritis, pancreatitis, or intestinal parasites',
        'Foreign body obstruction or inflammatory bowel disease',
        'Liver disease, kidney disease, or endocrine disorders in chronic cases',
      ],
      whenToGoToER: [
        'Repeated vomiting more than twice in 24 hours or inability to keep water down',
        'Blood in vomit, black tarry stool, or severe abdominal pain',
        'Lethargy, collapse, bloated abdomen, or known toxin ingestion',
        'Puppy under 16 weeks with vomiting and diarrhea (parvovirus risk)',
      ],
      homeCare: [
        'Offer a small bedtime snack or split meals into 3-4 smaller feedings',
        'Withhold food 4-6 hours after a single mild episode, then reintroduce bland diet',
        'Ensure fresh water; avoid fatty treats and table scraps',
        'Track frequency and timing for your vet if episodes persist beyond 1-2 weeks',
      ],
    },
    relatedSlugs: [
      'dog-diarrhea-mucus-blood-fasting-emergency',
      'lethargic-puppy-parvovirus-warning-signs',
      'dog-feeding-schedule-walk-tracker',
      'pet-emergency-information-card-guide',
    ],
    internalLinks: [
      { phrase: 'pet emergency information card', slug: 'pet-emergency-information-card-guide' },
      { phrase: 'dog feeding schedule', slug: 'dog-feeding-schedule-walk-tracker' },
      { phrase: 'organize pet medical records', slug: 'organize-pet-medical-records-online' },
    ],
  },
  {
    num: 62,
    slug: 'cat-limping-front-leg-when-to-call-vet',
    title: 'Cat Limping on Front Leg: When to Wait and When to Call the Vet',
    category: 'symptom-triage',
    excerpt:
      'A mild front-limb lameness after a jump may resolve with rest, but non-weight-bearing limps, swelling, or open wounds need same-day veterinary assessment.',
    tags: ['cat limping', 'lameness', 'front leg injury', 'sprain', 'fracture', 'feline orthopedics'],
    facts: {
      symptoms: [
        'Favoring one front paw with shortened stride or toe-touching only',
        'Reluctance to jump, climb, or use scratching post',
        'Swelling, heat, or vocalization when the limb is touched',
        'Overgrown nails, pad wounds, or visible nail-bed bleeding',
      ],
      differentialDiagnoses: [
        'Soft-tissue sprain or muscle strain after landing awkwardly',
        'Nail-bed injury, pad laceration, or foreign body between toes',
        'Fracture, luxation, or tendon/ligament tear',
        'Arthritis flare in senior cats',
        'Cat bite abscess (often presents days after outdoor fight)',
      ],
      whenToGoToER: [
        'Non-weight-bearing on the limb for more than a few hours',
        'Obvious deformity, open fracture, or heavy bleeding',
        'Limb feels cold, blue, or pulseless (vascular compromise)',
        'Trauma from fall or vehicle strike regardless of apparent mildness',
      ],
      homeCare: [
        'Confine to a small quiet room with low-sided litter box',
        'Restrict jumping for 48-72 hours if mild and weight-bearing returns',
        'Do not give human NSAIDs (toxic to cats); avoid aspirin unless vet-directed',
        'Inspect paws and nails; photograph swelling to show your veterinarian',
      ],
    },
    relatedSlugs: [
      'cat-hiding-recognizing-pain',
      'arthritis-management-records-senior-dogs',
      'pain-management-log-for-recovering-pets',
      'cat-health-records-checklist',
    ],
    internalLinks: [
      { phrase: 'pain management log', slug: 'pain-management-log-for-recovering-pets' },
      { phrase: 'cat health records checklist', slug: 'cat-health-records-checklist' },
      { phrase: 'after-hours emergency vet sheet', slug: 'after-hours-emergency-vet-information-sheet' },
    ],
  },
  {
    num: 63,
    slug: 'dog-diarrhea-mucus-blood-fasting-emergency',
    title: 'Dog Diarrhea With Mucus or Blood: Fasting vs. Emergency Visit',
    category: 'symptom-triage',
    excerpt:
      'Mucus alone often signals colitis, but hematochezia, black stool, or vomiting with diarrhea crosses into emergency territory - especially in puppies and small breeds.',
    tags: ['dog diarrhea', 'bloody stool', 'colitis', 'hematochezia', 'GI emergency', 'fasting protocol'],
    facts: {
      symptoms: [
        'Loose to watery stool with jelly-like mucus coating',
        'Bright red blood (hematochezia) or dark tarry stool (melena)',
        'Urgency, straining, flatulence, or accidents in house-trained dogs',
        'Vomiting, reduced appetite, or mild lethargy in mild colitis',
      ],
      differentialDiagnoses: [
        'Stress colitis or dietary indiscretion',
        'Parasites (Giardia, hookworms), bacterial overgrowth',
        'Hemorrhagic gastroenteritis (HGE) in small breeds',
        'Pancreatitis, foreign body, or intussusception',
        'Parvovirus in unvaccinated puppies',
      ],
      whenToGoToER: [
        'Large volume of blood, black tarry stool, or collapse',
        'Repeated vomiting with diarrhea and inability to hold fluids',
        'Puppy under 6 months, toy breed, or known toxin/foreign body ingestion',
        'Pale gums, bloated painful abdomen, or fever above 103.5°F',
      ],
      homeCare: [
        'Adult dogs only: brief 12-hour food fast with free access to water if otherwise stable',
        'Reintroduce bland boiled chicken and rice in small portions after fasting window',
        'Submit fresh stool sample to vet for parasite panel if not improving in 24-48 hours',
        'Never fast puppies, diabetic dogs, or dogs on prescription diets without vet guidance',
      ],
    },
    relatedSlugs: [
      'dog-throwing-up-yellow-bile-morning',
      'lethargic-puppy-parvovirus-warning-signs',
      'puppy-vaccination-schedule-2026',
      'pet-poison-control-information-card-guide',
    ],
    internalLinks: [
      { phrase: 'puppy vaccination schedule', slug: 'puppy-vaccination-schedule-2026' },
      { phrase: 'pet poison control card', slug: 'pet-poison-control-information-card-guide' },
      { phrase: 'pet emergency information card', slug: 'pet-emergency-information-card-guide' },
    ],
  },
  {
    num: 64,
    slug: 'reverse-sneezing-dogs-choking-allergies',
    title: 'Reverse Sneezing in Dogs: Is It Choking or Just Allergies?',
    category: 'symptom-triage',
    excerpt:
      'Reverse sneezing is a harmless inspiratory spasm that sounds alarming but usually self-resolves in seconds - true choking involves cyanosis, pawing at the mouth, and collapse.',
    tags: ['reverse sneezing', 'dog allergies', 'respiratory', 'choking vs sneezing', 'brachycephalic', 'airway'],
    facts: {
      symptoms: [
        'Rapid noisy inward snorts with extended neck and flared nostrils',
        'Episode lasts 5-30 seconds then stops abruptly with normal breathing',
        'Often triggered by excitement, pulling on leash, pollen, or dust',
        'No persistent cough, fever, or thick nasal discharge during episode',
      ],
      differentialDiagnoses: [
        'Paroxysmal reverse sneezing (benign pharyngeal irritation)',
        'Allergic rhinitis or seasonal environmental allergies',
        'Nasal mites, foreign body, or collapsing trachea',
        'Upper respiratory infection or kennel cough',
        'True airway obstruction or laryngeal paralysis in seniors',
      ],
      whenToGoToER: [
        'Gums turn blue or gray, or dog collapses during episode',
        'Continuous gagging with visible object in mouth or throat',
        'Labored breathing between episodes or open-mouth breathing at rest',
        'Thick green nasal discharge with fever and lethargy',
      ],
      homeCare: [
        'Gently stroke throat or briefly cover nostrils to encourage swallowing',
        'Reduce leash pulling; use harness instead of collar',
        'Rinse paws and wipe face after outdoor exposure during allergy season',
        'Record a phone video for your vet if episodes become frequent or prolonged',
      ],
    },
    relatedSlugs: [
      'kennel-cough-symptoms-contagious-how-long',
      'french-bulldog-respiratory-health-tracking',
      'bordetella-vaccine-boarding-daycare-guide',
      'pet-allergy-tracker-symptoms-triggers-records',
    ],
    internalLinks: [
      { phrase: 'Bordetella vaccine guide', slug: 'bordetella-vaccine-boarding-daycare-guide' },
      { phrase: 'pet allergy symptom tracker', slug: 'pet-allergy-tracker-symptoms-triggers-records' },
      { phrase: 'French Bulldog respiratory tracking', slug: 'french-bulldog-respiratory-health-tracking' },
    ],
  },
  {
    num: 65,
    slug: 'cat-bad-breath-dental-disease-stages',
    title: "Why Does My Cat's Breath Smell So Bad? (Stages of Dental Disease)",
    category: 'symptom-triage',
    excerpt:
      'Halitosis in cats usually signals periodontal disease progressing from gingivitis to tooth-root abscess - early professional cleaning prevents pain, tooth loss, and systemic infection.',
    tags: ['cat bad breath', 'dental disease', 'periodontitis', 'gingivitis', 'feline oral health', 'halitosis'],
    facts: {
      symptoms: [
        'Persistent fishy or rotten odor despite no dietary change',
        'Red or bleeding gum line, tartar buildup, or drooling',
        'Dropping food, chewing on one side, or pawing at mouth',
        'Weight loss or hiding in advanced oral pain',
      ],
      differentialDiagnoses: [
        'Stage 1-2 gingivitis and early periodontitis',
        'Stage 3-4 periodontal disease with bone loss and mobile teeth',
        'Tooth resorption (FORL) - common and painful in cats',
        'Oral masses, stomatitis, or kidney disease (uremic breath)',
        'Foreign body wedged across hard palate',
      ],
      whenToGoToER: [
        'Facial swelling, eye bulging, or inability to close mouth (abscess)',
        'Not eating for 24+ hours with significant drooling',
        'Bleeding that will not stop or suspected jaw fracture after trauma',
        'Sudden foul breath with vomiting and severe lethargy',
      ],
      homeCare: [
        'Schedule veterinary oral exam; home brushing helps prevention, not cure of stage 3+ disease',
        'Use VOHC-approved dental treats only as adjunct, not replacement for cleaning',
        'Offer soft food temporarily if chewing appears painful until vet visit',
        'Photograph teeth and gums to document progression between visits',
      ],
    },
    relatedSlugs: [
      'dog-dental-care-schedule-cleanings-reminders',
      'pet-dental-records-cleaning-history-guide',
      'cat-drooling-excessively-nausea-poison',
      'cat-losing-weight-eating-hyperthyroidism',
    ],
    internalLinks: [
      { phrase: 'pet dental records guide', slug: 'pet-dental-records-cleaning-history-guide' },
      { phrase: 'dog dental care schedule', slug: 'dog-dental-care-schedule-cleanings-reminders' },
      { phrase: 'cat health records checklist', slug: 'cat-health-records-checklist' },
    ],
  },
  {
    num: 66,
    slug: 'dog-panting-heavily-at-night',
    title: 'Dog Panting Heavily at Night: Pain, Anxiety, or Heart Failure?',
    category: 'symptom-triage',
    excerpt:
      'Nocturnal panting without heat or exercise warrants a same-week vet visit - distinguish anxiety pacing from cardiogenic cough, restlessness from abdominal pain, and senior cognitive changes.',
    tags: ['dog panting', 'nocturnal restlessness', 'heart failure', 'anxiety', 'pain signs', 'Cushing disease'],
    facts: {
      symptoms: [
        'Heavy open-mouth breathing while resting in cool environment',
        'Pacing, inability to settle, or waking from sleep to pant',
        'Cough especially at night or after lying down (heart disease clue)',
        'Vocalization, trembling, or clingy behavior suggesting anxiety or pain',
      ],
      differentialDiagnoses: [
        'Generalized anxiety, noise phobia, or cognitive dysfunction syndrome',
        'Orthopedic pain, abdominal discomfort, or fever',
        'Congestive heart failure or laryngeal disease',
        "Cushing's disease, anemia, or respiratory infection",
        'Medication side effects (steroids, opioids)',
      ],
      whenToGoToER: [
        'Gums blue or gray, collapse, or extreme respiratory effort',
        'Distended abdomen with unproductive retching (GDV risk in deep-chested breeds)',
        'Known heart disease with sudden worsening cough or fainting',
        'Panting with temperature above 104°F or suspected heatstroke',
      ],
      homeCare: [
        'Note time of night, room temperature, and recent diet or medication changes',
        'Provide calm dark sleeping area; avoid late vigorous exercise',
        'Do not give human sedatives or pain meds without veterinary approval',
        'Film a 30-second video of breathing pattern for your veterinarian',
      ],
    },
    relatedSlugs: [
      'dog-drinking-too-much-water-cushings-diabetes-kidney',
      'dog-shaking-trembling-toxic-shock',
      'pain-management-log-for-recovering-pets',
      'chronic-condition-pet-record-system',
    ],
    internalLinks: [
      { phrase: 'chronic condition record system', slug: 'chronic-condition-pet-record-system' },
      { phrase: 'pain management log', slug: 'pain-management-log-for-recovering-pets' },
      { phrase: 'pet lab results tracking', slug: 'pet-lab-results-tracking-normal-ranges' },
    ],
  },
  {
    num: 67,
    slug: 'cat-not-drinking-water-kidney-failure',
    title: 'Cat Not Drinking Water: How to Prevent Kidney Failure',
    category: 'symptom-triage',
    excerpt:
      'Cats who drink little from bowls but eat wet food may be fine - sudden thirst changes, vomiting, or weight loss signal dehydration, CKD, or urinary obstruction needing urgent labs.',
    tags: ['cat dehydration', 'kidney disease', 'CKD', 'water intake', 'feline hydration', 'urinary health'],
    facts: {
      symptoms: [
        'Dry tacky gums, skin tenting, or sunken eyes',
        'Reduced urination or very concentrated dark urine',
        'Lethargy, poor coat, or constipation alongside low intake',
        'Paradoxically increased drinking later as CKD progresses',
      ],
      differentialDiagnoses: [
        'Preference for running water or moisture from wet food only',
        'Dental pain, nausea, or upper respiratory congestion reducing intake',
        'Chronic kidney disease (CKD) or hyperthyroidism',
        'Urethral obstruction in male cats (often stops eating and drinking)',
        'Fever, pancreatitis, or systemic infection',
      ],
      whenToGoToER: [
        'Male cat straining in litter box with no urine production',
        'Vomiting repeatedly and unable to keep fluids down',
        'Collapse, severe lethargy, or capillary refill time over 2 seconds',
        'Known kidney disease with sudden behavior change or anorexia',
      ],
      homeCare: [
        'Add water fountains, multiple stations, and flavor with tuna juice sparingly',
        'Transition toward wet food to increase moisture intake',
        'Monitor daily litter box clump size and weight on a kitchen scale',
        'Never force oral syringe fluids without vet instruction - aspiration risk',
      ],
    },
    relatedSlugs: [
      'cat-peeing-outside-litter-box-flutd',
      'cat-losing-weight-eating-hyperthyroidism',
      'pet-lab-results-tracking-normal-ranges',
      'chronic-condition-pet-record-system',
    ],
    internalLinks: [
      { phrase: 'pet lab results tracking', slug: 'pet-lab-results-tracking-normal-ranges' },
      { phrase: 'chronic condition records', slug: 'chronic-condition-pet-record-system' },
      { phrase: 'cat health records checklist', slug: 'cat-health-records-checklist' },
    ],
  },
  {
    num: 68,
    slug: 'kennel-cough-symptoms-contagious-how-long',
    title: 'Kennel Cough Symptoms: How Long is a Dog Contagious?',
    category: 'symptom-triage',
    excerpt:
      'Infectious tracheobronchitis spreads for 1-2 weeks after symptoms start - isolate from dog parks and boarding until cough resolves and your vet clears return to group settings.',
    tags: ['kennel cough', 'Bordetella', 'contagious period', 'dog cough', 'infectious tracheobronchitis', 'boarding'],
    facts: {
      symptoms: [
        'Honking dry cough worse with excitement or collar pressure',
        'Mild nasal discharge, sneezing, or low-grade fever',
        'Normal appetite with occasional cough-induced vomiting',
        'Symptoms peak days 3-5 and often improve within 1-3 weeks',
      ],
      differentialDiagnoses: [
        'Bordetella bronchiseptica complex (kennel cough)',
        'Canine influenza virus',
        'Collapsing trachea in toy breeds (non-infectious)',
        'Heartworm disease or congestive heart failure',
        'Pneumonia secondary to viral infection',
      ],
      whenToGoToER: [
        'Labored breathing, blue gums, or persistent fever above 103.5°F',
        'Lethargy, refusal to eat, or productive cough with green discharge',
        'Puppy under 16 weeks or immunocompromised dog with worsening signs',
        'Cough persisting beyond 3 weeks without improvement',
      ],
      homeCare: [
        'Isolate from other dogs for minimum 14 days after last cough',
        'Use harness instead of collar; keep environment humidified',
        'Offer easy-to-swallow meals; limit strenuous play',
        'Notify boarding facility and dog walkers to prevent spread',
      ],
    },
    relatedSlugs: [
      'reverse-sneezing-dogs-choking-allergies',
      'bordetella-vaccine-boarding-daycare-guide',
      'canine-influenza-vaccine-outbreak-prep',
      'pet-boarding-preparation-vaccination-records-health-forms',
    ],
    internalLinks: [
      { phrase: 'Bordetella boarding guide', slug: 'bordetella-vaccine-boarding-daycare-guide' },
      { phrase: 'canine influenza outbreak prep', slug: 'canine-influenza-vaccine-outbreak-prep' },
      { phrase: 'boarding vaccination records', slug: 'pet-boarding-preparation-vaccination-records-health-forms' },
    ],
  },
  {
    num: 69,
    slug: 'dog-dragging-back-legs-ivdd-emergency',
    title: 'Dog Dragging Back Legs (Paresis): Emergency Protocol for IVDD',
    category: 'symptom-triage',
    excerpt:
      'Sudden hind-limb weakness in dachshunds and other chondrodystrophic breeds is a neurosurgical emergency - strict crate rest and immediate referral can preserve deep pain sensation and walking.',
    tags: ['IVDD', 'hind limb paralysis', 'intervertebral disc disease', 'dachshund', 'neurologic emergency', 'paresis'],
    facts: {
      symptoms: [
        'Wobbly hind legs, crossing, or inability to stand',
        'Dragging nails on ground or knuckling on paws',
        'Crying when lifted, arched back, or neck pain in cervical IVDD',
        'Urinary incontinence or inability to voluntarily urinate',
      ],
      differentialDiagnoses: [
        'Hansen type I intervertebral disc herniation (IVDD)',
        'Fibrocartilaginous embolism (FCE stroke-like event)',
        'Spinal tumor, meningitis, or degenerative myelopathy',
        'Traumatic fracture or luxation',
        'Tick paralysis or botulism (regional, exposure-dependent)',
      ],
      whenToGoToER: [
        'Any sudden hind-limb paralysis or inability to walk - same day',
        'Loss of deep pain sensation (does not withdraw when toe is crushed)',
        'Progression from wobbly to fully paralyzed within hours',
        'Inability to urinate with full bladder or severe spinal pain',
      ],
      homeCare: [
        'Strict crate rest only - no stairs, jumping, or off-leash activity until cleared',
        'Carry with supported hind end using towel sling if movement required',
        'Do not give human NSAIDs; note exact time symptoms began for surgeon',
        'Express bladder only if trained by vet - improper technique risks rupture',
      ],
    },
    relatedSlugs: [
      'dachshund-back-health-mobility-tracking',
      'dog-panting-heavily-at-night',
      'pain-management-log-for-recovering-pets',
      'pet-surgery-history-documentation-guide',
    ],
    internalLinks: [
      { phrase: 'Dachshund back health tracking', slug: 'dachshund-back-health-mobility-tracking' },
      { phrase: 'surgery history documentation', slug: 'pet-surgery-history-documentation-guide' },
      { phrase: 'after-hours emergency vet sheet', slug: 'after-hours-emergency-vet-information-sheet' },
    ],
  },
  {
    num: 70,
    slug: 'dog-licking-paws-constantly-yeast-allergies',
    title: 'Why is My Dog Licking Their Paws Constantly? (Yeast vs. Allergies)',
    category: 'symptom-triage',
    excerpt:
      'Saliva-stained rusty paws often mean yeast dermatitis or atopic allergy - distinguish seasonal itch from food allergy, contact irritants, and painful interdigital cysts before treating at home.',
    tags: ['paw licking', 'yeast infection', 'atopic dermatitis', 'dog allergies', 'pododermatitis', 'itch'],
    facts: {
      symptoms: [
        'Persistent licking or chewing of one or more paws, often at night',
        'Brown-red staining between toes, greasy odor, or thickened skin',
        'Ear itching, recurrent ear infections, or seasonal flare pattern',
        'Limping if interdigital cyst or foreign body present',
      ],
      differentialDiagnoses: [
        'Atopic dermatitis (environmental allergies)',
        'Food-responsive dermatitis or contact allergy (grass, detergent)',
        'Malassezia (yeast) overgrowth secondary to moisture or allergy',
        'Demodex or sarcoptic mange',
        'Interdigital furunculosis, foreign body, or autoimmune pododermatitis',
      ],
      whenToGoToER: [
        'Sudden severe swelling of face or paws after new food or walk (anaphylaxis)',
        'Open bleeding wounds, maggot infestation, or limb hot and painful with fever',
        'Limping with pus-draining tract between toes',
        'Systemic signs: vomiting, collapse, or hives over entire body',
      ],
      homeCare: [
        'Rinse paws after walks; dry thoroughly between toes',
        'Use Elizabethan collar short-term to break lick cycle until vet exam',
        'Avoid OTC hydrocortisone long-term without diagnosis - can worsen yeast',
        'Track seasonality, diet changes, and floor cleaners in a symptom log',
      ],
    },
    relatedSlugs: [
      'pet-allergy-tracker-symptoms-triggers-records',
      'allergy-and-reaction-history-for-pets',
      'hot-spots-dogs-home-remedies-vet-treatments',
      'flea-tick-prevention-calendar-pets',
    ],
    internalLinks: [
      { phrase: 'pet allergy symptom tracker', slug: 'pet-allergy-tracker-symptoms-triggers-records' },
      { phrase: 'allergy and reaction history', slug: 'allergy-and-reaction-history-for-pets' },
      { phrase: 'flea and tick prevention calendar', slug: 'flea-tick-prevention-calendar-pets' },
    ],
  },
  {
    num: 71,
    slug: 'cat-peeing-outside-litter-box-flutd',
    title: 'Cat Peeing Outside the Litter Box: Behavioral vs. Medical (FLUTD)',
    category: 'symptom-triage',
    excerpt:
      'Urinating outside the box is a medical red flag until proven otherwise - straining, blood, or small frequent puddles suggest FLUTD or urethral obstruction, not spite.',
    tags: ['inappropriate urination', 'FLUTD', 'UTI cats', 'litter box', 'urinary blockage', 'feline stress'],
    facts: {
      symptoms: [
        'Urinating on soft surfaces (bed, laundry) or near box',
        'Frequent trips with little output, crying in box, or blood in urine',
        'Overgrooming genital area or excessive licking after urination',
        'Sudden change after new pet, move, or litter brand switch',
      ],
      differentialDiagnoses: [
        'Feline lower urinary tract disease (idiopathic cystitis)',
        'Urethral obstruction in male cats (emergency)',
        'Urinary tract infection, bladder stones, or crystals',
        'Arthritis making box entry painful',
        'Behavioral marking vs. medical pollakiuria',
      ],
      whenToGoToER: [
        'Male cat visiting litter box repeatedly with no urine or only drops',
        'Vomiting, lethargy, or painful abdomen with urinary signs',
        'Complete inability to urinate for 6+ hours',
        'Collapse or extreme vocalization when attempting to urinate',
      ],
      homeCare: [
        'Add extra boxes (one per cat plus one) with low entry and unscented litter',
        'Increase water intake via fountains and wet food',
        'Do not punish - stress worsens idiopathic cystitis',
        'Collect urine sample at vet visit; note blood, odor, and frequency on calendar',
      ],
    },
    relatedSlugs: [
      'cat-not-drinking-water-kidney-failure',
      'feline-asthma-cough-vs-hairball',
      'cat-health-records-checklist',
      'first-30-days-new-cat-owner-records-guide',
    ],
    internalLinks: [
      { phrase: 'new cat owner records guide', slug: 'first-30-days-new-cat-owner-records-guide' },
      { phrase: 'cat health records checklist', slug: 'cat-health-records-checklist' },
      { phrase: 'chronic condition record system', slug: 'chronic-condition-pet-record-system' },
    ],
  },
  {
    num: 72,
    slug: 'how-to-tell-if-dog-has-fever-without-thermometer',
    title: 'How to Tell if Your Dog is Running a Fever (Without a Thermometer)',
    category: 'symptom-triage',
    excerpt:
      'Warm ears and dry nose are unreliable - watch for shivering, lethargy, and reduced appetite; rectal temperature above 103°F confirms fever and warrants vet workup same day.',
    tags: ['dog fever', 'hyperthermia', 'temperature check', 'infection signs', 'pyrexia', 'home triage'],
    facts: {
      symptoms: [
        'Lethargy, reluctance to walk or play',
        'Shivering or panting in cool room without exercise',
        'Warm ears and paw pads with reduced appetite',
        'Nasal discharge, cough, or vomiting accompanying systemic illness',
      ],
      differentialDiagnoses: [
        'Viral or bacterial infection (respiratory, urinary, tick-borne)',
        'Post-vaccination mild fever within 24 hours',
        'Abscess, bite wound, or dental infection',
        'Immune-mediated disease or neoplasia in chronic cases',
        'Heatstroke (hyperthermia - not true fever) - environmental cause',
      ],
      whenToGoToER: [
        'Temperature at or above 104°F, or unknown with collapse',
        'Suspected heatstroke: heavy panting, vomiting, ataxia after heat exposure',
        'Fever with pale gums, bruising, or known toxin ingestion',
        'Puppy under 6 months with fever and diarrhea',
      ],
      homeCare: [
        'Offer fresh water; encourage rest in cool ventilated area',
        'Use pet rectal thermometer with lubricant for accurate reading if available',
        'Do not give ibuprofen, acetaminophen, or aspirin without vet dosing',
        'Document onset, vaccines in past 48 hours, and tick exposure',
      ],
    },
    relatedSlugs: [
      'pale-gums-dogs-capillary-refill-time',
      'tick-on-dog-removal-symptoms-to-track',
      'lethargic-puppy-parvovirus-warning-signs',
      'pet-first-aid-kit-records-checklist',
    ],
    internalLinks: [
      { phrase: 'pet first-aid kit checklist', slug: 'pet-first-aid-kit-records-checklist' },
      { phrase: 'pet emergency information card', slug: 'pet-emergency-information-card-guide' },
      { phrase: 'vaccine reaction documentation', slug: 'vaccine-reaction-documentation-for-vets' },
    ],
  },
  {
    num: 73,
    slug: 'lethargic-puppy-parvovirus-warning-signs',
    title: 'Lethargic Puppy: When Is Sleepiness Actually Parvovirus?',
    category: 'symptom-triage',
    excerpt:
      'A sleepy puppy after play is normal - a floppy, uninterested puppy who vomits or has bloody diarrhea needs immediate parvovirus testing; mortality drops sharply with early hospitalization.',
    tags: ['lethargic puppy', 'parvovirus', 'puppy emergency', 'bloody diarrhea', 'CPV', 'unvaccinated puppy'],
    facts: {
      symptoms: [
        'Profound lethargy out of proportion to mild illness',
        'Vomiting, anorexia, and foul-smelling diarrhea',
        'Bloody or mucoid stool with rapid dehydration',
        'Fever or hypothermia, weak suckle reflex in very young pups',
      ],
      differentialDiagnoses: [
        'Canine parvovirus type 2 (CPV-2)',
        'Intestinal parasites or coronavirus (usually milder)',
        'Hypoglycemia in toy breeds',
        'Foreign body obstruction',
        'Septicemia from umbilical infection in neonates',
      ],
      whenToGoToER: [
        'Any vomiting and diarrhea in unvaccinated or partially vaccinated puppy - immediate',
        'Collapse, gray gums, or skin tenting suggesting shock',
        'Puppy not nursing or standing for more than a few hours (neonate)',
        'Known exposure to parvovirus-positive environment within incubation window',
      ],
      homeCare: [
        'Do not attempt home treatment - parvovirus requires IV fluids and isolation',
        'Prevent contact with other dogs and contaminated yards until cleared',
        'Bring vaccination records and exposure timeline to emergency clinic',
        'Disinfect with diluted bleach (1:32) on hard surfaces after recovery',
      ],
    },
    relatedSlugs: [
      'puppy-vaccination-schedule-2026',
      'new-puppy-checklist-health-records-vaccines',
      'dog-diarrhea-mucus-blood-fasting-emergency',
      'dog-throwing-up-yellow-bile-morning',
    ],
    internalLinks: [
      { phrase: 'puppy vaccination schedule 2026', slug: 'puppy-vaccination-schedule-2026' },
      { phrase: 'new puppy health checklist', slug: 'new-puppy-checklist-health-records-vaccines' },
      { phrase: 'pet emergency information card', slug: 'pet-emergency-information-card-guide' },
    ],
  },
  {
    num: 74,
    slug: 'dog-cloudy-eyes-nuclear-sclerosis-vs-cataracts',
    title: "Why Are My Dog's Eyes Cloudy? Nuclear Sclerosis vs. Cataracts",
    category: 'symptom-triage',
    excerpt:
      'Lenticular sclerosis causes harmless blue-gray haze in seniors with preserved vision - white opaque cataracts block light and may need surgery if they impair navigation or trigger glaucoma.',
    tags: ['cloudy eyes', 'nuclear sclerosis', 'cataracts', 'senior dog vision', 'lenticular sclerosis', 'ophthalmology'],
    facts: {
      symptoms: [
        'Bilateral blue-gray haziness in dogs over 7 years (nuclear sclerosis)',
        'White dense opacity blocking view of lens nucleus (cataract)',
        'Bumping into furniture, hesitation on stairs, or night blindness',
        'Red painful eye with squinting suggests glaucoma or uveitis - not simple aging',
      ],
      differentialDiagnoses: [
        'Age-related nuclear (lenticular) sclerosis - benign',
        'Immature, mature, or hypermature cataracts',
        'Diabetic cataracts (rapid onset in dogs)',
        'Glaucoma, corneal edema, or keratitis',
        'Nuclear sclerosis plus unrelated retinal disease',
      ],
      whenToGoToER: [
        'Sudden vision loss, bulging eye, or severe squinting with tearing',
        'Cloudiness after trauma or chemical splash',
        'Eye appears larger than normal with dilated pupil (acute glaucoma)',
        'Diabetic dog with rapid bilateral white lens changes and systemic illness',
      ],
      homeCare: [
        'Keep furniture layout stable; use night-lights for senior dogs',
        'Schedule veterinary ophthalmology referral for cataract assessment',
        'Do not use human eye drops unless prescribed',
        'Photograph eyes in daylight to track opacity progression',
      ],
    },
    relatedSlugs: [
      'dog-drinking-too-much-water-cushings-diabetes-kidney',
      'arthritis-management-records-senior-dogs',
      'chronic-condition-pet-record-system',
      'pet-imaging-reports-mri-xray-storage',
    ],
    internalLinks: [
      { phrase: 'senior dog arthritis records', slug: 'arthritis-management-records-senior-dogs' },
      { phrase: 'pet imaging report storage', slug: 'pet-imaging-reports-mri-xray-storage' },
      { phrase: 'chronic condition records', slug: 'chronic-condition-pet-record-system' },
    ],
  },
  {
    num: 75,
    slug: 'cat-vomiting-hairballs-gi-blockage',
    title: 'Cat Vomiting Hairballs Frequently: When Is It Actually a GI Blockage?',
    category: 'symptom-triage',
    excerpt:
      'Hairballs should be occasional - weekly vomiting, weight loss, or tubular bile vomit without hair suggests foreign body, inflammatory bowel disease, or metabolic illness needing imaging.',
    tags: ['cat hairballs', 'vomiting cat', 'foreign body', 'GI obstruction', 'trichobezoar', 'IBD'],
    facts: {
      symptoms: [
        'Productive gag producing cylindrical hair mass every few weeks (normal range)',
        'Vomiting more than once weekly or containing no hair',
        'Reduced appetite, weight loss, or lethargy between episodes',
        'Constipation, small hard stools, or abdominal tension',
      ],
      differentialDiagnoses: [
        'Routine trichobezoar (hairball) in long-haired cats',
        'Over-grooming from stress, allergy, or external parasites',
        'Linear foreign body (string, tinsel) - high risk in cats',
        'Inflammatory bowel disease or food intolerance',
        'Hyperthyroidism, kidney disease, or pancreatitis',
      ],
      whenToGoToER: [
        'Repeated vomiting with no hair production and hunched posture',
        'Known ingestion of string, rubber bands, or tinsel',
        'Vomiting bile or blood, or abdomen painful to touch',
        'Not eating for 24+ hours with vomiting',
      ],
      homeCare: [
        'Brush daily; consider hairball diet or vet-approved lubricant gel',
        'Provide enrichment to reduce stress grooming',
        'Never pull string visible from mouth or rectum - can saw intestines',
        'Track vomit contents (hair vs. bile vs. food) with dates for vet',
      ],
    },
    relatedSlugs: [
      'cat-bad-breath-dental-disease-stages',
      'cat-losing-weight-eating-hyperthyroidism',
      'feline-asthma-cough-vs-hairball',
      'cat-drooling-excessively-nausea-poison',
    ],
    internalLinks: [
      { phrase: 'cat health records checklist', slug: 'cat-health-records-checklist' },
      { phrase: 'pet poison control card', slug: 'pet-poison-control-information-card-guide' },
      { phrase: 'building a medical history timeline', slug: 'building-complete-pet-medical-history-timeline' },
    ],
  },
  {
    num: 76,
    slug: 'dog-scooting-carpet-anal-glands-parasites',
    title: 'Dog Scooting on the Carpet: Anal Glands vs. Parasites',
    category: 'symptom-triage',
    excerpt:
      'Scooting usually means full or infected anal sacs, but tapeworm segments and perianal dermatitis mimic the urge - expressing glands at home risks abscess if done incorrectly.',
    tags: ['dog scooting', 'anal glands', 'tapeworms', 'perianal itch', 'anal sac disease', 'parasites'],
    facts: {
      symptoms: [
        'Dragging rear on ground or excessive licking under tail',
        'Fishy odor from rear, brown staining on bedding',
        'Rice-grain segments near anus or in stool (tapeworm)',
        'Swelling beside anus, bleeding, or pain when sitting',
      ],
      differentialDiagnoses: [
        'Anal sac impaction or abscess',
        'Tapeworm infection (Dipylidium caninum)',
        'Perianal fistula (German Shepherds predisposed)',
        'Food allergy or flea allergy dermatitis',
        'Tumor or perianal adenoma in older intact males',
      ],
      whenToGoToER: [
        'Large painful swelling beside anus with fever',
        'Profuse bleeding or open draining tract',
        'Inability to defecate with straining and vomiting',
        'Sudden scooting with known foreign body ingestion',
      ],
      homeCare: [
        'Schedule vet anal sac check - do not repeat DIY expression',
        'Maintain consistent flea control to reduce tapeworm risk',
        'Increase dietary fiber (pumpkin, fiber supplement) if vet approves',
        'Photograph stool and perianal area if worms suspected',
      ],
    },
    relatedSlugs: [
      'dog-licking-paws-constantly-yeast-allergies',
      'flea-tick-prevention-calendar-pets',
      'dog-diarrhea-mucus-blood-fasting-emergency',
      'pet-allergy-tracker-symptoms-triggers-records',
    ],
    internalLinks: [
      { phrase: 'flea and tick prevention calendar', slug: 'flea-tick-prevention-calendar-pets' },
      { phrase: 'pet allergy tracker', slug: 'pet-allergy-tracker-symptoms-triggers-records' },
      { phrase: 'dog feeding schedule', slug: 'dog-feeding-schedule-walk-tracker' },
    ],
  },
  {
    num: 77,
    slug: 'swollen-dog-ear-aural-hematoma',
    title: 'Swollen Dog Ear (Aural Hematoma): Causes and Surgical Fixes',
    category: 'symptom-triage',
    excerpt:
      'A pillowy ear flap filled with blood usually follows head shaking from otitis - aural hematomas rarely resolve alone and often recur without treating underlying ear infection plus drainage.',
    tags: ['aural hematoma', 'swollen ear flap', 'otitis externa', 'ear infection', 'dog ears', 'head shaking'],
    facts: {
      symptoms: [
        'Fluid-filled swelling on inner pinna feeling like water balloon',
        'Head tilt, ear scratching, odor, or discharge from canal',
        'Pain when ear is touched; reluctance to have head handled',
        'Cauliflower ear deformity if chronic or untreated',
      ],
      differentialDiagnoses: [
        'Traumatic aural hematoma from otitis-induced shaking',
        'Otitis externa (yeast, bacteria, or mites)',
        'Allergic otitis or foreign body in canal',
        'Ear margin vasculitis or insect bite swelling (localized)',
        'Tumor of pinna or canal (less common)',
      ],
      whenToGoToER: [
        'Ear swelling with collapse, facial nerve paralysis, or balance loss',
        'Profuse bleeding from canal or ruptured hematoma',
        'Severe pain preventing sleep or eating',
        'Suspected snake bite or trauma to head and ear',
      ],
      homeCare: [
        'Prevent scratching with E-collar until veterinary appointment',
        'Do not lance or drain at home - infection and cartilage damage risk',
        'Keep ear dry; no swimming until cleared',
        'Note allergy season, bathing frequency, and prior ear infections',
      ],
    },
    relatedSlugs: [
      'dog-licking-paws-constantly-yeast-allergies',
      'pet-allergy-tracker-symptoms-triggers-records',
      'pain-management-log-for-recovering-pets',
      'pet-surgery-history-documentation-guide',
    ],
    internalLinks: [
      { phrase: 'surgery history documentation', slug: 'pet-surgery-history-documentation-guide' },
      { phrase: 'pain management log', slug: 'pain-management-log-for-recovering-pets' },
      { phrase: 'allergy and reaction history', slug: 'allergy-and-reaction-history-for-pets' },
    ],
  },
  {
    num: 78,
    slug: 'pale-gums-dogs-capillary-refill-time',
    title: 'Pale Gums in Dogs: How to Check Capillary Refill Time in an Emergency',
    category: 'symptom-triage',
    excerpt:
      'Lift the lip: pink gums with refill under 2 seconds are normal - white, gray, or brick-red gums with delayed refill signal shock, anemia, or heatstroke and need emergency transport.',
    tags: ['pale gums', 'capillary refill time', 'CRT', 'shock', 'anemia', 'emergency triage'],
    facts: {
      symptoms: [
        'Gums pale white, gray, or bluish instead of salmon pink',
        'Capillary refill time greater than 2 seconds after pressing gum',
        'Brick-red gums with heat exposure (hyperthermia)',
        'Weak pulse, cold extremities, or collapse accompanying gum changes',
      ],
      differentialDiagnoses: [
        'Hypovolemic shock from bleeding or dehydration',
        'Anemia from immune-mediated hemolytic anemia (IMHA)',
        'Heatstroke or severe infection (sepsis)',
        'Heart failure with poor perfusion',
        'Internal bleeding from splenic mass rupture or rodenticide toxicity',
      ],
      whenToGoToER: [
        'Any pale, white, blue, or gray gums - transport immediately',
        'CRT over 3 seconds, collapse, or uncontrolled bleeding',
        'Known ingestion of anticoagulant rodent poison',
        'Trauma with gum color change even if external wounds seem minor',
      ],
      homeCare: [
        'Check gums on healthy dog now to learn your baseline color',
        'Press gum above canine tooth; count seconds until pink returns',
        'Keep dog calm and warm during transport; call clinic en route',
        'Do not offer food or water if vomiting or altered mental status',
      ],
    },
    relatedSlugs: [
      'how-to-tell-if-dog-has-fever-without-thermometer',
      'dog-shaking-trembling-toxic-shock',
      'pet-poison-control-information-card-guide',
      'after-hours-emergency-vet-information-sheet',
    ],
    internalLinks: [
      { phrase: 'after-hours emergency vet sheet', slug: 'after-hours-emergency-vet-information-sheet' },
      { phrase: 'pet poison control card', slug: 'pet-poison-control-information-card-guide' },
      { phrase: 'pet first-aid kit checklist', slug: 'pet-first-aid-kit-records-checklist' },
    ],
  },
  {
    num: 79,
    slug: 'feline-asthma-cough-vs-hairball',
    title: 'Feline Asthma: Recognizing a Cough vs. a Hairball Hack',
    category: 'symptom-triage',
    excerpt:
      'Asthma cough is dry, neck-extended, and produces no hair - episodes may worsen at night or with litter dust; untreated bronchoconstriction can progress to respiratory crisis.',
    tags: ['feline asthma', 'cat cough', 'hairball vs cough', 'bronchitis', 'respiratory disease', 'allergic airway'],
    facts: {
      symptoms: [
        'Crouched posture with neck extended, little or no product brought up',
        'Wheezing audible or rapid shallow breathing between episodes',
        'Cough triggered by perfume, smoke, dusty litter, or stress',
        'Hairball hack produces cylindrical hair after gagging',
      ],
      differentialDiagnoses: [
        'Feline asthma (allergic bronchitis)',
        'Chronic bronchitis or parasitic lung disease',
        'Heartworm-associated respiratory disease (HWAARD)',
        'Pneumonia or pleural effusion',
        'Trichobezoar (hairball) vs. lower airway disease coexistence',
      ],
      whenToGoToER: [
        'Open-mouth breathing or blue gums at rest',
        'Respiratory rate over 40 breaths per minute while sleeping',
        'Collapse after coughing episode',
        'Cough with fever, nasal discharge, and lethargy',
      ],
      homeCare: [
        'Switch to low-dust litter; eliminate smoke and aerosol sprays',
        'Use HEPA air purifier in primary living area',
        'Film coughing episodes for veterinarian - audio helps diagnosis',
        'Never use human inhalers without feline AeroKat spacer prescription',
      ],
    },
    relatedSlugs: [
      'cat-vomiting-hairballs-gi-blockage',
      'reverse-sneezing-dogs-choking-allergies',
      'cat-hiding-recognizing-pain',
      'pet-allergy-tracker-symptoms-triggers-records',
    ],
    internalLinks: [
      { phrase: 'pet allergy symptom tracker', slug: 'pet-allergy-tracker-symptoms-triggers-records' },
      { phrase: 'cat health records checklist', slug: 'cat-health-records-checklist' },
      { phrase: 'chronic condition record system', slug: 'chronic-condition-pet-record-system' },
    ],
  },
  {
    num: 80,
    slug: 'dog-drinking-too-much-water-cushings-diabetes-kidney',
    title: "Why is My Dog Drinking So Much Water? (Cushing's, Diabetes, Kidney)",
    category: 'symptom-triage',
    excerpt:
      'Polydipsia plus accidents in a previously house-trained dog usually means metabolic disease - baseline bloodwork and urinalysis differentiate Cushing\'s, diabetes mellitus, and chronic kidney disease.',
    tags: ['polydipsia', 'excessive drinking', 'Cushing disease', 'diabetes dogs', 'kidney disease', 'PU/PD'],
    facts: {
      symptoms: [
        'Water bowl emptying faster than usual; seeking puddles or toilets',
        'Increased urination volume or accidents indoors',
        'Weight change, pot belly, or muscle loss (Cushing\'s pattern)',
        'Cloudy eyes, ravenous appetite with weight loss (diabetes clue)',
      ],
      differentialDiagnoses: [
        "Hyperadrenocorticism (Cushing's disease)",
        'Diabetes mellitus',
        'Chronic kidney disease or pyometra in intact females',
        'Hypercalcemia, liver disease, or hypothyroidism',
        'Psychogenic polydipsia after diet change (diagnosis of exclusion)',
      ],
      whenToGoToER: [
        'Vomiting with extreme thirst and lethargy (diabetic ketoacidosis risk)',
        'Distended abdomen with unproductive vomiting in intact female',
        'Collapse, seizures, or severe weakness',
        'Not urinating despite heavy drinking (obstruction)',
      ],
      homeCare: [
        'Measure 24-hour water intake (normal ~1 oz per lb body weight/day)',
        'Do not restrict water before vet appointment',
        'Collect first-morning urine sample if possible',
        'List medications (steroids cause polydipsia) and recent bloodwork',
      ],
    },
    relatedSlugs: [
      'dog-panting-heavily-at-night',
      'dog-cloudy-eyes-nuclear-sclerosis-vs-cataracts',
      'pet-lab-results-tracking-normal-ranges',
      'chronic-condition-pet-record-system',
    ],
    internalLinks: [
      { phrase: 'pet lab results tracking', slug: 'pet-lab-results-tracking-normal-ranges' },
      { phrase: 'chronic condition records', slug: 'chronic-condition-pet-record-system' },
      { phrase: 'dog weight tracker', slug: 'dog-weight-tracker-log-trends-vet-health' },
    ],
  },
  {
    num: 81,
    slug: 'cat-losing-weight-eating-hyperthyroidism',
    title: 'Cat Losing Weight but Eating Constantly: Hyperthyroidism Explained',
    category: 'symptom-triage',
    excerpt:
      'Middle-aged and senior cats with ravenous appetite and weight loss often have hyperthyroidism - untreated disease strains heart and kidneys; a simple T4 test confirms diagnosis.',
    tags: ['hyperthyroidism', 'weight loss cat', 'polyphagia', 'senior cat', 'thyroid disease', 'T4 test'],
    facts: {
      symptoms: [
        'Visible rib and spine prominence despite increased food intake',
        'Hyperactivity, yowling, or poor coat quality',
        'Vomiting, diarrhea, or increased thirst secondary to disease',
        'Rapid heart rate or murmur on home resting check',
      ],
      differentialDiagnoses: [
        'Primary hyperthyroidism (adenoma of thyroid)',
        'Diabetes mellitus with weight loss',
        'Chronic kidney disease with poor body condition',
        'Intestinal malabsorption or exocrine pancreatic insufficiency',
        'Neoplasia or severe dental disease limiting intake (apparent polyphagia)',
      ],
      whenToGoToER: [
        'Collapse, open-mouth breathing, or heart rate sustained above 240 at rest',
        'Not eating for 24+ hours after being on methimazole (thyroid crisis risk)',
        'Severe vomiting and weakness with known hyperthyroidism',
        'Sudden hind-limb weakness (thromboembolism risk)',
      ],
      homeCare: [
        'Weigh cat weekly on same scale; graph trend for veterinarian',
        'Do not restrict calories without diagnosis - metabolic demand is high',
        'Schedule senior blood panel including total T4',
        'Note behavior changes, vomiting frequency, and water intake',
      ],
    },
    relatedSlugs: [
      'cat-not-drinking-water-kidney-failure',
      'cat-bad-breath-dental-disease-stages',
      'pet-lab-results-tracking-normal-ranges',
      'chronic-condition-pet-record-system',
    ],
    internalLinks: [
      { phrase: 'pet lab results tracking', slug: 'pet-lab-results-tracking-normal-ranges' },
      { phrase: 'chronic condition records', slug: 'chronic-condition-pet-record-system' },
      { phrase: 'cat health records checklist', slug: 'cat-health-records-checklist' },
    ],
  },
  {
    num: 82,
    slug: 'dog-seizures-first-3-minutes-protocol',
    title: 'Dog Seizures: What to Do (And Record) During the First 3 Minutes',
    category: 'symptom-triage',
    excerpt:
      'During a seizure: time the episode, cushion the head, and do not put hands near the mouth - cluster seizures or status epilepticus beyond 5 minutes require emergency benzodiazepine protocol.',
    tags: ['dog seizures', 'epilepsy', 'status epilepticus', 'first aid', 'neurologic emergency', 'cluster seizures'],
    facts: {
      symptoms: [
        'Sudden collapse with paddling, jaw chomping, drooling, or urination',
        'Loss of consciousness with stiff limbs then rhythmic twitching',
        'Post-ictal confusion, blindness, or pacing for minutes to hours',
        'Focal seizures: fly-biting, facial twitching, or one limb jerking',
      ],
      differentialDiagnoses: [
        'Idiopathic epilepsy (age 1-5 common onset)',
        'Toxin ingestion (chocolate, xylitol, bromethalin)',
        'Hypoglycemia, liver shunt, or electrolyte imbalance',
        'Brain tumor or infectious encephalitis in older dogs',
        'Syncope mistaken for seizure (shorter, no post-ictal phase)',
      ],
      whenToGoToER: [
        'Seizure lasting longer than 5 minutes or three seizures in 24 hours',
        'First-ever seizure in dog over 5 years or under 6 months',
        'Seizure with known toxin access or trauma',
        'Prolonged post-ictal blindness, fever, or not returning to normal within 2 hours',
      ],
      homeCare: [
        'Start timer; dim lights and reduce noise during episode',
        'Slide pillow under head; clear stairs and furniture',
        'Video record duration and body involvement for neurologist',
        'After episode: note last meal, medications, and possible triggers',
      ],
    },
    relatedSlugs: [
      'dog-shaking-trembling-toxic-shock',
      'pet-poison-control-information-card-guide',
      'pain-management-log-for-recovering-pets',
      'chronic-condition-pet-record-system',
    ],
    internalLinks: [
      { phrase: 'pet poison control card', slug: 'pet-poison-control-information-card-guide' },
      { phrase: 'chronic condition records', slug: 'chronic-condition-pet-record-system' },
      { phrase: 'pet emergency information card', slug: 'pet-emergency-information-card-guide' },
    ],
  },
  {
    num: 83,
    slug: 'hot-spots-dogs-home-remedies-vet-treatments',
    title: 'Hot Spots on Dogs: Overnight Home Remedies and Vet Treatments',
    category: 'symptom-triage',
    excerpt:
      'Acute moist dermatitis spreads in hours from licking one itchy spot - clip hair, keep dry, and see vet for antibiotics and underlying allergy workup; E-collar prevents overnight expansion.',
    tags: ['hot spots', 'acute moist dermatitis', 'pyotraumatic dermatitis', 'skin infection', 'dog itching', 'E-collar'],
    facts: {
      symptoms: [
        'Sudden red oozing lesion with matted hair and foul odor',
        'Intense licking or scratching at one area (often cheek or hip)',
        'Moist exudate that crusts overnight',
        'Pain when touched; may start after swimming or bath',
      ],
      differentialDiagnoses: [
        'Pyotraumatic dermatitis (hot spot) secondary to self-trauma',
        'Flea allergy dermatitis or atopic flare',
        'Ear infection with referred scratching to face',
        'Anal sac irritation causing hip hot spots',
        'Demodex or ringworm mimicking moist lesion',
      ],
      whenToGoToER: [
        'Facial swelling, hives, or difficulty breathing (anaphylaxis)',
        'Lesion doubling in size overnight with fever and lethargy',
        'Hot spot near eye with squinting or vision change',
        'Immunocompromised dog with rapidly spreading skin infection',
      ],
      homeCare: [
        'Trim hair around lesion; clean gently with chlorhexidine if vet-approved',
        'Apply E-collar immediately to stop lick cycle',
        'Keep dry - no swimming until healed',
        'Start flea prevention if lapse may have triggered itch',
      ],
    },
    relatedSlugs: [
      'dog-licking-paws-constantly-yeast-allergies',
      'flea-tick-prevention-calendar-pets',
      'pet-allergy-tracker-symptoms-triggers-records',
      'swollen-dog-ear-aural-hematoma',
    ],
    internalLinks: [
      { phrase: 'flea and tick prevention', slug: 'flea-tick-prevention-calendar-pets' },
      { phrase: 'pet allergy tracker', slug: 'pet-allergy-tracker-symptoms-triggers-records' },
      { phrase: 'allergy and reaction history', slug: 'allergy-and-reaction-history-for-pets' },
    ],
  },
  {
    num: 84,
    slug: 'cat-hiding-recognizing-pain',
    title: 'Why is My Cat Hiding? Recognizing Pain in Felines',
    category: 'symptom-triage',
    excerpt:
      'Cats hide illness until late - withdrawal from family, reduced grooming, and altered gait often mean pain from dental disease, arthritis, or abdominal crisis, not mere mood change.',
    tags: ['cat hiding', 'feline pain', 'sick cat behavior', 'illness signs', 'stoic cat', 'pain recognition'],
    facts: {
      symptoms: [
        'Retreat to closet, under bed, or high perch away from activity',
        'Decreased social interaction or aggression when approached',
        'Poor coat, hunched posture, or reluctance to jump',
        'Changes in litter box habits or appetite without obvious cause',
      ],
      differentialDiagnoses: [
        'Osteoarthritis or soft-tissue injury',
        'Dental pain or oral disease',
        'Urinary obstruction, pancreatitis, or GI pain',
        'Stress from environmental change (less common alone)',
        'Systemic illness: kidney disease, hyperthyroidism, neoplasia',
      ],
      whenToGoToER: [
        'Male cat hiding with straining to urinate',
        'Hiding plus open-mouth breathing or pale gums',
        'Not eating for 24+ hours in overweight cat (hepatic lipidosis risk)',
        'Sudden paralysis, vocalization, or collapse',
      ],
      homeCare: [
        'Place food, water, and low-sided litter near hiding spot temporarily',
        'Use Feline Grimace Scale photos to document pain signs for vet',
        'Avoid forcing interaction; schedule exam within 24-48 hours of behavior change',
        'Note timeline of hiding onset and any triggers (guests, new pet, renovation)',
      ],
    },
    relatedSlugs: [
      'cat-limping-front-leg-when-to-call-vet',
      'cat-bad-breath-dental-disease-stages',
      'cat-peeing-outside-litter-box-flutd',
      'pain-management-log-for-recovering-pets',
    ],
    internalLinks: [
      { phrase: 'pain management log', slug: 'pain-management-log-for-recovering-pets' },
      { phrase: 'cat health records checklist', slug: 'cat-health-records-checklist' },
      { phrase: 'building medical history timeline', slug: 'building-complete-pet-medical-history-timeline' },
    ],
  },
  {
    num: 85,
    slug: 'dog-shaking-trembling-toxic-shock',
    title: 'Dog Shaking and Trembling: Cold, Scared, or Toxic Shock?',
    category: 'symptom-triage',
    excerpt:
      'Shivering from fear or cold resolves with warmth and calm - persistent tremors with vomiting, ataxia, or pale gums suggest toxin ingestion, hypoglycemia, or shock needing emergency care.',
    tags: ['dog trembling', 'shaking dog', 'toxic shock', 'hypoglycemia', 'anxiety', 'poisoning signs'],
    facts: {
      symptoms: [
        'Fine muscle tremors vs. whole-body shivering',
        'Context clues: fireworks, vet visit, cold weather, or unknown',
        'Drooling, vomiting, wobbly gait with tremors (toxin pattern)',
        'Lethargy, weak suckle in toy breeds (hypoglycemia)',
      ],
      differentialDiagnoses: [
        'Situational anxiety or fear response',
        'Hypothermia or post-anesthetic shivering',
        'Xylitol, chocolate, or stimulant toxicity',
        'Hypoglycemia in small breeds or diabetic on insulin',
        'Pain, fever, seizure prodrome, or shaker syndrome (white dogs)',
      ],
      whenToGoToER: [
        'Tremors with known toxin ingestion or access to medications',
        'Collapse, seizures, or brick-red gums after heat exposure',
        'Toy breed puppy trembling and unable to stand',
        'Tremors persisting over 30 minutes without clear anxiety trigger',
      ],
      homeCare: [
        'Warm dry blanket if cold; quiet space if noise-triggered',
        'Offer small meal to toy breeds after exercise if trembling',
        'Inventory gum, candy, sugar-free products for xylitol',
        'Film tremor pattern and note exact onset time for poison control',
      ],
    },
    relatedSlugs: [
      'dog-seizures-first-3-minutes-protocol',
      'pale-gums-dogs-capillary-refill-time',
      'pet-poison-control-information-card-guide',
      'how-to-tell-if-dog-has-fever-without-thermometer',
    ],
    internalLinks: [
      { phrase: 'pet poison control card', slug: 'pet-poison-control-information-card-guide' },
      { phrase: 'pet emergency information card', slug: 'pet-emergency-information-card-guide' },
      { phrase: 'pet first-aid kit checklist', slug: 'pet-first-aid-kit-records-checklist' },
    ],
  },
  {
    num: 86,
    slug: 'ringworm-cats-symptoms-contagion-woods-lamp',
    title: "Ringworm in Cats: Symptoms, Contagion, and Wood's Lamp Testing",
    category: 'symptom-triage',
    excerpt:
      'Dermatophytosis causes circular hair loss and is zoonotic - Wood\'s lamp fluoresces only ~50% of Microsporum canis strains; fungal culture remains the diagnostic gold standard.',
    tags: ['ringworm cats', 'dermatophytosis', 'zoonotic', 'Woods lamp', 'fungal infection', 'contagious'],
    facts: {
      symptoms: [
        'Round patches of hair loss with scaly or crusty skin',
        'Broken hairs resembling stubble; mild or no itch in some cats',
        'Lesions on face, ears, or paws in young or stressed cats',
        'Wood\'s lamp apple-green fluorescence in some M. canis cases only',
      ],
      differentialDiagnoses: [
        'Microsporum canis dermatophytosis (most common in cats)',
        'Flea allergy dermatitis or eosinophilic granuloma complex',
        'Bacterial pyoderma or demodicosis',
        'Healing trauma or over-grooming alopecia',
        'Pemphigus foliaceus (autoimmune)',
      ],
      whenToGoToER: [
        'Not typically ER - schedule vet within days to limit household spread',
        'Seek urgent care if widespread skin infection with fever in immunocompromised cat',
        'Human household members develop expanding red rings - physician visit plus isolate cat',
        'Kitten with multiple lesions and failure to thrive',
      ],
      homeCare: [
        'Isolate affected cat; wash hands after contact; vacuum frequently',
        'Do not use human antifungal cream without veterinary culture confirmation',
        'Disinfect grooming tools; replace porous bedding if heavily contaminated',
        'Treat all in-contact pets - asymptomatic carriers are common',
      ],
    },
    relatedSlugs: [
      'dog-licking-paws-constantly-yeast-allergies',
      'hot-spots-dogs-home-remedies-vet-treatments',
      'multi-pet-household-health-records-setup',
      'pet-allergy-tracker-symptoms-triggers-records',
    ],
    internalLinks: [
      { phrase: 'multi-pet household records', slug: 'multi-pet-household-health-records-setup' },
      { phrase: 'pet allergy tracker', slug: 'pet-allergy-tracker-symptoms-triggers-records' },
      { phrase: 'cat health records checklist', slug: 'cat-health-records-checklist' },
    ],
  },
  {
    num: 87,
    slug: 'tick-on-dog-removal-symptoms-to-track',
    title: 'Tick Found on Dog: How to Remove It and What Symptoms to Track',
    category: 'symptom-triage',
    excerpt:
      'Grasp the tick close to skin with fine tweezers and pull straight up - watch for 30 days for lameness, fever, or platelet changes signaling Lyme, ehrlichiosis, or anaplasmosis.',
    tags: ['tick removal', 'Lyme disease', 'ehrlichiosis', 'tick-borne disease', 'anaplasmosis', 'vector-borne'],
    facts: {
      symptoms: [
        'Attached tick found during grooming - note size and engorgement',
        'Post-bite: shifting leg lameness, fever, lethargy 1-4 weeks later',
        'Reduced appetite, bruising, or nosebleeds (platelet disorders)',
        'Local swelling or infection at bite site (secondary bacterial)',
      ],
      differentialDiagnoses: [
        'Lyme borreliosis (Borrelia burgdorferi)',
        'Ehrlichiosis and anaplasmosis',
        'Rocky Mountain spotted fever (regional)',
        'Local tick bite reaction vs. systemic vector-borne disease',
        'Babesiosis in greyhounds and splenectomized dogs',
      ],
      whenToGoToER: [
        'Acute paralysis ascending from limbs (tick paralysis - remove tick urgently)',
        'Collapse, severe anemia signs, or bleeding with recent tick exposure',
        'Neurologic signs with fever within weeks of bite',
        'Unable to remove embedded head after proper attempt with worsening swelling',
      ],
      homeCare: [
        'Remove with tweezers; disinfect skin; save tick in bag with date for ID',
        'Do not burn, twist, or apply petroleum jelly',
        'Continue vet-prescribed tick prevention year-round in endemic areas',
        'Log bite date and monitor for lameness fever window (2-6 weeks)',
      ],
    },
    relatedSlugs: [
      'flea-tick-prevention-calendar-pets',
      'how-to-tell-if-dog-has-fever-without-thermometer',
      'cat-limping-front-leg-when-to-call-vet',
      'pet-lab-results-tracking-normal-ranges',
    ],
    internalLinks: [
      { phrase: 'flea and tick prevention calendar', slug: 'flea-tick-prevention-calendar-pets' },
      { phrase: 'pet lab results tracking', slug: 'pet-lab-results-tracking-normal-ranges' },
      { phrase: 'building medical history timeline', slug: 'building-complete-pet-medical-history-timeline' },
    ],
  },
  {
    num: 88,
    slug: 'cherry-eye-dogs-surgery-alternatives',
    title: 'Cherry Eye in Dogs: Can It Be Fixed Without Surgery?',
    category: 'symptom-triage',
    excerpt:
      'Prolapsed nictitating membrane gland looks like red mass at inner corner - medical repositioning sometimes works in first days, but recurrence is common without surgical tacking to preserve tear production.',
    tags: ['cherry eye', 'prolapsed third eyelid', 'nictitans gland', 'brachycephalic', 'eye surgery', 'dry eye risk'],
    facts: {
      symptoms: [
        'Pink or red oval mass at medial canthus of eye',
        'May appear intermittently before becoming permanent',
        'Mild discharge or pawing at eye',
        'Common in puppies of bulldog, cocker, beagle breeds',
      ],
      differentialDiagnoses: [
        'Prolapsed gland of third eyelid (cherry eye)',
        'Conjunctivitis or foreign body under third eyelid',
        'Orbital mass or eyelid tumor (unusual in young dogs)',
        'Keratoconjunctivitis sicca after chronic prolapse',
        'Bilateral prolapse suggesting genetic predisposition',
      ],
      whenToGoToER: [
        'Eye suddenly closed, blue, or obviously painful (glaucoma or ulcer)',
        'Mass trauma with bleeding or inability to blink',
        'Cherry eye with corneal cloudiness or squinting',
        'Young puppy with both eyes affected and not eating',
      ],
      homeCare: [
        'Do not massage aggressively at home - schedule ophthalmology consult promptly',
        'Use E-collar to prevent self-trauma until treated',
        'Apply only vet-prescribed ophthalmic ointment if provided',
        'Note breed, age at onset, and whether mass reduces spontaneously',
      ],
    },
    relatedSlugs: [
      'dog-cloudy-eyes-nuclear-sclerosis-vs-cataracts',
      'french-bulldog-respiratory-health-tracking',
      'pet-surgery-history-documentation-guide',
      'pain-management-log-for-recovering-pets',
    ],
    internalLinks: [
      { phrase: 'surgery history documentation', slug: 'pet-surgery-history-documentation-guide' },
      { phrase: 'French Bulldog health tracking', slug: 'french-bulldog-respiratory-health-tracking' },
      { phrase: 'pet imaging report storage', slug: 'pet-imaging-reports-mri-xray-storage' },
    ],
  },
  {
    num: 89,
    slug: 'cat-drooling-excessively-nausea-poison',
    title: 'Cat Drooling Excessively: Nausea, Dental Pain, or Poison?',
    category: 'symptom-triage',
    excerpt:
      'Hypersalivation in cats is rarely benign - bitter toxins, lily ingestion, and oral ulcers cause immediate drooling; nausea from kidney disease or pancreatitis needs same-day bloodwork.',
    tags: ['cat drooling', 'hypersalivation', 'nausea cat', 'lily toxicity', 'oral pain', 'poisoning'],
    facts: {
      symptoms: [
        'Profuse saliva dripping from mouth or wet chin and chest',
        'Pawing at mouth, head shaking, or refusing food',
        'Halitosis, red gums, or visible ulceration',
        'Vomiting, lethargy, or hiding accompanying drool',
      ],
      differentialDiagnoses: [
        'Nausea from GI disease, pancreatitis, or kidney failure',
        'Dental pain, stomatitis, or oral foreign body',
        'Bitter medication or household chemical exposure',
        'Lily, permethrin (dog flea product), or plant toxicity',
        'Esophageal foreign body or mass',
      ],
      whenToGoToER: [
        'Known or suspected lily, antifreeze, or permethrin exposure - immediate',
        'Drooling with difficulty breathing or swelling of face',
        'Seizures, tremors, or collapse with hypersalivation',
        'Unable to swallow water or repeated gagging',
      ],
      homeCare: [
        'Rinse mouth gently with water only if safe and cat cooperative',
        'Remove access to plants, cleaners, and dog-only flea products',
        'Do not induce vomiting unless poison control directs',
        'Bring product label or plant sample to emergency clinic',
      ],
    },
    relatedSlugs: [
      'cat-bad-breath-dental-disease-stages',
      'cat-vomiting-hairballs-gi-blockage',
      'pet-poison-control-information-card-guide',
      'cat-hiding-recognizing-pain',
    ],
    internalLinks: [
      { phrase: 'pet poison control card', slug: 'pet-poison-control-information-card-guide' },
      { phrase: 'pet dental records guide', slug: 'pet-dental-records-cleaning-history-guide' },
      { phrase: 'pet emergency information card', slug: 'pet-emergency-information-card-guide' },
    ],
  },
  {
    num: 90,
    slug: 'track-pet-symptoms-petclues-health-foresight-ai',
    title: "Track Your Pet's Symptoms Automatically with PetClues Health Foresight AI",
    category: 'symptom-triage',
    excerpt:
      'Scattered notes miss patterns vets need - timestamped symptom logs with appetite, stool, and behavior trends surface flare windows before crises and sharpen every appointment.',
    tags: ['symptom tracker', 'Health Foresight AI', 'pet health log', 'Pro features', 'triage journal', 'vet visit prep'],
    facts: {
      symptoms: [
        'Owners forget episode timing, severity, and triggers between vet visits',
        'Chronic conditions need trend data: weight, thirst, cough frequency',
        'Multi-pet homes confuse which cat vomited or which dog limped',
        'Emergency visits lack baseline vitals and medication history',
      ],
      differentialDiagnoses: [
        'Paper notes and phone photos (disorganized, not searchable)',
        'Generic notes apps without pet-specific triage fields',
        'Spreadsheets requiring manual charting discipline',
        'Reactive care without longitudinal pattern detection',
        'Fragmented records across clinics and telehealth platforms',
      ],
      whenToGoToER: [
        'Software never replaces emergency care for acute collapse, bleeding, or obstruction',
        'Export symptom log en route to ER so clinicians see timeline immediately',
        'Flag red symptoms in app but still call poison control or emergency vet directly',
        'AI insights are decision support - not diagnosis',
      ],
      homeCare: [
        'Log each episode within minutes: symptom, severity 1-5, photo optional',
        'Set reminders for medication, post-op checks, and chronic disease labs',
        'Share read-only timeline link with sitter, family, or specialist',
        'Review monthly trend report before wellness visits',
      ],
    },
    relatedSlugs: [
      'best-pet-health-tracker-app-2026',
      'chronic-condition-pet-record-system',
      'building-complete-pet-medical-history-timeline',
      'organize-pet-medical-records-online',
    ],
    internalLinks: [
      { phrase: 'best pet health tracker app', slug: 'best-pet-health-tracker-app-2026' },
      { phrase: 'organize pet medical records online', slug: 'organize-pet-medical-records-online' },
      { phrase: 'chronic condition record system', slug: 'chronic-condition-pet-record-system' },
      { phrase: 'building medical history timeline', slug: 'building-complete-pet-medical-history-timeline' },
    ],
  },
];
