/**
 * PetClues dominance blog  -  Engine 4: Pet Travel (topics 91-120).
 * Seed data for article generation; 2026 US travel benchmarks.
 */

/** @typedef {{ phrase: string; slug: string }} DominanceInternalLink */
/** @typedef {{ destinations: string[]; lineItems: Array<{ item: string; cost: string }>; requirements: string[]; timeline: string[]; regulations: string[]; checklistItems: string[]; risks: string[]; year: number; region: string; legacySlugs: string[] }} PetTravelFacts */
/** @typedef {{ num: number; slug: string; title: string; category: 'pet-travel'; excerpt: string; tags: string[]; facts: PetTravelFacts; relatedSlugs: string[]; internalLinks: DominanceInternalLink[] }} Engine4CatalogEntry */

/** @type {Engine4CatalogEntry[]} */
export const ENGINE_4_CATALOG = [
  {
    num: 91,
    slug: 'flying-domestically-dog-2026-airline-rules-carrier-sizes',
    title: 'Flying Domestically with a Dog in 2026: Airline Rules and Carrier Sizes',
    category: 'pet-travel',
    excerpt:
      'Major US carriers allow in-cabin dogs up to 20 lbs combined (pet + carrier) with fees of $100-$200 each way  -  soft-sided carriers must fit fully under the seat without protruding.',
    tags: ['domestic air travel', 'dog in cabin', 'airline pet policy', 'IATA carrier', '2026 rules'],
    facts: {
      destinations: ['United States domestic'],
      lineItems: [
        { item: 'In-cabin pet fee (one-way)', cost: '$100-$200' },
        { item: 'Soft-sided airline carrier', cost: '$60-$150' },
        { item: 'Pre-flight vet health check', cost: '$75-$125' },
      ],
      requirements: [
        'Age 8+ weeks; rabies vaccine per state law',
        'Carrier max ~17"L × 12"W × 8"H under-seat fit',
        'Health certificate if airline or state requires',
      ],
      timeline: [
        'Book pet spot at ticket purchase  -  many airlines cap cabin pets per flight',
        'Acclimate dog to carrier 2-4 weeks before travel',
        'No food 4 hours pre-flight; water via ice cubes or drip bottle',
      ],
      regulations: [
        'DOT service animal rules do not cover regular pets',
        'Summer embargoes on cargo for snub-nosed breeds',
        'One pet per passenger on most carriers',
      ],
      checklistItems: ['Airline confirmation number for pet', 'Rabies certificate and ID tags', 'Absorbent pad and spare leash'],
      risks: ['Anxiety and elimination in cabin', 'Denied boarding if carrier exceeds dimensions', 'Heat stress during tarmac delays'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'international-pet-travel-health-certificate-guide',
        'traveling-with-pets-health-documents-checklist',
        'flying-with-cats-health-documents-checklist',
        'pet-emergency-information-card-guide',
      ],
    },
    relatedSlugs: [
      'flying-cat-cabin-tsa-gabapentin-carrier-tips',
      'cargo-travel-stress-safe-large-dogs',
      'brachycephalic-breeds-cargo-travel-ban',
      'international-pet-travel-health-certificate-guide',
    ],
    internalLinks: [
      { phrase: 'international travel certificates', slug: 'international-pet-travel-health-certificate-guide' },
      { phrase: 'travel health documents', slug: 'traveling-with-pets-health-documents-checklist' },
      { phrase: 'pet emergency card', slug: 'pet-emergency-information-card-guide' },
    ],
  },
  {
    num: 92,
    slug: 'moving-eu-pet-2026-rabies-titer-microchip-guide',
    title: 'Moving to the EU with a Pet: The 2026 Rabies Titer and Microchip Guide',
    category: 'pet-travel',
    excerpt:
      'EU non-commercial pet entry requires ISO microchip first, rabies vaccine 21+ days later, then a rabies antibody titer (FAVN) drawn 30+ days post-vaccine  -  plan 4-6 months before move.',
    tags: ['EU pet travel', 'rabies titer', 'FAVN test', 'microchip', 'relocation'],
    facts: {
      destinations: ['European Union', 'France', 'Germany', 'Spain', 'Italy'],
      lineItems: [
        { item: 'ISO 11784/11785 microchip + implant', cost: '$45-$80' },
        { item: 'Rabies FAVN titer (USDA lab)', cost: '$120-$200' },
        { item: 'EU health certificate (USDA endorsement)', cost: '$150-$400' },
      ],
      requirements: [
        'ISO microchip implanted before rabies vaccine',
        'Rabies titer ≥0.5 IU/ml from approved lab',
        'EU animal health certificate within 10 days of entry',
      ],
      timeline: [
        'Month 0: microchip + rabies vaccine',
        'Month 1: titer blood draw',
        'Month 4+: travel after 3-month wait post-titer (most EU countries)',
      ],
      regulations: [
        'Non-commercial move: ≤5 pets, not changing ownership within 5 days of owner travel',
        'Tapeworm treatment for UK, Ireland, Finland, Malta, Norway',
        'Banned breeds vary by member state',
      ],
      checklistItems: ['USDA-accredited vet appointment', 'Original titer lab report', 'Owner passport matching certificate'],
      risks: ['Wrong microchip date invalidates entire timeline', 'Non-ISO chips require re-implant and restart', 'Brexit UK uses separate APHA rules'],
      year: 2026,
      region: 'European Union',
      legacySlugs: [
        'international-pet-travel-health-certificate-guide',
        'microchip-registration-guide-dogs-cats',
        'cross-country-move-pet-records-guide',
        'organize-pet-medical-records-online',
      ],
    },
    relatedSlugs: [
      'moving-uk-dog-defra-regulations',
      'usda-health-certificate-pet-travel-timeline-fees',
      'sync-pet-microchip-digital-medical-record',
      'international-pet-travel-health-certificate-guide',
    ],
    internalLinks: [
      { phrase: 'international pet travel guide', slug: 'international-pet-travel-health-certificate-guide' },
      { phrase: 'microchip registration', slug: 'microchip-registration-guide-dogs-cats' },
      { phrase: 'cross-country move records', slug: 'cross-country-move-pet-records-guide' },
    ],
  },
  {
    num: 93,
    slug: 'moving-uk-dog-defra-regulations',
    title: 'Moving to the UK with a Dog: Navigating the Defra Regulations',
    category: 'pet-travel',
    excerpt:
      'Post-Brexit UK pet import requires microchip, rabies vaccine, FAVN titer, 3-month wait, tapeworm treatment 24-120 hours before entry, and an APHA-endorsed health certificate.',
    tags: ['UK pet import', 'Defra', 'APHA', 'tapeworm', 'Great Britain'],
    facts: {
      destinations: ['United Kingdom', 'England', 'Scotland', 'Wales'],
      lineItems: [
        { item: 'Rabies titer + 3-month wait', cost: '$120-$200' },
        { item: 'Tapeworm treatment (Echinococcus)', cost: '$25-$60' },
        { item: 'APHA health certificate endorsement', cost: '$150-$400' },
        { item: 'Approved route / carrier fee', cost: '$200-$2,000' },
      ],
      requirements: [
        'Enter via approved route (Eurotunnel, ferry, designated airports)',
        'Tapeworm (praziquantel) documented on certificate',
        'Banned breeds: Pit Bull Terrier type, Japanese Tosa, etc.',
      ],
      timeline: [
        '4+ months: same EU titer pathway',
        '48-24 hours before UK arrival: vet-administered tapeworm treatment',
        'Within 10 days: APHA certificate issued',
      ],
      regulations: [
        'Defra governs non-commercial pet travel into GB',
        'Northern Ireland follows EU-style rules with UK checks',
        'Commercial imports need additional Balai rules',
      ],
      checklistItems: ['Carrier approved for UK entry point', 'Tapeworm treatment timestamp on cert', 'Customs declaration at border'],
      risks: ['Missing tapeworm window = quarantine or refused entry', 'Prohibited breeds seized at border', 'Wrong entry port without pre-approval'],
      year: 2026,
      region: 'United Kingdom',
      legacySlugs: [
        'international-pet-travel-health-certificate-guide',
        'microchip-registration-guide-dogs-cats',
        'organize-pet-medical-records-online',
        'cross-country-move-pet-records-guide',
      ],
    },
    relatedSlugs: [
      'moving-eu-pet-2026-rabies-titer-microchip-guide',
      'usda-health-certificate-pet-travel-timeline-fees',
      'pet-relocation-scams-verify-safe-transport',
      'international-pet-travel-health-certificate-guide',
    ],
    internalLinks: [
      { phrase: 'international travel certificates', slug: 'international-pet-travel-health-certificate-guide' },
      { phrase: 'organize medical records', slug: 'organize-pet-medical-records-online' },
      { phrase: 'microchip guide', slug: 'microchip-registration-guide-dogs-cats' },
    ],
  },
  {
    num: 94,
    slug: 'create-shareable-digital-emergency-pet-passport',
    title: 'How to Create a Shareable Digital Emergency Pet Passport',
    category: 'pet-travel',
    excerpt:
      'A digital pet passport bundles microchip ID, meds, allergies, vet contacts, and vaccination PDFs into one shareable link  -  critical when sitters, airlines, or ER vets need instant access.',
    tags: ['digital pet passport', 'emergency records', 'shareable link', 'pet sitter', 'travel documents'],
    facts: {
      destinations: ['United States', 'International'],
      lineItems: [
        { item: 'Vet record export / scan time', cost: '$0-$50' },
        { item: 'Pet health app (annual)', cost: '$0-$120' },
        { item: 'QR tag for collar (optional)', cost: '$15-$35' },
      ],
      requirements: [
        'Microchip number and registry contact',
        'Current rabies certificate with lot number',
        'Medication list with dosages and pharmacy',
      ],
      timeline: [
        'Day 1: gather PDFs from vet portal',
        'Day 2: upload vaccines, rabies, prescriptions',
        'Day 3: generate share link for sitter or travel',
      ],
      regulations: [
        'Digital copies supplement  -  not replace  -  USDA originals for border entry',
        'Revoke sitter access after trip for privacy',
      ],
      checklistItems: ['Emergency vet and poison control numbers', 'Insurance policy number', 'Recent photo of pet'],
      risks: ['Outdated rabies cert on phone while paper expired', 'Broken link when offline  -  download PDF backup', 'Oversharing medical data publicly'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'pet-emergency-information-card-guide',
        'organize-pet-medical-records-online',
        'pet-sitter-instructions-medical-emergency-info',
        'microchip-registration-guide-dogs-cats',
      ],
    },
    relatedSlugs: [
      'one-click-medical-profile-pet-boarder',
      'pet-emergency-information-card-guide',
      'leaving-dog-rover-sitter-digital-handoff',
      'organize-pet-medical-records-online',
    ],
    internalLinks: [
      { phrase: 'pet emergency information card', slug: 'pet-emergency-information-card-guide' },
      { phrase: 'organize pet medical records', slug: 'organize-pet-medical-records-online' },
      { phrase: 'pet sitter instructions', slug: 'pet-sitter-instructions-medical-emergency-info' },
    ],
  },
  {
    num: 95,
    slug: 'leaving-dog-rover-sitter-digital-handoff',
    title: 'Leaving Your Dog with a Rover Sitter: The Ultimate Digital Handoff',
    category: 'pet-travel',
    excerpt:
      'Rover sitters need feeding schedules, vet authorization, emergency contacts, and medication photos  -  a structured digital handoff cuts miscommunication and speeds ER decisions.',
    tags: ['Rover sitter', 'pet sitting', 'digital handoff', 'dog care', 'instructions'],
    facts: {
      destinations: ['United States'],
      lineItems: [
        { item: 'Rover booking fee (platform)', cost: '20% of sitter rate' },
        { item: 'Meet-and-greet (recommended)', cost: '$0' },
        { item: 'Emergency vet deposit hold', cost: '$200-$500' },
      ],
      requirements: [
        'Rover vet release form signed',
        'House rules: rooms off-limits, leash policy',
        'Medication with labeled syringes or pill pockets',
      ],
      timeline: [
        '1 week before: share digital care doc',
        'Day before: in-person walkthrough + lock codes',
        'During stay: daily photo check-in agreement',
      ],
      regulations: [
        'Rover Guarantee covers certain vet emergencies  -  read exclusions',
        'Local licensing may require sitter business permit',
      ],
      checklistItems: ['Food portions pre-measured', 'Spare key or smart lock code', 'Carrier and leash by door'],
      risks: ['Incomplete allergy info leads to treat incidents', 'Sitter cannot reach you during ER', 'Dog escapes without updated microchip address'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'pet-sitter-instructions-medical-emergency-info',
        'pet-emergency-information-card-guide',
        'dog-feeding-schedule-walk-tracker',
        'organize-pet-medical-records-online',
      ],
    },
    relatedSlugs: [
      'essential-documents-dog-walker-before-work',
      'five-minute-checklist-leaving-pet-neighbor',
      'one-click-medical-profile-pet-boarder',
      'pet-sitter-instructions-medical-emergency-info',
    ],
    internalLinks: [
      { phrase: 'pet sitter instructions', slug: 'pet-sitter-instructions-medical-emergency-info' },
      { phrase: 'emergency information card', slug: 'pet-emergency-information-card-guide' },
      { phrase: 'dog feeding schedule', slug: 'dog-feeding-schedule-walk-tracker' },
    ],
  },
  {
    num: 96,
    slug: 'flying-cat-cabin-tsa-gabapentin-carrier-tips',
    title: 'Flying with a Cat in Cabin: TSA Checks, Gabapentin, and Carrier Tips',
    category: 'pet-travel',
    excerpt:
      'TSA requires you to remove the cat from the carrier at security; gabapentin may reduce travel anxiety but needs a vet prescription  -  never use human sedatives without guidance.',
    tags: ['cat air travel', 'TSA', 'gabapentin', 'in-cabin cat', 'carrier training'],
    facts: {
      destinations: ['United States domestic', 'International'],
      lineItems: [
        { item: 'In-cabin cat fee', cost: '$100-$200' },
        { item: 'Expandable soft carrier', cost: '$45-$120' },
        { item: 'Gabapentin consult + Rx', cost: '$50-$100' },
      ],
      requirements: [
        'Cat must remain in carrier except at TSA screening',
        'Rabies certificate for interstate/international legs',
        'Absorbent liner and quiet toys only',
      ],
      timeline: [
        '4 weeks: carrier training with treats',
        '1 week: vet discusses gabapentin trial at home',
        'Travel day: light meal 4 hours before',
      ],
      regulations: [
        'FAA: pet counts as carry-on on most airlines',
        'Some airlines ban sedated animals',
        'International cats need USDA cert chain',
      ],
      checklistItems: ['Harness and leash for security', 'Health certificate copies', 'Calming pheromone spray (optional)'],
      risks: ['Escape at security checkpoint', 'Respiratory stress from sedation', '48-hour food/water strike after flight'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'flying-with-cats-health-documents-checklist',
        'traveling-with-pets-health-documents-checklist',
        'pet-emergency-information-card-guide',
        'international-pet-travel-health-certificate-guide',
      ],
    },
    relatedSlugs: [
      'flying-domestically-dog-2026-airline-rules-carrier-sizes',
      'sedating-pet-air-travel-vets-recommend-against',
      'flying-with-cats-health-documents-checklist',
      'road-tripping-cats-litter-box-anxiety-meds',
    ],
    internalLinks: [
      { phrase: 'flying with cats checklist', slug: 'flying-with-cats-health-documents-checklist' },
      { phrase: 'travel health documents', slug: 'traveling-with-pets-health-documents-checklist' },
      { phrase: 'pet emergency card', slug: 'pet-emergency-information-card-guide' },
    ],
  },
  {
    num: 97,
    slug: 'pet-shipping-companies-cost-why-need-one',
    title: 'Pet Shipping Companies: What They Cost and Why You Might Need One',
    category: 'pet-travel',
    excerpt:
      'Door-to-door pet relocation runs $1,500-$5,000 domestically and $3,000-$8,000+ internationally  -  specialists handle customs, routing, and IATA crates when owners cannot fly with pets.',
    tags: ['pet shipping', 'pet relocation', 'IPATA', 'cargo transport', 'moving with pets'],
    facts: {
      destinations: ['United States', 'International'],
      lineItems: [
        { item: 'Domestic ground + flight coordination', cost: '$1,500-$3,500' },
        { item: 'International door-to-door', cost: '$3,000-$8,000+' },
        { item: 'Custom IATA crate (large dog)', cost: '$200-$500' },
        { item: 'Customs broker fees', cost: '$150-$400' },
      ],
      requirements: [
        'IPATA or USDA-registered transporter',
        'Rabies, titer, import permit per destination',
        'Fit-to-fly exam within 10 days',
      ],
      timeline: [
        '3-6 months international planning',
        '2 weeks: crate acclimation',
        'Travel day: handoff at origin airport or home pickup',
      ],
      regulations: [
        'IATA LAR crate standards for cargo',
        'Some countries require quarantine booking before flight',
        'Commercial vs. non-commercial import paths',
      ],
      checklistItems: ['Written contract with insurance', 'GPS or photo updates en route', 'Destination vet pre-registration'],
      risks: ['Unlicensed brokers (see scam guide)', 'Heat embargoes delaying shipment', 'Emotional distress in cargo hold'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'international-pet-travel-health-certificate-guide',
        'cross-country-move-pet-records-guide',
        'organize-pet-medical-records-online',
        'pet-emergency-information-card-guide',
      ],
    },
    relatedSlugs: [
      'pet-relocation-scams-verify-safe-transport',
      'cargo-travel-stress-safe-large-dogs',
      'usda-health-certificate-pet-travel-timeline-fees',
      'cross-country-move-pet-records-guide',
    ],
    internalLinks: [
      { phrase: 'international travel guide', slug: 'international-pet-travel-health-certificate-guide' },
      { phrase: 'cross-country move records', slug: 'cross-country-move-pet-records-guide' },
      { phrase: 'organize medical records', slug: 'organize-pet-medical-records-online' },
    ],
  },
  {
    num: 98,
    slug: 'usda-health-certificate-pet-travel-timeline-fees',
    title: 'Getting a USDA Health Certificate for Pet Travel: Timeline and Fees',
    category: 'pet-travel',
    excerpt:
      'USDA APHIS endorsement of a vet-issued health certificate costs $38-$173 plus vet exam fees  -  international travel needs appointment 2-10 days before departure depending on destination.',
    tags: ['USDA', 'APHIS', 'health certificate', 'endorsement', 'pet export'],
    facts: {
      destinations: ['United States export', 'International'],
      lineItems: [
        { item: 'USDA endorsement fee (2026)', cost: '$38-$173' },
        { item: 'Accredited vet exam + certificate', cost: '$150-$350' },
        { item: 'Overnight shipping to USDA office', cost: '$25-$75' },
      ],
      requirements: [
        'USDA-accredited veterinarian issues certificate',
        'Rabies and destination-specific vaccines current',
        'Microchip matches all paperwork',
      ],
      timeline: [
        '30+ days before: verify destination rules',
        'Within 10 days (often 48-72 hours) of travel: vet exam',
        'Submit to USDA for endorsement  -  allow 3-7 business days',
      ],
      regulations: [
        'Each country publishes unique entry requirements on APHIS site',
        'EU uses EU model certificate; UK uses separate form',
        'Hawaii and territory rules differ from mainland',
      ],
      checklistItems: ['APHIS VEHCS online submission if available', 'Original ink-signed copies', 'Return envelope for endorsed cert'],
      risks: ['Missed endorsement window forces rebooking', 'Typo on microchip number invalidates cert', 'Federal holiday delays at USDA offices'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'international-pet-travel-health-certificate-guide',
        'traveling-with-pets-health-documents-checklist',
        'microchip-registration-guide-dogs-cats',
        'organize-pet-medical-records-online',
      ],
    },
    relatedSlugs: [
      'moving-eu-pet-2026-rabies-titer-microchip-guide',
      'pet-travel-hawaii-quarantine-laws',
      'traveling-mexico-dog-senasica-requirements-2026',
      'international-pet-travel-health-certificate-guide',
    ],
    internalLinks: [
      { phrase: 'international pet travel guide', slug: 'international-pet-travel-health-certificate-guide' },
      { phrase: 'travel documents checklist', slug: 'traveling-with-pets-health-documents-checklist' },
      { phrase: 'microchip registration', slug: 'microchip-registration-guide-dogs-cats' },
    ],
  },
  {
    num: 99,
    slug: 'pet-travel-hawaii-quarantine-laws',
    title: 'Pet Travel to Hawaii: Navigating the Strict Quarantine Laws',
    category: 'pet-travel',
    excerpt:
      "Hawaii's rabies-free status means direct release requires microchip, two rabies vaccines, OIE-FAVN titer, and 30-day pre-arrival waiting  -  otherwise quarantine up to 120 days at $1,080+.",
    tags: ['Hawaii quarantine', 'rabies-free state', 'direct airport release', 'DAR', 'island pet travel'],
    facts: {
      destinations: ['Hawaii'],
      lineItems: [
        { item: '5-day-or-less program fee', cost: '$244' },
        { item: '120-day quarantine (if ineligible)', cost: '$1,080+' },
        { item: 'Neighbor island inspection fee', cost: '$165' },
        { item: 'FAVN titer test', cost: '$120-$200' },
      ],
      requirements: [
        'Two rabies vaccines ≥30 days apart',
        'OIE-FAVN titer ≥0.5 IU/ml',
        '30-day wait after successful titer before arrival',
      ],
      timeline: [
        'Month 0-4: vaccines and titer',
        'Month 5: 30-day waiting period completes',
        'Arrive at Honolulu (or approved port) with paperwork',
      ],
      regulations: [
        'Hawaii DAR administers Animal Quarantine',
        'Only Honolulu airport for direct release on Oahu',
        'Cats and dogs only  -  no ferrets',
      ],
      checklistItems: ['Flight arrives during inspection hours', 'Pre-paid quarantine application', 'Tick treatment documentation'],
      risks: ['One day early breaks 30-day wait', 'Wrong port = full quarantine', 'Titer failure restarts timeline'],
      year: 2026,
      region: 'Hawaii, United States',
      legacySlugs: [
        'international-pet-travel-health-certificate-guide',
        'microchip-registration-guide-dogs-cats',
        'organize-pet-medical-records-online',
        'traveling-with-pets-health-documents-checklist',
      ],
    },
    relatedSlugs: [
      'usda-health-certificate-pet-travel-timeline-fees',
      'moving-eu-pet-2026-rabies-titer-microchip-guide',
      'sync-pet-microchip-digital-medical-record',
      'international-pet-travel-health-certificate-guide',
    ],
    internalLinks: [
      { phrase: 'international travel certificates', slug: 'international-pet-travel-health-certificate-guide' },
      { phrase: 'organize medical records', slug: 'organize-pet-medical-records-online' },
      { phrase: 'microchip guide', slug: 'microchip-registration-guide-dogs-cats' },
    ],
  },
  {
    num: 100,
    slug: 'traveling-mexico-dog-senasica-requirements-2026',
    title: 'Traveling to Mexico with a Dog: Senasica Requirements for 2026',
    category: 'pet-travel',
    excerpt:
      'Mexico allows healthy dogs and cats with proof of rabies, tick treatment, and a USDA health certificate  -  Senasica inspection at border is usually brief but paperwork must match microchip.',
    tags: ['Mexico pet travel', 'Senasica', 'border crossing', 'rabies certificate', '2026'],
    facts: {
      destinations: ['Mexico'],
      lineItems: [
        { item: 'USDA health certificate', cost: '$150-$350' },
        { item: 'Rabies vaccine (current)', cost: '$20-$40' },
        { item: 'Tick/flea treatment proof', cost: '$15-$50' },
      ],
      requirements: [
        'Dog/cat in good health, free of infectious disease',
        'Rabies vaccine certificate',
        'USDA-accredited vet health certificate',
      ],
      timeline: [
        '1-2 weeks before: vet exam and certificate',
        'Border: OISA/Senasica visual inspection',
        'Return to US: CDC dog import rules if applicable',
      ],
      regulations: [
        'Senasica (SAGARPA) inspects at official points of entry',
        'No quarantine for personal pets with valid docs',
        'Maximum 2 pets per person without import permit',
      ],
      checklistItems: ['Certificate within 10 days of entry', 'Spanish translation optional but helpful', 'Carrier for border walk-through'],
      risks: ['Expired rabies cert = denied entry or fines', 'Driving remote crossings without inspection hours', 'CDC re-entry requirements for dogs'],
      year: 2026,
      region: 'Mexico',
      legacySlugs: [
        'international-pet-travel-health-certificate-guide',
        'traveling-with-pets-health-documents-checklist',
        'microchip-registration-guide-dogs-cats',
        'organize-pet-medical-records-online',
      ],
    },
    relatedSlugs: [
      'flying-canada-dog-border-rules-cbsa-checks',
      'usda-health-certificate-pet-travel-timeline-fees',
      'traveling-with-pets-health-documents-checklist',
      'international-pet-travel-health-certificate-guide',
    ],
    internalLinks: [
      { phrase: 'travel health documents', slug: 'traveling-with-pets-health-documents-checklist' },
      { phrase: 'international travel guide', slug: 'international-pet-travel-health-certificate-guide' },
      { phrase: 'microchip registration', slug: 'microchip-registration-guide-dogs-cats' },
    ],
  },
  {
    num: 101,
    slug: 'pet-medical-emergency-road-trip',
    title: 'What Happens If Your Pet Has a Medical Emergency on a Road Trip?',
    category: 'pet-travel',
    excerpt:
      'On a road trip, locate the nearest AAHA or VECCS emergency hospital via app before crisis hits  -  bring records, know payment policy, and never give human meds without vet guidance.',
    tags: ['road trip emergency', 'travel vet', 'pet ER', 'highway travel', 'first aid'],
    facts: {
      destinations: ['United States interstate'],
      lineItems: [
        { item: 'Emergency exam fee (traveling)', cost: '$150-$350' },
        { item: 'After-hours surcharge', cost: '$50-$150' },
        { item: 'Stabilization + diagnostics', cost: '$500-$3,000+' },
      ],
      requirements: [
        'Digital or paper medical history accessible offline',
        'Pet insurance policy number and pre-auth line',
        'Carrier or harness for safe clinic transfer',
      ],
      timeline: [
        'Before trip: save ER hospitals along route',
        'During crisis: call ahead while driving to ER',
        'Post-stabilization: request records sent to home vet',
      ],
      regulations: [
        'Interstate travel may require rabies cert if stopped by authorities',
        'Some states restrict rabies vaccine validity windows',
      ],
      checklistItems: ['Poison control number (888-426-4435)', 'Towel and spare leash', 'Credit card for ER deposit'],
      risks: ['Delayed care in rural stretches', 'Heatstroke in parked car', 'Foreign object ingestion at rest stops'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'pet-emergency-information-card-guide',
        'after-hours-emergency-vet-information-sheet',
        'organize-pet-medical-records-online',
        'traveling-with-pets-health-documents-checklist',
      ],
    },
    relatedSlugs: [
      'pet-first-aid-kit-hiking',
      'pet-emergency-kit-hurricanes-wildfires',
      'create-shareable-digital-emergency-pet-passport',
      'pet-emergency-information-card-guide',
    ],
    internalLinks: [
      { phrase: 'emergency vet information sheet', slug: 'after-hours-emergency-vet-information-sheet' },
      { phrase: 'pet emergency card', slug: 'pet-emergency-information-card-guide' },
      { phrase: 'organize medical records', slug: 'organize-pet-medical-records-online' },
    ],
  },
  {
    num: 102,
    slug: 'essential-documents-dog-walker-before-work',
    title: 'Essential Documents to Give Your Dog Walker Before You Go to Work',
    category: 'pet-travel',
    excerpt:
      'Daily dog walkers need vet authorization, emergency contacts, leash rules, and medication instructions  -  a one-page digital handoff prevents ER delays when you are in meetings.',
    tags: ['dog walker', 'daily care', 'workday pet care', 'handoff documents', 'urban dogs'],
    facts: {
      destinations: ['United States'],
      lineItems: [
        { item: 'Walker background check service', cost: '$0-$35' },
        { item: 'Key lockbox or smart lock', cost: '$30-$200' },
        { item: 'Printed emergency card', cost: '$0-$15' },
      ],
      requirements: [
        'Signed vet treatment authorization',
        'Feeding and treat restrictions in writing',
        'Microchip number and tag photo',
      ],
      timeline: [
        'Day 1: meet-and-greet on route',
        'Week 1: trial walks with feedback',
        'Ongoing: update doc when meds or diet change',
      ],
      regulations: [
        'Local leash laws and breed restrictions',
        'Some HOAs require walker insurance certificate',
      ],
      checklistItems: ['Spare harness and poop bags', 'Thunderstorm / fireworks protocol', 'Building access codes'],
      risks: ['Dog slip on loose collar', 'Walker cannot reach owner during bite incident', 'Missed insulin if diabetic'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'pet-sitter-instructions-medical-emergency-info',
        'dog-feeding-schedule-walk-tracker',
        'pet-emergency-information-card-guide',
        'organize-pet-medical-records-online',
      ],
    },
    relatedSlugs: [
      'leaving-dog-rover-sitter-digital-handoff',
      'five-minute-checklist-leaving-pet-neighbor',
      'one-click-medical-profile-pet-boarder',
      'pet-sitter-instructions-medical-emergency-info',
    ],
    internalLinks: [
      { phrase: 'pet sitter instructions', slug: 'pet-sitter-instructions-medical-emergency-info' },
      { phrase: 'feeding and walk tracker', slug: 'dog-feeding-schedule-walk-tracker' },
      { phrase: 'emergency information card', slug: 'pet-emergency-information-card-guide' },
    ],
  },
  {
    num: 103,
    slug: 'digital-vaccine-proof-doggy-daycare-boarding',
    title: 'Digital Vaccine Proof for Doggy Daycares and Boarding Facilities',
    category: 'pet-travel',
    excerpt:
      'Daycares require Bordetella every 6-12 months, rabies, and often canine influenza  -  digital vaccine logs with lot numbers speed check-in and prevent denied drop-offs.',
    tags: ['doggy daycare', 'boarding vaccines', 'Bordetella', 'digital records', 'vaccine proof'],
    facts: {
      destinations: ['United States'],
      lineItems: [
        { item: 'Bordetella vaccine', cost: '$25-$45' },
        { item: 'Canine influenza (H3N2/H3N8)', cost: '$40-$70' },
        { item: 'Daycare trial day', cost: '$25-$50' },
      ],
      requirements: [
        'Rabies per state law',
        'Bordetella within facility window (often 6 months)',
        'Negative fecal or parasite prevention per policy',
      ],
      timeline: [
        '2 weeks before first visit: schedule vaccines',
        '48 hours before: upload records to facility portal',
        'Annual: set reminders for expiring shots',
      ],
      regulations: [
        'Facilities may refuse pets with expired vaccines',
        'Some counties mandate rabies reporting',
      ],
      checklistItems: ['Vet clinic fax/email on file', 'Titer exceptions documented if applicable', 'Flea/tick prevention current'],
      risks: ['Last-minute vaccine = 7-14 day wait before admission', 'Mismatched pet name on cert', 'Kennel cough outbreak despite vaccines'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'bordetella-vaccine-boarding-daycare-guide',
        'organize-pet-medical-records-online',
        'puppy-vaccination-schedule-2026',
        'pet-emergency-information-card-guide',
      ],
    },
    relatedSlugs: [
      'luxury-boarding-facility-health-requirements',
      'bordetella-vaccine-boarding-daycare-guide',
      'one-click-medical-profile-pet-boarder',
    ],
    internalLinks: [
      { phrase: 'boarding and daycare vaccines', slug: 'bordetella-vaccine-boarding-daycare-guide' },
      { phrase: 'organize medical records', slug: 'organize-pet-medical-records-online' },
      { phrase: 'puppy vaccination schedule', slug: 'puppy-vaccination-schedule-2026' },
    ],
  },
  {
    num: 104,
    slug: 'find-english-speaking-vet-abroad',
    title: 'How to Find an English-Speaking Vet Abroad',
    category: 'pet-travel',
    excerpt:
      'Use USDA post pet lists, expat forums, and Google Maps reviews filtered by "emergency"  -  carry translated medication names and your pet\'s digital record before leaving home.',
    tags: ['vet abroad', 'expat pets', 'travel emergency', 'English-speaking vet', 'international'],
    facts: {
      destinations: ['European Union', 'United Kingdom', 'Mexico', 'Japan', 'Global'],
      lineItems: [
        { item: 'International pet insurance claim', cost: 'Varies' },
        { item: 'Translation app / document service', cost: '$0-$50' },
        { item: 'Emergency consult abroad', cost: '$80-$300' },
      ],
      requirements: [
        'Pet passport or USDA export paperwork',
        'Medication generic names (not just brand)',
        'Microchip registry updated with travel contact',
      ],
      timeline: [
        'Pre-trip: bookmark 3 clinics near lodging',
        'Day 1 abroad: confirm hours and payment methods',
        'Emergency: call clinic en route with symptoms',
      ],
      regulations: [
        'EU vets use different vaccine brands  -  records must show dates',
        'Some countries require government vet for export cert',
      ],
      checklistItems: ['Embassy veterinarian referral list', 'Cash and chip-enabled card', 'Carrier for taxi transport'],
      risks: ['Weekend closures in small towns', 'Language barrier on dosing instructions', 'Payment due upfront without insurance direct billing'],
      year: 2026,
      region: 'International',
      legacySlugs: [
        'international-pet-travel-health-certificate-guide',
        'organize-pet-medical-records-online',
        'pet-emergency-information-card-guide',
        'traveling-with-pets-health-documents-checklist',
      ],
    },
    relatedSlugs: [
      'moving-eu-pet-2026-rabies-titer-microchip-guide',
      'create-shareable-digital-emergency-pet-passport',
      'pet-medical-emergency-road-trip',
      'international-pet-travel-health-certificate-guide',
    ],
    internalLinks: [
      { phrase: 'international travel guide', slug: 'international-pet-travel-health-certificate-guide' },
      { phrase: 'digital emergency passport', slug: 'create-shareable-digital-emergency-pet-passport' },
      { phrase: 'organize medical records', slug: 'organize-pet-medical-records-online' },
    ],
  },
  {
    num: 105,
    slug: 'hotel-pet-policies-2026-marriott-hilton-boutique-fees',
    title: 'Hotel Pet Policies in 2026: Marriott, Hilton, and Boutique Fees',
    category: 'pet-travel',
    excerpt:
      'Marriott and Hilton brands charge $50-$150 per stay for dogs up to 40-75 lbs  -  boutique hotels may cap at 25 lbs with $25-$100 nightly fees and strict leave-in-crate rules.',
    tags: ['pet-friendly hotels', 'Marriott', 'Hilton', 'travel fees', 'boutique hotels'],
    facts: {
      destinations: ['United States'],
      lineItems: [
        { item: 'Marriott pet fee (per stay)', cost: '$50-$150' },
        { item: 'Hilton pet fee (per stay)', cost: '$50-$125' },
        { item: 'Boutique nightly pet fee', cost: '$25-$100/night' },
        { item: 'Damage deposit (refundable)', cost: '$100-$250' },
      ],
      requirements: [
        'Advance pet registration at check-in',
        'Crate when unattended in room',
        'Leash in all public areas',
      ],
      timeline: [
        'Booking: filter pet-friendly and confirm weight limit',
        'Check-in: sign pet policy addendum',
        'Checkout: request fee itemized for records',
      ],
      regulations: [
        'ADA service animals exempt from pet fees',
        'ESA no longer covered by airline/hotel federal rules  -  property discretion',
      ],
      checklistItems: ['Proof of flea treatment', 'Quiet chew toys', 'Door hanger "pet in room"'],
      risks: ['Barking complaints → eviction without refund', 'Undisclosed pet cleaning fee $200-$500', 'Breed restrictions at some properties'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'traveling-with-pets-health-documents-checklist',
        'pet-emergency-information-card-guide',
        'organize-pet-medical-records-online',
        'pet-sitter-instructions-medical-emergency-info',
      ],
    },
    relatedSlugs: [
      'flying-domestically-dog-2026-airline-rules-carrier-sizes',
      'camping-dogs-flea-tick-leptospirosis-protocols',
      'esa-vs-service-dog-travel-rules-airlines',
      'traveling-with-pets-health-documents-checklist',
    ],
    internalLinks: [
      { phrase: 'travel health documents', slug: 'traveling-with-pets-health-documents-checklist' },
      { phrase: 'pet emergency card', slug: 'pet-emergency-information-card-guide' },
      { phrase: 'ESA vs service dog rules', slug: 'esa-vs-service-dog-travel-rules-airlines' },
    ],
  },
  {
    num: 106,
    slug: 'camping-dogs-flea-tick-leptospirosis-protocols',
    title: 'Camping with Dogs: Flea, Tick, and Leptospirosis Protocols',
    category: 'pet-travel',
    excerpt:
      'Woodland campsites expose dogs to ticks carrying Lyme disease and standing water with Leptospira  -  use vet-recommended preventives and check coats twice daily.',
    tags: ['camping with dogs', 'ticks', 'Lyme disease', 'leptospirosis', 'outdoor travel'],
    facts: {
      destinations: ['United States national parks', 'State forests'],
      lineItems: [
        { item: 'Monthly flea/tick preventive', cost: '$15-$40/month' },
        { item: 'Leptospirosis vaccine (annual)', cost: '$25-$45' },
        { item: 'Tick removal tool + first-aid kit', cost: '$15-$40' },
      ],
      requirements: [
        'Leash where required; bear-bag food away from tent',
        'Current rabies tag visible',
        'Collapsible bowl and filtered water',
      ],
      timeline: [
        '2 weeks before: confirm preventives active',
        'Daily at camp: full-body tick check',
        'Post-trip: bath and monitor for fever or lameness',
      ],
      regulations: [
        'BARK rules in many national parks',
        'Some campgrounds require proof of vaccines',
      ],
      checklistItems: ['LED collar light', 'Paw balm for rough terrain', 'Vet phone saved offline'],
      risks: ['Tick-borne illness 24-72 hour attachment window', 'Lepto from shared water bowls', 'Heat exhaustion on hikes'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'traveling-with-pets-health-documents-checklist',
        'pet-emergency-information-card-guide',
        'puppy-vaccination-schedule-2026',
        'organize-pet-medical-records-online',
      ],
    },
    relatedSlugs: [
      'pet-first-aid-kit-hiking',
      'pet-medical-emergency-road-trip',
      'hotel-pet-policies-2026-marriott-hilton-boutique-fees',
      'traveling-with-pets-health-documents-checklist',
    ],
    internalLinks: [
      { phrase: 'hiking first-aid kit', slug: 'pet-first-aid-kit-hiking' },
      { phrase: 'travel documents', slug: 'traveling-with-pets-health-documents-checklist' },
      { phrase: 'emergency card', slug: 'pet-emergency-information-card-guide' },
    ],
  },
  {
    num: 107,
    slug: 'luxury-boarding-facility-health-requirements',
    title: 'Leaving Your Pet at a Luxury Boarding Facility: Health Requirements',
    category: 'pet-travel',
    excerpt:
      'Luxury kennels and resort boarders often require vaccines within 30 days, vet exam within 12 months, and parasite prevention  -  spa add-ons run $40-$100/day on top of $75-$150/night.',
    tags: ['luxury boarding', 'pet resort', 'kennel requirements', 'vacation boarding', 'health screening'],
    facts: {
      destinations: ['United States'],
      lineItems: [
        { item: 'Luxury boarding (per night)', cost: '$75-$150' },
        { item: 'Spa / play package', cost: '$40-$100/day' },
        { item: 'Required vet wellness exam', cost: '$55-$120' },
      ],
      requirements: [
        'Full vaccine panel including Bordetella and flu',
        'Fecal test negative within 6-12 months',
        'Emergency contact and authorized vet on file',
      ],
      timeline: [
        '4 weeks before: book peak-season slots',
        '2 weeks before: vaccines if expiring',
        'Drop-off: bring labeled food and meds',
      ],
      regulations: [
        'State kennel licensing inspections vary',
        'Medication logs required for controlled drugs',
      ],
      checklistItems: ['Favorite bed or shirt for scent', 'Explicit feeding instructions', 'Digital med profile link'],
      risks: ['GI upset from new food', 'Stress colitis in anxious pets', 'Denied entry for expired Bordetella'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'bordetella-vaccine-boarding-daycare-guide',
        'pet-sitter-instructions-medical-emergency-info',
        'organize-pet-medical-records-online',
        'pet-emergency-information-card-guide',
      ],
    },
    relatedSlugs: [
      'digital-vaccine-proof-doggy-daycare-boarding',
      'one-click-medical-profile-pet-boarder',
      'leaving-dog-rover-sitter-digital-handoff',
      'bordetella-vaccine-boarding-daycare-guide',
    ],
    internalLinks: [
      { phrase: 'boarding vaccines', slug: 'bordetella-vaccine-boarding-daycare-guide' },
      { phrase: 'medical profile for boarder', slug: 'one-click-medical-profile-pet-boarder' },
      { phrase: 'pet sitter instructions', slug: 'pet-sitter-instructions-medical-emergency-info' },
    ],
  },
  {
    num: 108,
    slug: 'cargo-travel-stress-safe-large-dogs',
    title: 'The Stress of Cargo Travel: Is It Safe for Large Dogs?',
    category: 'pet-travel',
    excerpt:
      'Cargo holds are pressurized and climate-controlled on most commercial flights, but brachycephalic breeds, seniors, and anxious dogs face higher risk  -  IATA crates and no sedation are standard.',
    tags: ['pet cargo', 'large dog travel', 'airline cargo', 'IATA crate', 'flight safety'],
    facts: {
      destinations: ['United States', 'International'],
      lineItems: [
        { item: 'Cargo booking fee (one-way, large dog)', cost: '$200-$600' },
        { item: 'IATA CR82 reinforced crate', cost: '$250-$600' },
        { item: 'Fit-to-fly health certificate', cost: '$75-$200' },
      ],
      requirements: [
        'Rigid IATA-compliant crate with ventilation on 3 sides',
        'Water bowl and absorbent bedding (no straw)',
        'Acclimation to crate 2+ weeks',
      ],
      timeline: [
        'Book cargo slot early  -  limited per flight',
        'Avoid summer midday departures when possible',
        'Arrive 3-4 hours before flight for acceptance',
      ],
      regulations: [
        'Airlines embargo snub-nosed breeds in cargo',
        'Temperature restrictions above 85°F or below 45°F at any leg',
        'Sedation discouraged by AVMA and airlines',
      ],
      checklistItems: ['Live animal labels on crate', 'Recent photo of pet', 'Shipper emergency contact on crate'],
      risks: ['Dehydration on tarmac delays', 'Escape from damaged crate', 'Stress cardiomyopathy in anxious dogs'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'brachycephalic-breeds-cargo-travel-ban',
        'international-pet-travel-health-certificate-guide',
        'pet-emergency-information-card-guide',
        'traveling-with-pets-health-documents-checklist',
      ],
    },
    relatedSlugs: [
      'flying-domestically-dog-2026-airline-rules-carrier-sizes',
      'pet-shipping-companies-cost-why-need-one',
      'sedating-pet-air-travel-vets-recommend-against',
      'brachycephalic-breeds-cargo-travel-ban',
    ],
    internalLinks: [
      { phrase: 'brachycephalic cargo ban', slug: 'brachycephalic-breeds-cargo-travel-ban' },
      { phrase: 'pet shipping companies', slug: 'pet-shipping-companies-cost-why-need-one' },
      { phrase: 'sedation risks', slug: 'sedating-pet-air-travel-vets-recommend-against' },
    ],
  },
  {
    num: 109,
    slug: 'pet-relocation-scams-verify-safe-transport',
    title: 'Pet Relocation Scams: How to Verify a Safe Transport Service',
    category: 'pet-travel',
    excerpt:
      'Fake pet shippers demand deposits then vanish  -  verify IPATA membership, USDA registration, and a physical address before paying; never wire money to unsolicited brokers.',
    tags: ['pet scam', 'pet relocation fraud', 'IPATA', 'verify transporter', 'moving safety'],
    facts: {
      destinations: ['United States', 'International'],
      lineItems: [
        { item: 'Legitimate door-to-door quote', cost: '$1,500-$8,000' },
        { item: 'Typical scam deposit demand', cost: '$500-$2,000 (lost)' },
        { item: 'USDA broker verification', cost: '$0' },
      ],
      requirements: [
        'Written contract with refund policy',
        'USDA carrier or broker license number',
        'References from recent international moves',
      ],
      timeline: [
        'Week 1: collect 3 quotes from IPATA members',
        'Week 2: video call facility tour',
        'Never pay 100% upfront  -  staged payments tied to milestones',
      ],
      regulations: [
        'USDA APHIS regulates commercial pet transport',
        'IPATA code of ethics for member companies',
      ],
      checklistItems: ['Check BBB and Google reviews', 'Reverse-image search website photos', 'Confirm airline awb numbers'],
      risks: ['Ghost brokers on social media', 'Puppy mill tie-ins disguised as relocation', 'Pet held hostage for extra fees'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'international-pet-travel-health-certificate-guide',
        'cross-country-move-pet-records-guide',
        'organize-pet-medical-records-online',
        'pet-emergency-information-card-guide',
      ],
    },
    relatedSlugs: [
      'pet-shipping-companies-cost-why-need-one',
      'moving-eu-pet-2026-rabies-titer-microchip-guide',
      'usda-health-certificate-pet-travel-timeline-fees',
      'cross-country-move-pet-records-guide',
    ],
    internalLinks: [
      { phrase: 'pet shipping costs', slug: 'pet-shipping-companies-cost-why-need-one' },
      { phrase: 'USDA health certificate', slug: 'usda-health-certificate-pet-travel-timeline-fees' },
      { phrase: 'cross-country move records', slug: 'cross-country-move-pet-records-guide' },
    ],
  },
  {
    num: 110,
    slug: 'flying-canada-dog-border-rules-cbsa-checks',
    title: 'Flying to Canada with a Dog: Border Rules and CBSA Checks',
    category: 'pet-travel',
    excerpt:
      'Canada accepts dogs 8+ months with current rabies certificate  -  puppies under 8 months need additional import permits; CBSA may inspect at first port of entry.',
    tags: ['Canada pet travel', 'CBSA', 'rabies certificate', 'border crossing', 'import rules'],
    facts: {
      destinations: ['Canada'],
      lineItems: [
        { item: 'Rabies vaccine', cost: '$20-$40' },
        { item: 'Health certificate (if required)', cost: '$75-$200' },
        { item: 'Airline in-cabin/cargo fee', cost: '$100-$400' },
      ],
      requirements: [
        'Rabies vaccination certificate with microchip or tattoo ID',
        'Dog appears healthy at inspection',
        'Puppies under 8 months: commercial import rules may apply',
      ],
      timeline: [
        'Before flight: confirm airline + CBSA requirements',
        'Arrival: CBSA agriculture inspection',
        'Return to US: CDC dog import form if applicable',
      ],
      regulations: [
        'CFIA oversees animal import; CBSA conducts border inspection',
        'Banned breeds in Ontario (Pit Bull-type)  -  research province',
        'Service dogs have separate documentation path',
      ],
      checklistItems: ['Rabies cert in English or French', 'Microchip matches paperwork', 'Leash and cleanup supplies'],
      risks: ['Denied entry without valid rabies proof', 'Provincial breed bans', 'Winter cargo embargoes'],
      year: 2026,
      region: 'Canada',
      legacySlugs: [
        'international-pet-travel-health-certificate-guide',
        'traveling-with-pets-health-documents-checklist',
        'microchip-registration-guide-dogs-cats',
        'organize-pet-medical-records-online',
      ],
    },
    relatedSlugs: [
      'traveling-mexico-dog-senasica-requirements-2026',
      'flying-domestically-dog-2026-airline-rules-carrier-sizes',
      'usda-health-certificate-pet-travel-timeline-fees',
      'international-pet-travel-health-certificate-guide',
    ],
    internalLinks: [
      { phrase: 'international travel guide', slug: 'international-pet-travel-health-certificate-guide' },
      { phrase: 'Mexico travel requirements', slug: 'traveling-mexico-dog-senasica-requirements-2026' },
      { phrase: 'travel documents', slug: 'traveling-with-pets-health-documents-checklist' },
    ],
  },
  {
    num: 111,
    slug: 'esa-vs-service-dog-travel-rules-airlines',
    title: 'ESA vs. Service Dog Travel Rules: What Airlines Actually Require',
    category: 'pet-travel',
    excerpt:
      'Since 2021 DOT rules, emotional support animals fly as pets with fees  -  only task-trained service dogs get cabin access free with DOT service animal form and behavior standards.',
    tags: ['ESA', 'service dog', 'DOT rules', 'airline policy', 'ADA travel'],
    facts: {
      destinations: ['United States'],
      lineItems: [
        { item: 'In-cabin pet fee (ESA treated as pet)', cost: '$100-$200' },
        { item: 'Service dog: no pet fee', cost: '$0' },
        { item: 'DOT Service Animal Air Transportation Form', cost: '$0' },
      ],
      requirements: [
        'Service dog: trained to perform disability-related tasks',
        'DOT form submitted 48 hours before flight (if required)',
        'ESA: same carrier/vaccine rules as pets',
      ],
      timeline: [
        'Book pet reservation for ESA',
        'Service dog: complete DOT form with trainer/handler attestation',
        'Airport: dog must remain controlled at all times',
      ],
      regulations: [
        'DOT Part 382  -  service animals limited to dogs (with some psychiatric SD exceptions)',
        'Airlines may deny untrained or aggressive animals',
        'Hotels follow ADA for service dogs only  -  not ESA',
      ],
      checklistItems: ['Vaccination records', 'Harness identifying service dog (optional but helpful)', 'Potty relief before security'],
      risks: ['Misrepresentation fines on some airlines', 'ESA denied boarding without pet reservation', 'International destinations may not recognize US service dog rules'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'traveling-with-pets-health-documents-checklist',
        'flying-domestically-dog-2026-airline-rules-carrier-sizes',
        'pet-emergency-information-card-guide',
        'organize-pet-medical-records-online',
      ],
    },
    relatedSlugs: [
      'flying-domestically-dog-2026-airline-rules-carrier-sizes',
      'hotel-pet-policies-2026-marriott-hilton-boutique-fees',
      'best-emotional-support-animal-breeds-documentation',
      'traveling-with-pets-health-documents-checklist',
    ],
    internalLinks: [
      { phrase: 'domestic dog airline rules', slug: 'flying-domestically-dog-2026-airline-rules-carrier-sizes' },
      { phrase: 'hotel pet policies', slug: 'hotel-pet-policies-2026-marriott-hilton-boutique-fees' },
      { phrase: 'travel documents', slug: 'traveling-with-pets-health-documents-checklist' },
    ],
  },
  {
    num: 112,
    slug: 'road-tripping-cats-litter-box-anxiety-meds',
    title: 'Road Tripping with Cats: Litter Box Logistics and Anxiety Meds',
    category: 'pet-travel',
    excerpt:
      'Use a disposable aluminum tray or portable litter box in the hotel bathroom; gabapentin or pheromone sprays can ease car anxiety  -  never let cats roam loose in the vehicle.',
    tags: ['road trip cat', 'travel litter box', 'cat anxiety', 'gabapentin', 'car travel'],
    facts: {
      destinations: ['United States interstate'],
      lineItems: [
        { item: 'Disposable litter trays (pack)', cost: '$10-$25' },
        { item: 'Gabapentin Rx consult', cost: '$50-$100' },
        { item: 'Pheromone spray (Feliway)', cost: '$20-$35' },
      ],
      requirements: [
        'Hard-sided or secured soft carrier while driving',
        'Litter, scoop, and waste bags in car',
        'Harness + leash for rest-stop breaks only',
      ],
      timeline: [
        '2 weeks: short car rides with treats',
        'Vet visit: discuss anti-nausea if vomiting',
        'Every 2-3 hours: offer litter in parked car',
      ],
      regulations: [
        'Hotels: confirm cat policy and fee',
        'Some states require rabies certificate for cats',
      ],
      checklistItems: ['Favorite blanket in carrier', 'Wet food for hydration', 'Paper towels for accidents'],
      risks: ['Heatstroke if left in car', 'Escape at rest stops', 'Urinary blockage from withholding litter access'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'flying-with-cats-health-documents-checklist',
        'traveling-with-pets-health-documents-checklist',
        'pet-emergency-information-card-guide',
        'organize-pet-medical-records-online',
      ],
    },
    relatedSlugs: [
      'flying-cat-cabin-tsa-gabapentin-carrier-tips',
      'sedating-pet-air-travel-vets-recommend-against',
      'pet-medical-emergency-road-trip',
      'flying-with-cats-health-documents-checklist',
    ],
    internalLinks: [
      { phrase: 'flying with cats', slug: 'flying-cat-cabin-tsa-gabapentin-carrier-tips' },
      { phrase: 'road trip emergencies', slug: 'pet-medical-emergency-road-trip' },
      { phrase: 'travel documents', slug: 'traveling-with-pets-health-documents-checklist' },
    ],
  },
  {
    num: 113,
    slug: 'sedating-pet-air-travel-vets-recommend-against',
    title: 'Sedating a Pet for Air Travel: Why Most Vets Recommend Against It',
    category: 'pet-travel',
    excerpt:
      'Acepromazine and over-the-counter antihistamines depress breathing and balance  -  AVMA and airlines warn sedation increases aspiration and cardiovascular risk at altitude.',
    tags: ['pet sedation', 'air travel', 'acepromazine', 'AVMA', 'flight safety'],
    facts: {
      destinations: ['United States', 'International'],
      lineItems: [
        { item: 'Behavior consult (alternative to sedation)', cost: '$75-$150' },
        { item: 'Gabapentin (sometimes prescribed)', cost: '$15-$40' },
        { item: 'Carrier training tools', cost: '$20-$60' },
      ],
      requirements: [
        'Airline may refuse sedated animals',
        'Vet must document fitness to fly without sedation',
        'Acclimation training preferred over drugs',
      ],
      timeline: [
        '4-8 weeks: desensitize to carrier and car sounds',
        'Trial any prescribed anxiolytic at home first',
        'Travel day: exercise before flight, skip heavy sedation',
      ],
      regulations: [
        'IATA discourages sedation unless medically necessary',
        'Some countries require alert animal at customs inspection',
      ],
      checklistItems: ['Calming pheromones', 'Familiar toy (no squeakers)', 'Vet letter if medical exception'],
      risks: ['Respiratory arrest in brachycephalic breeds', 'Lower blood pressure at cabin altitude', 'Delayed recovery causing missed connections'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'flying-with-cats-health-documents-checklist',
        'brachycephalic-breeds-cargo-travel-ban',
        'pet-emergency-information-card-guide',
        'traveling-with-pets-health-documents-checklist',
      ],
    },
    relatedSlugs: [
      'flying-cat-cabin-tsa-gabapentin-carrier-tips',
      'cargo-travel-stress-safe-large-dogs',
      'flying-domestically-dog-2026-airline-rules-carrier-sizes',
      'brachycephalic-breeds-cargo-travel-ban',
    ],
    internalLinks: [
      { phrase: 'cat cabin travel tips', slug: 'flying-cat-cabin-tsa-gabapentin-carrier-tips' },
      { phrase: 'cargo travel safety', slug: 'cargo-travel-stress-safe-large-dogs' },
      { phrase: 'brachycephalic ban', slug: 'brachycephalic-breeds-cargo-travel-ban' },
    ],
  },
  {
    num: 114,
    slug: 'one-click-medical-profile-pet-boarder',
    title: 'Creating a One-Click Medical Profile for Your Pet Boarder',
    category: 'pet-travel',
    excerpt:
      'Boarders need instant access to allergies, meds, vet authorization, and emergency contacts  -  a shareable digital profile replaces scattered texts and sticky notes.',
    tags: ['pet boarder', 'medical profile', 'shareable records', 'boarding handoff', 'digital care'],
    facts: {
      destinations: ['United States'],
      lineItems: [
        { item: 'Pet health app (annual)', cost: '$0-$120' },
        { item: 'QR collar tag (optional)', cost: '$15-$35' },
        { item: 'Printed backup card', cost: '$0-$10' },
      ],
      requirements: [
        'Medication photos with dosing schedule',
        'Authorized emergency vet and spending limit',
        'Vaccine PDFs with expiration dates',
      ],
      timeline: [
        'Day 1: compile records into one folder',
        'Day 2: generate read-only share link',
        'Post-stay: revoke boarder access',
      ],
      regulations: [
        'Boarding facilities must log medication administration in many states',
        'Controlled substances need written instructions',
      ],
      checklistItems: ['Feeding measured portions labeled', 'Behavior triggers documented', 'Insurance claim contact'],
      risks: ['Outdated link after app update', 'Boarder cannot open link offline', 'Wrong pet profile in multi-pet homes'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'organize-pet-medical-records-online',
        'pet-sitter-instructions-medical-emergency-info',
        'pet-emergency-information-card-guide',
        'bordetella-vaccine-boarding-daycare-guide',
      ],
    },
    relatedSlugs: [
      'create-shareable-digital-emergency-pet-passport',
      'luxury-boarding-facility-health-requirements',
      'leaving-dog-rover-sitter-digital-handoff',
      'organize-pet-medical-records-online',
    ],
    internalLinks: [
      { phrase: 'digital emergency passport', slug: 'create-shareable-digital-emergency-pet-passport' },
      { phrase: 'organize medical records', slug: 'organize-pet-medical-records-online' },
      { phrase: 'pet sitter instructions', slug: 'pet-sitter-instructions-medical-emergency-info' },
    ],
  },
  {
    num: 115,
    slug: 'traveling-diabetic-pets-insulin-syringes',
    title: 'Traveling with Diabetic Pets: Storing Insulin and Syringes on the Go',
    category: 'pet-travel',
    excerpt:
      'Insulin stays potent in a FRIO wallet or insulated case at 36-46°F  -  never freeze; carry twice the syringes needed and a glucose curve log for timezone-shifted dosing.',
    tags: ['diabetic pet travel', 'insulin storage', 'FRIO wallet', 'syringes TSA', 'chronic care'],
    facts: {
      destinations: ['United States', 'International'],
      lineItems: [
        { item: 'FRIO insulin cooling wallet', cost: '$25-$45' },
        { item: 'Portable glucose meter', cost: '$40-$80' },
        { item: 'Extra insulin vial + syringes', cost: '$100-$250' },
      ],
      requirements: [
        'Letter from vet for syringes and insulin in carry-on',
        'Sharps container for disposal',
        'Consistent feeding schedule across time zones',
      ],
      timeline: [
        'Pre-trip: vet adjusts dosing plan for travel days',
        'Flight: insulin in carry-on never checked baggage',
        'Daily: log glucose at same relative times',
      ],
      regulations: [
        'TSA allows insulin and syringes with documentation',
        'Some countries restrict insulin import quantities',
      ],
      checklistItems: ['Honey or glucose gel for hypoglycemia', 'Emergency vet list at destination', 'Cool pack backups'],
      risks: ['Frozen insulin loses potency', 'Missed meal → hypoglycemia', 'Heat degradation in parked car'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'chronic-condition-pet-record-system',
        'organize-pet-medical-records-online',
        'pet-emergency-information-card-guide',
        'traveling-with-pets-health-documents-checklist',
      ],
    },
    relatedSlugs: [
      'create-shareable-digital-emergency-pet-passport',
      'pet-medical-emergency-road-trip',
      'one-click-medical-profile-pet-boarder',
      'chronic-condition-pet-record-system',
    ],
    internalLinks: [
      { phrase: 'chronic condition records', slug: 'chronic-condition-pet-record-system' },
      { phrase: 'digital emergency passport', slug: 'create-shareable-digital-emergency-pet-passport' },
      { phrase: 'travel emergencies', slug: 'pet-medical-emergency-road-trip' },
    ],
  },
  {
    num: 116,
    slug: 'pet-emergency-kit-hurricanes-wildfires',
    title: 'Preparing a Pet Emergency Kit for Hurricanes and Wildfires',
    category: 'pet-travel',
    excerpt:
      'Evacuation kits need 7+ days of meds, sealed records, microchip proof, and a go-bag per pet  -  FEMA recommends including photos and a trusted neighbor contact before storm season.',
    tags: ['pet evacuation', 'hurricane prep', 'wildfire', 'emergency kit', 'disaster planning'],
    facts: {
      destinations: ['United States Gulf Coast', 'Wildfire-prone West'],
      lineItems: [
        { item: 'Evacuation go-bag per pet', cost: '$50-$150' },
        { item: '7-day medication supply', cost: 'Varies' },
        { item: 'Pet-friendly hotel deposit reserve', cost: '$200-$500' },
      ],
      requirements: [
        'Collar with ID and rabies tag',
        'Waterproof document pouch',
        'Carrier or crate labeled with contact info',
      ],
      timeline: [
        'May-June: assemble kit before hurricane season',
        'Watch alerts: evacuate early with pets  -  shelters fill',
        'Post-event: update microchip address if displaced',
      ],
      regulations: [
        'Red Cross shelters often cannot take pets  -  locate pet-friendly hotels',
        'Some counties issue pet evacuation transport',
      ],
      checklistItems: ['3-7 days food and water', 'Litter or poop bags', 'Calming aids and familiar toy'],
      risks: ['Left behind in mandatory evacuations', 'Smoke inhalation in wildfires', 'Contaminated floodwater exposure'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'pet-emergency-information-card-guide',
        'organize-pet-medical-records-online',
        'after-hours-emergency-vet-information-sheet',
        'microchip-registration-guide-dogs-cats',
      ],
    },
    relatedSlugs: [
      'pet-first-aid-kit-hiking',
      'create-shareable-digital-emergency-pet-passport',
      'pet-medical-emergency-road-trip',
      'pet-emergency-information-card-guide',
    ],
    internalLinks: [
      { phrase: 'emergency information card', slug: 'pet-emergency-information-card-guide' },
      { phrase: 'digital emergency passport', slug: 'create-shareable-digital-emergency-pet-passport' },
      { phrase: 'first-aid kit hiking', slug: 'pet-first-aid-kit-hiking' },
    ],
  },
  {
    num: 117,
    slug: 'pet-first-aid-kit-hiking',
    title: 'What to Pack in a Pet First-Aid Kit for Hiking',
    category: 'pet-travel',
    excerpt:
      'Trail kits need tweezers for ticks, vet wrap, saline flush, and booties for paw cuts  -  know your dog\'s weight for Benadryl dosing only after vet approval.',
    tags: ['pet first aid', 'hiking with dogs', 'trail safety', 'tick removal', 'outdoor kit'],
    facts: {
      destinations: ['United States trails', 'National parks'],
      lineItems: [
        { item: 'Compact pet first-aid kit', cost: '$25-$60' },
        { item: 'Dog booties (set of 4)', cost: '$20-$50' },
        { item: 'Collapsible water bowl', cost: '$10-$20' },
      ],
      requirements: [
        'Tweezers or tick tool',
        'Gauze, vet wrap, medical tape',
        'Digital copy of vet phone and records',
      ],
      timeline: [
        'Pre-hike: check paw pads and hydration',
        'On trail: rest in shade every 30-45 minutes in heat',
        'Post-hike: tick check and monitor lameness',
      ],
      regulations: [
        'Leash laws on most public trails',
        'Leave No Trace includes packing out waste',
      ],
      checklistItems: ['Benadryl dosing chart from vet', 'Styptic powder for nail breaks', 'Emergency blanket'],
      risks: ['Snakebite  -  do not suck venom', 'Heatstroke on exposed trails', 'Foxtail grass in ears and paws'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'pet-emergency-information-card-guide',
        'after-hours-emergency-vet-information-sheet',
        'traveling-with-pets-health-documents-checklist',
        'organize-pet-medical-records-online',
      ],
    },
    relatedSlugs: [
      'camping-dogs-flea-tick-leptospirosis-protocols',
      'pet-medical-emergency-road-trip',
      'pet-emergency-kit-hurricanes-wildfires',
      'pet-emergency-information-card-guide',
    ],
    internalLinks: [
      { phrase: 'camping protocols', slug: 'camping-dogs-flea-tick-leptospirosis-protocols' },
      { phrase: 'road trip emergencies', slug: 'pet-medical-emergency-road-trip' },
      { phrase: 'emergency card', slug: 'pet-emergency-information-card-guide' },
    ],
  },
  {
    num: 118,
    slug: 'crossing-state-lines-horses-livestock-coggins-health-certs',
    title: 'Crossing State Lines with Horses and Livestock: Coggins and Health Certs',
    category: 'pet-travel',
    excerpt:
      'Interstate horse travel requires a negative Coggins (EIA) test within 12 months and a USDA health certificate within 30 days  -  brand inspections apply in Western states.',
    tags: ['horse travel', 'Coggins test', 'EIA', 'livestock health certificate', 'interstate'],
    facts: {
      destinations: ['United States interstate'],
      lineItems: [
        { item: 'Coggins (EIA) test', cost: '$40-$100' },
        { item: 'USDA health certificate (equine)', cost: '$75-$200' },
        { item: 'Brand inspection (where required)', cost: '$15-$50' },
      ],
      requirements: [
        'Negative Coggins within 12 months',
        'Health cert issued within 30 days of movement',
        'Permit for some states (e.g., California entry)',
      ],
      timeline: [
        '2-4 weeks before: schedule Coggins blood draw',
        'Within 30 days of travel: vet issues CVI',
        'At border: state ag inspector may check papers',
      ],
      regulations: [
        'USDA APHIS VS Form 7001 or eCVI',
        'Brand laws vary  -  Wyoming, Montana, etc.',
        'Vesicular stomatitis restrictions when outbreaks occur',
      ],
      checklistItems: ['Original Coggins paper', 'Emergency contact at destination stable', 'Halter with ID'],
      risks: ['Quarantine if paperwork expired', 'Disease outbreak movement bans', 'Heat stress in trailer'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'usda-health-certificate-pet-travel-timeline-fees',
        'international-pet-travel-health-certificate-guide',
        'organize-pet-medical-records-online',
        'traveling-with-pets-health-documents-checklist',
      ],
    },
    relatedSlugs: [
      'usda-health-certificate-pet-travel-timeline-fees',
      'cross-country-move-pet-records-guide',
      'pet-medical-emergency-road-trip',
      'international-pet-travel-health-certificate-guide',
    ],
    internalLinks: [
      { phrase: 'USDA health certificate', slug: 'usda-health-certificate-pet-travel-timeline-fees' },
      { phrase: 'cross-country move records', slug: 'cross-country-move-pet-records-guide' },
      { phrase: 'organize medical records', slug: 'organize-pet-medical-records-online' },
    ],
  },
  {
    num: 119,
    slug: 'sync-pet-microchip-digital-medical-record',
    title: "How to Sync Your Pet's Microchip to a Digital Medical Record",
    category: 'pet-travel',
    excerpt:
      'Register the chip with the manufacturer database and link it to your digital health profile  -  when scanners read the ID, reunification and ER access work faster.',
    tags: ['microchip sync', 'digital records', 'pet ID', 'registry', 'travel safety'],
    facts: {
      destinations: ['United States', 'International'],
      lineItems: [
        { item: 'Microchip registration (lifetime)', cost: '$0-$25' },
        { item: 'Premium registry with alerts', cost: '$15-$50/year' },
        { item: 'Digital health app', cost: '$0-$120/year' },
      ],
      requirements: [
        '15-digit ISO microchip number from vet scan',
        'Current owner phone and travel address',
        'Link to vaccination and medical PDFs',
      ],
      timeline: [
        'Day 1: scan chip at vet to confirm number',
        'Day 2: update manufacturer registry online',
        'Day 3: attach medical record share link to profile',
      ],
      regulations: [
        'EU travel requires chip implanted before rabies vaccine',
        'Some registries charge to transfer ownership',
      ],
      checklistItems: ['Annual registry login check', 'Backup email for alerts', 'Photo on file'],
      risks: ['Unregistered chip useless at shelter', 'Old owner info after move', 'Duplicate registries with conflicting data'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'microchip-registration-guide-dogs-cats',
        'organize-pet-medical-records-online',
        'create-shareable-digital-emergency-pet-passport',
        'international-pet-travel-health-certificate-guide',
      ],
    },
    relatedSlugs: [
      'moving-eu-pet-2026-rabies-titer-microchip-guide',
      'create-shareable-digital-emergency-pet-passport',
      'one-click-medical-profile-pet-boarder',
      'microchip-registration-guide-dogs-cats',
    ],
    internalLinks: [
      { phrase: 'microchip registration guide', slug: 'microchip-registration-guide-dogs-cats' },
      { phrase: 'digital emergency passport', slug: 'create-shareable-digital-emergency-pet-passport' },
      { phrase: 'EU microchip rules', slug: 'moving-eu-pet-2026-rabies-titer-microchip-guide' },
    ],
  },
  {
    num: 120,
    slug: 'five-minute-checklist-leaving-pet-neighbor',
    title: 'The 5-Minute Checklist Before Leaving Your Pet with a Neighbor',
    category: 'pet-travel',
    excerpt:
      'Before a quick trip, text your neighbor the vet number, feeding amounts, leash rules, and where the carrier lives  -  five minutes of prep prevents midnight panic calls.',
    tags: ['neighbor pet care', 'quick handoff', 'checklist', 'short trip', 'pet sitting'],
    facts: {
      destinations: ['United States'],
      lineItems: [
        { item: 'Printed one-page care sheet', cost: '$0' },
        { item: 'Spare key or lock code', cost: '$0-$30' },
        { item: 'Thank-you treat budget', cost: '$10-$25' },
      ],
      requirements: [
        'Emergency vet authorization in writing',
        'Exact feeding and medication instructions',
        'Your reachable phone and backup contact',
      ],
      timeline: [
        'Minute 1: confirm neighbor availability',
        'Minutes 2-3: walk through meds and quirks',
        'Minutes 4-5: share digital record link',
      ],
      regulations: [
        'Neighbor is not a licensed boarder  -  liability varies by state',
        'Homeowner insurance may cover incidental pet injury',
      ],
      checklistItems: ['Food pre-portioned', 'Leash by door', 'Litter or potty schedule'],
      risks: ['Neighbor gives forbidden human food', 'Dog bolts when door opens', 'No vet authorization delays ER care'],
      year: 2026,
      region: 'United States',
      legacySlugs: [
        'pet-sitter-instructions-medical-emergency-info',
        'pet-emergency-information-card-guide',
        'dog-feeding-schedule-walk-tracker',
        'organize-pet-medical-records-online',
      ],
    },
    relatedSlugs: [
      'leaving-dog-rover-sitter-digital-handoff',
      'essential-documents-dog-walker-before-work',
      'one-click-medical-profile-pet-boarder',
      'pet-sitter-instructions-medical-emergency-info',
    ],
    internalLinks: [
      { phrase: 'Rover digital handoff', slug: 'leaving-dog-rover-sitter-digital-handoff' },
      { phrase: 'dog walker documents', slug: 'essential-documents-dog-walker-before-work' },
      { phrase: 'pet sitter instructions', slug: 'pet-sitter-instructions-medical-emergency-info' },
    ],
  },
];
