/**
 * Curated hero + inline image pairs per dominance blog slug.
 * Every mapping ties to the closest available local asset.
 */
export const DOMINANCE_IMAGE_BY_SLUG = {
  // Engine 1: vet cost & finance
  'how-much-does-vet-visit-cost-2026': { hero: 'blog-pet-records.webp', inline: 'blog-vet-bill-organizer.webp' },
  'decoding-vet-bill-cbc-chem-17': { hero: 'blog-vet-bill-organizer.webp', inline: 'blog-pet-records.webp' },
  'dog-teeth-cleaning-costs-dental-surgery': { hero: 'blog-dog-dental-care.webp', inline: 'blog-vet-bill-organizer.webp' },
  'mri-vs-x-ray-dogs-costs': { hero: 'blog-pet-records.webp', inline: 'blog-vet-bill-organizer.webp' },
  'emergency-vet-costs-urgent-care': { hero: 'blog-emergency-passport.webp', inline: 'blog-vet-bill-organizer.webp' },
  'spay-neuter-dog-cost-2026': { hero: 'blog-puppy-checklist.webp', inline: 'blog-vet-bill-organizer.webp' },
  'tplo-surgery-cost-torn-acl-dogs': { hero: 'blog-labrador-joint-care.webp', inline: 'blog-vet-bill-organizer.webp' },
  'cat-bloodwork-cost-overcharged': { hero: 'blog-cat-health-records.webp', inline: 'blog-vet-bill-organizer.webp' },
  'pet-insurance-vs-out-of-pocket-2026': { hero: 'blog-vet-bill-organizer.webp', inline: 'blog-pet-records.webp' },
  'hidden-costs-vet-invoices': { hero: 'blog-vet-bill-organizer.webp', inline: 'blog-pet-records-timeline.webp' },
  'how-to-negotiate-vet-bills-payment-plans': { hero: 'blog-vet-bill-organizer.webp', inline: 'blog-emergency-passport.webp' },
  'euthanasia-cremation-cost-end-of-life': { hero: 'blog-senior-dog.webp', inline: 'blog-pet-records-timeline.webp' },
  'heartworm-treatment-cost-prevention': { hero: 'blog-heartworm-prevention.webp', inline: 'blog-vet-bill-organizer.webp' },
  'parvovirus-treatment-costs-survival-rates': { hero: 'blog-puppy-vaccination.webp', inline: 'blog-emergency-passport.webp' },
  'dog-allergy-treatment-costs-cytopoint-apoquel': { hero: 'blog-pet-allergy-tracker.webp', inline: 'blog-vet-bill-organizer.webp' },
  'feline-leukemia-testing-vaccine-costs': { hero: 'blog-cat-vaccination.webp', inline: 'blog-cat-health-records.webp' },
  'fecal-float-test-cost-why-vets-push-it': { hero: 'blog-flea-tick-prevention.webp', inline: 'blog-vet-bill-organizer.webp' },
  'dog-tumor-removal-oncology-costs': { hero: 'blog-pet-records.webp', inline: 'blog-vet-bill-organizer.webp' },
  'iv-fluids-cats-kidney-disease-costs': { hero: 'blog-senior-cat-care.webp', inline: 'blog-medication-reminder.webp' },
  'why-emergency-vets-cost-3x-more': { hero: 'blog-emergency-passport.webp', inline: 'blog-vet-bill-organizer.webp' },
  'veterinary-prescriptions-overpaying-pet-meds': { hero: 'blog-medication-reminder.webp', inline: 'blog-vet-bill-organizer.webp' },
  'french-bulldog-surgery-costs-boas-ivdd': { hero: 'blog-french-bulldog-health.webp', inline: 'blog-vet-bill-organizer.webp' },
  'ultrasound-costs-dogs-cats': { hero: 'blog-cat-health-records.webp', inline: 'blog-pet-records.webp' },
  'cat-uti-blockage-treatment-costs': { hero: 'blog-senior-cat-care.webp', inline: 'blog-vet-bill-organizer.webp' },
  'rabies-titer-test-international-travel-cost': { hero: 'blog-microchip-registration.webp', inline: 'blog-travel-pets.webp' },
  'diabetes-treatment-cost-dogs-cats': { hero: 'blog-medication-reminder.webp', inline: 'blog-vet-bill-organizer.webp' },
  'snake-bite-vet-bills-antivenom-costs': { hero: 'blog-emergency-passport.webp', inline: 'blog-vet-bill-organizer.webp' },
  'dog-toxic-ingestion-treatment-costs': { hero: 'blog-emergency-passport.webp', inline: 'blog-puppy-checklist.webp' },
  'cruciate-ligament-tear-conservative-vs-surgery-costs': { hero: 'blog-labrador-joint-care.webp', inline: 'blog-vet-bill-organizer.webp' },
  'wellness-plans-banfield-vca-independent-vets': { hero: 'blog-vet-bill-organizer.webp', inline: 'blog-dog-vaccination-guide.webp' },

  // Engine 2: breed & lifestyle
  'golden-retriever-first-year-cost-guide': { hero: 'blog-labrador-joint-care.webp', inline: 'blog-puppy-checklist.webp' },
  'best-apartment-dogs-9-to-5-workers': { hero: 'blog-daily-checkin.webp', inline: 'blog-puppy-checklist.webp' },
  'low-maintenance-pets-busy-professionals-2026': { hero: 'blog-life-stage-care.webp', inline: 'blog-daily-checkin.webp' },
  'hypoallergenic-dogs-fact-vs-fiction': { hero: 'blog-pet-allergy-tracker.webp', inline: 'blog-poodle-grooming-health.webp' },
  'maine-coon-cost-guide-purchase-food-vet': { hero: 'blog-maine-coon-health.webp', inline: 'blog-cat-health-records.webp' },
  'french-bulldog-vet-costs-reality-check': { hero: 'blog-french-bulldog-health.webp', inline: 'blog-vet-bill-organizer.webp' },
  'best-cat-breeds-for-dog-people': { hero: 'blog-cat-health-records.webp', inline: 'blog-siamese-cat-wellness.webp' },
  'shelter-dog-vs-breeder-puppy-financial-differences': { hero: 'blog-puppy-checklist.webp', inline: 'blog-vet-bill-organizer.webp' },
  'high-energy-dogs-marathon-running-partners': { hero: 'blog-german-shepherd-hip.webp', inline: 'blog-dog-weight-tracker.webp' },
  'best-guard-dogs-families-small-children': { hero: 'blog-german-shepherd-hip.webp', inline: 'blog-puppy-checklist.webp' },
  'most-expensive-dog-breeds-to-insure': { hero: 'blog-vet-bill-organizer.webp', inline: 'blog-french-bulldog-health.webp' },
  'easiest-reptiles-beginners-setup-vet-costs': { hero: 'blog-snake-care.webp', inline: 'blog-exotic-pet-records.webp' },
  'sphynx-cat-care-costs-lotions-heart-scans': { hero: 'blog-cat-health-records.webp', inline: 'blog-maine-coon-health.webp' },
  'dog-breeds-most-prone-to-cancer': { hero: 'blog-senior-dog.webp', inline: 'blog-pet-records-timeline.webp' },
  'best-emotional-support-animal-breeds-documentation': { hero: 'blog-life-stage-care.webp', inline: 'blog-pet-records.webp' },
  'true-cost-owning-parrot-50-year-commitment': { hero: 'blog-bird-care.webp', inline: 'blog-vet-bill-organizer.webp' },
  'doodle-breeds-grooming-costs-health-quirks': { hero: 'blog-poodle-grooming-health.webp', inline: 'blog-pet-allergy-tracker.webp' },
  'working-breeds-apartment-husky-city-life': { hero: 'blog-german-shepherd-hip.webp', inline: 'blog-daily-checkin.webp' },
  'bengal-cat-ownership-energy-diet-vet-costs': { hero: 'blog-siamese-cat-wellness.webp', inline: 'blog-cat-health-records.webp' },
  'brachycephalic-breeds-cargo-travel-ban': { hero: 'blog-french-bulldog-health.webp', inline: 'blog-travel-pets.webp' },
  'senior-rescue-dogs-adoption-costs-rewards': { hero: 'blog-senior-dog.webp', inline: 'blog-puppy-checklist.webp' },
  'dog-breeds-that-shed-least-grooming-costs': { hero: 'blog-poodle-grooming-health.webp', inline: 'blog-vet-bill-organizer.webp' },
  'large-breed-vs-giant-breed-great-dane-feeding-costs': { hero: 'blog-dog-weight-tracker.webp', inline: 'blog-puppy-checklist.webp' },
  'most-vocal-cat-breeds-siamese-bengal-oriental': { hero: 'blog-siamese-cat-wellness.webp', inline: 'blog-maine-coon-health.webp' },
  'apartment-friendly-cats-no-outdoor-access': { hero: 'blog-cat-health-records.webp', inline: 'blog-new-kitten-checklist.webp' },
  'dog-breeds-separation-anxiety-daycare-costs': { hero: 'blog-pet-boarding.webp', inline: 'blog-daily-checkin.webp' },
  'best-pets-seniors-limited-mobility': { hero: 'blog-senior-dog.webp', inline: 'blog-senior-cat-care.webp' },
  'corgi-spine-health-ivdd-ramps-reality': { hero: 'blog-dachshund-mobility.webp', inline: 'blog-labrador-joint-care.webp' },
  'male-vs-female-puppy-health-behavior-trends': { hero: 'blog-puppy-checklist.webp', inline: 'blog-puppy-vaccination.webp' },
  'petclues-lifestyle-quiz-breed-fit': { hero: 'blog-life-stage-care.webp', inline: 'blog-best-pet-health-app.webp' },

  // Engine 3: symptom triage
  'dog-throwing-up-yellow-bile-morning': { hero: 'blog-dog-vaccination-guide.webp', inline: 'blog-emergency-passport.webp' },
  'cat-limping-front-leg-when-to-call-vet': { hero: 'blog-cat-health-records.webp', inline: 'blog-emergency-passport.webp' },
  'dog-diarrhea-mucus-blood-fasting-emergency': { hero: 'blog-emergency-passport.webp', inline: 'blog-dog-vaccination-guide.webp' },
  'reverse-sneezing-dogs-choking-allergies': { hero: 'blog-pet-allergy-tracker.webp', inline: 'blog-dog-vaccination-guide.webp' },
  'cat-bad-breath-dental-disease-stages': { hero: 'blog-dog-dental-care.webp', inline: 'blog-cat-health-records.webp' },
  'dog-panting-heavily-at-night': { hero: 'blog-senior-dog.webp', inline: 'blog-emergency-passport.webp' },
  'cat-not-drinking-water-kidney-failure': { hero: 'blog-senior-cat-care.webp', inline: 'blog-medication-reminder.webp' },
  'kennel-cough-symptoms-contagious-how-long': { hero: 'blog-dog-vaccination-guide.webp', inline: 'blog-pet-boarding.webp' },
  'dog-dragging-back-legs-ivdd-emergency': { hero: 'blog-dachshund-mobility.webp', inline: 'blog-emergency-passport.webp' },
  'dog-licking-paws-constantly-yeast-allergies': { hero: 'blog-pet-allergy-tracker.webp', inline: 'blog-dog-vaccination-guide.webp' },
  'cat-peeing-outside-litter-box-flutd': { hero: 'blog-senior-cat-care.webp', inline: 'blog-cat-health-records.webp' },
  'how-to-tell-if-dog-has-fever-without-thermometer': { hero: 'blog-dog-vaccination-guide.webp', inline: 'blog-emergency-passport.webp' },
  'lethargic-puppy-parvovirus-warning-signs': { hero: 'blog-puppy-vaccination.webp', inline: 'blog-emergency-passport.webp' },
  'dog-cloudy-eyes-nuclear-sclerosis-vs-cataracts': { hero: 'blog-senior-dog.webp', inline: 'blog-dog-vaccination-guide.webp' },
  'cat-vomiting-hairballs-gi-blockage': { hero: 'blog-cat-health-records.webp', inline: 'blog-emergency-passport.webp' },
  'dog-scooting-carpet-anal-glands-parasites': { hero: 'blog-flea-tick-prevention.webp', inline: 'blog-dog-vaccination-guide.webp' },
  'swollen-dog-ear-aural-hematoma': { hero: 'blog-dog-vaccination-guide.webp', inline: 'blog-emergency-passport.webp' },
  'pale-gums-dogs-capillary-refill-time': { hero: 'blog-emergency-passport.webp', inline: 'blog-dog-vaccination-guide.webp' },
  'feline-asthma-cough-vs-hairball': { hero: 'blog-cat-health-records.webp', inline: 'blog-senior-cat-care.webp' },
  'dog-drinking-too-much-water-cushings-diabetes-kidney': { hero: 'blog-dog-weight-tracker.webp', inline: 'blog-medication-reminder.webp' },
  'cat-losing-weight-eating-hyperthyroidism': { hero: 'blog-senior-cat-care.webp', inline: 'blog-cat-health-records.webp' },
  'dog-seizures-first-3-minutes-protocol': { hero: 'blog-emergency-passport.webp', inline: 'blog-medication-reminder.webp' },
  'hot-spots-dogs-home-remedies-vet-treatments': { hero: 'blog-pet-allergy-tracker.webp', inline: 'blog-dog-vaccination-guide.webp' },
  'cat-hiding-recognizing-pain': { hero: 'blog-cat-health-records.webp', inline: 'blog-senior-cat-care.webp' },
  'dog-shaking-trembling-toxic-shock': { hero: 'blog-emergency-passport.webp', inline: 'blog-pet-allergy-tracker.webp' },
  'ringworm-cats-symptoms-contagion-woods-lamp': { hero: 'blog-cat-health-records.webp', inline: 'blog-flea-tick-prevention.webp' },
  'tick-on-dog-removal-symptoms-to-track': { hero: 'blog-flea-tick-prevention.webp', inline: 'blog-emergency-passport.webp' },
  'cherry-eye-dogs-surgery-alternatives': { hero: 'blog-puppy-checklist.webp', inline: 'blog-dog-vaccination-guide.webp' },
  'cat-drooling-excessively-nausea-poison': { hero: 'blog-cat-health-records.webp', inline: 'blog-emergency-passport.webp' },
  'track-pet-symptoms-petclues-health-foresight-ai': { hero: 'blog-best-pet-health-app.webp', inline: 'blog-pet-records-timeline.webp' },

  // Engine 4: travel & passports
  'flying-domestically-dog-2026-airline-rules-carrier-sizes': { hero: 'blog-travel-pets.webp', inline: 'blog-pet-boarding.webp' },
  'moving-eu-pet-2026-rabies-titer-microchip-guide': { hero: 'blog-microchip-registration.webp', inline: 'blog-travel-pets.webp' },
  'moving-uk-dog-defra-regulations': { hero: 'blog-travel-pets.webp', inline: 'blog-microchip-registration.webp' },
  'create-shareable-digital-emergency-pet-passport': { hero: 'blog-emergency-passport.webp', inline: 'blog-pet-sitter-instructions.webp' },
  'leaving-dog-rover-sitter-digital-handoff': { hero: 'blog-pet-sitter-instructions.webp', inline: 'blog-emergency-passport.webp' },
  'flying-cat-cabin-tsa-gabapentin-carrier-tips': { hero: 'blog-flying-with-cats.webp', inline: 'blog-travel-pets.webp' },
  'pet-shipping-companies-cost-why-need-one': { hero: 'blog-travel-pets.webp', inline: 'blog-vet-bill-organizer.webp' },
  'usda-health-certificate-pet-travel-timeline-fees': { hero: 'blog-travel-pets.webp', inline: 'blog-microchip-registration.webp' },
  'pet-travel-hawaii-quarantine-laws': { hero: 'blog-travel-pets.webp', inline: 'blog-pet-boarding.webp' },
  'traveling-mexico-dog-senasica-requirements-2026': { hero: 'blog-travel-pets.webp', inline: 'blog-microchip-registration.webp' },
  'pet-medical-emergency-road-trip': { hero: 'blog-emergency-passport.webp', inline: 'blog-travel-pets.webp' },
  'essential-documents-dog-walker-before-work': { hero: 'blog-pet-sitter-instructions.webp', inline: 'blog-emergency-passport.webp' },
  'digital-vaccine-proof-doggy-daycare-boarding': { hero: 'blog-pet-boarding.webp', inline: 'blog-puppy-vaccination.webp' },
  'find-english-speaking-vet-abroad': { hero: 'blog-travel-pets.webp', inline: 'blog-emergency-passport.webp' },
  'hotel-pet-policies-2026-marriott-hilton-boutique-fees': { hero: 'blog-travel-pets.webp', inline: 'blog-pet-boarding.webp' },
  'camping-dogs-flea-tick-leptospirosis-protocols': { hero: 'blog-flea-tick-prevention.webp', inline: 'blog-travel-pets.webp' },
  'luxury-boarding-facility-health-requirements': { hero: 'blog-pet-boarding.webp', inline: 'blog-pet-sitter-instructions.webp' },
  'cargo-travel-stress-safe-large-dogs': { hero: 'blog-travel-pets.webp', inline: 'blog-german-shepherd-hip.webp' },
  'pet-relocation-scams-verify-safe-transport': { hero: 'blog-travel-pets.webp', inline: 'blog-vet-bill-organizer.webp' },
  'flying-canada-dog-border-rules-cbsa-checks': { hero: 'blog-travel-pets.webp', inline: 'blog-microchip-registration.webp' },
  'esa-vs-service-dog-travel-rules-airlines': { hero: 'blog-travel-pets.webp', inline: 'blog-pet-sitter-instructions.webp' },
  'road-tripping-cats-litter-box-anxiety-meds': { hero: 'blog-flying-with-cats.webp', inline: 'blog-travel-pets.webp' },
  'sedating-pet-air-travel-vets-recommend-against': { hero: 'blog-flying-with-cats.webp', inline: 'blog-emergency-passport.webp' },
  'one-click-medical-profile-pet-boarder': { hero: 'blog-pet-sitter-instructions.webp', inline: 'blog-emergency-passport.webp' },
  'traveling-diabetic-pets-insulin-syringes': { hero: 'blog-medication-reminder.webp', inline: 'blog-travel-pets.webp' },
  'pet-emergency-kit-hurricanes-wildfires': { hero: 'blog-emergency-passport.webp', inline: 'blog-travel-pets.webp' },
  'pet-first-aid-kit-hiking': { hero: 'blog-emergency-passport.webp', inline: 'blog-flea-tick-prevention.webp' },
  'crossing-state-lines-horses-livestock-coggins-health-certs': { hero: 'blog-travel-pets.webp', inline: 'blog-microchip-registration.webp' },
  'sync-pet-microchip-digital-medical-record': { hero: 'blog-microchip-registration.webp', inline: 'blog-pet-records-timeline.webp' },
  'five-minute-checklist-leaving-pet-neighbor': { hero: 'blog-pet-sitter-instructions.webp', inline: 'blog-emergency-passport.webp' },

  // Engine 5: pet tech & longevity
  'best-pet-tech-gadgets-2026-smart-feeders-ai-trackers': { hero: 'blog-best-pet-health-app.webp', inline: 'blog-daily-checkin.webp' },
  'apple-airtag-vs-fi-collar-vs-whistle-pet-tracker': { hero: 'blog-best-pet-health-app.webp', inline: 'blog-microchip-registration.webp' },
  'ai-diagnose-dog-future-veterinary-medicine': { hero: 'blog-best-pet-health-app.webp', inline: 'blog-pet-records.webp' },
  'cost-canine-longevity-supplements-rapamycin-diets': { hero: 'blog-senior-dog.webp', inline: 'blog-dog-weight-tracker.webp' },
  'smart-litter-boxes-worth-500-cat-uti-detection': { hero: 'blog-senior-cat-care.webp', inline: 'blog-best-pet-health-app.webp' },
  'wearable-tech-dogs-sleep-heart-rate-scratching': { hero: 'blog-best-pet-health-app.webp', inline: 'blog-dog-weight-tracker.webp' },
  'raw-vs-fresh-cooked-vs-kibble-2026-vet-consensus': { hero: 'blog-dog-weight-tracker.webp', inline: 'blog-daily-checkin.webp' },
  'microbiome-testing-pets-gut-health-dog-allergies': { hero: 'blog-pet-allergy-tracker.webp', inline: 'blog-best-pet-health-app.webp' },
  'automatic-cat-feeders-microchipped-multi-pet-homes': { hero: 'blog-cat-health-records.webp', inline: 'blog-best-pet-health-app.webp' },
  'cbd-dogs-arthritis-2026-clinical-studies-dosage': { hero: 'blog-senior-dog.webp', inline: 'blog-medication-reminder.webp' },
  'telehealth-pets-when-use-when-drive-er': { hero: 'blog-best-pet-health-app.webp', inline: 'blog-emergency-passport.webp' },
  'ai-decoding-veterinary-bills-saving-money': { hero: 'blog-vet-bill-organizer.webp', inline: 'blog-best-pet-health-app.webp' },
  'librela-solensia-monthly-injections-pet-arthritis': { hero: 'blog-senior-dog.webp', inline: 'blog-medication-reminder.webp' },
  'dna-testing-dogs-embark-vs-wisdom-panel-accuracy': { hero: 'blog-puppy-checklist.webp', inline: 'blog-best-pet-health-app.webp' },
  'at-home-urine-tests-cats-kidney-issues-early': { hero: 'blog-senior-cat-care.webp', inline: 'blog-cat-health-records.webp' },
  'subscription-pet-meds-chewy-petmed-vs-local-vets': { hero: 'blog-medication-reminder.webp', inline: 'blog-vet-bill-organizer.webp' },
  'chatgpt-understand-pet-bloodwork-results': { hero: 'blog-pet-records.webp', inline: 'blog-best-pet-health-app.webp' },
  'hydrotherapy-laser-therapy-senior-dogs-tech-help': { hero: 'blog-senior-dog.webp', inline: 'blog-labrador-joint-care.webp' },
  'smart-pet-doors-microchip-access-curfew': { hero: 'blog-microchip-registration.webp', inline: 'blog-best-pet-health-app.webp' },
  'pet-cameras-treat-dispensers-furbo-vs-wyze': { hero: 'blog-best-pet-health-app.webp', inline: 'blog-pet-sitter-instructions.webp' },
  'dental-water-additives-vs-brushing-plaque-removal': { hero: 'blog-dog-dental-care.webp', inline: 'blog-daily-checkin.webp' },
  'science-dog-goggles-rex-specs-hearing-protection': { hero: 'blog-dog-vaccination-guide.webp', inline: 'blog-best-pet-health-app.webp' },
  'alternative-therapies-acupuncture-chiropractic-pets': { hero: 'blog-senior-dog.webp', inline: 'blog-labrador-joint-care.webp' },
  'high-tech-aquariums-automated-dosing-monitoring': { hero: 'blog-exotic-pet-records.webp', inline: 'blog-best-pet-health-app.webp' },
  'air-purifiers-pet-dander-allergic-owners': { hero: 'blog-pet-allergy-tracker.webp', inline: 'blog-best-pet-health-app.webp' },
  'build-digital-living-archive-pet-life': { hero: 'blog-pet-records-timeline.webp', inline: 'blog-best-pet-health-app.webp' },
  'preventative-pet-care-shift-away-reactive-vet-visits': { hero: 'blog-dog-vaccination-guide.webp', inline: 'blog-pet-records-timeline.webp' },
  'gene-editing-future-hereditary-dog-diseases': { hero: 'blog-puppy-vaccination.webp', inline: 'blog-pet-records.webp' },
  'ethics-pet-cloning-2026-costs-reality': { hero: 'blog-life-stage-care.webp', inline: 'blog-vet-bill-organizer.webp' },
  'paper-pet-records-dead-rise-biological-pet-os': { hero: 'blog-pet-records-timeline.webp', inline: 'blog-best-pet-health-app.webp' },
};

export function pickDominanceImages(slug, title) {
  const mapped = DOMINANCE_IMAGE_BY_SLUG[slug];
  if (!mapped) {
    throw new Error(`Missing dominance image mapping for slug: ${slug}`);
  }
  return [
    {
      src: `/images/blog/${mapped.hero}`,
      alt: `${title} - primary reference`,
      caption: 'Topic-specific reference for planning and vet conversations',
    },
    {
      src: `/images/blog/${mapped.inline}`,
      alt: `${title} - related care context`,
      caption: 'Related care context from your PetClues health library',
    },
  ];
}

export function dominanceHeroFile(slug) {
  const mapped = DOMINANCE_IMAGE_BY_SLUG[slug];
  if (!mapped) {
    throw new Error(`Missing dominance image mapping for slug: ${slug}`);
  }
  return mapped.hero;
}
