/**
 * Compact breed catalog seed for breeds.json expansion.
 * Health issues are common veterinary breed predispositions; uncertain rows set needsReview.
 * Vaccine schedules are species-core windows (AAHA/AAFP style), not clinic prescriptions.
 */

function dog(slug, name, size, weight, life, issues, groom, temper, needsReview = false) {
  return {
    slug,
    name,
    species: 'dog',
    size_category: size,
    avg_weight_range: weight,
    avg_lifespan: life,
    common_health_issues: issues,
    grooming_needs: groom,
    temperament_summary: temper,
    ...(needsReview ? { NEEDS_VET_REVIEW: true } : {}),
  };
}

function cat(slug, name, size, weight, life, issues, groom, temper, needsReview = false) {
  return {
    slug,
    name,
    species: 'cat',
    size_category: size,
    avg_weight_range: weight,
    avg_lifespan: life,
    common_health_issues: issues,
    grooming_needs: groom,
    temperament_summary: temper,
    ...(needsReview ? { NEEDS_VET_REVIEW: true } : {}),
  };
}

/** @type {ReturnType<typeof dog>[]} */
export const BREED_SEED = [
  // Existing samples first (preserve)
  dog('labrador-retriever', 'Labrador Retriever', 'large', '55-80 lb (25-36 kg)', '11-13 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Exercise-induced collapse (EIC)', 'Progressive retinal atrophy (PRA)', 'Obesity-related orthopedic stress'],
    'Weekly brushing; heavier shed seasons need more frequent coat care. Check ears after swimming.',
    'Friendly, food-motivated, high energy working breed that needs structured exercise and training.'),
  cat('domestic-shorthair', 'Domestic Shorthair', 'medium', '8-12 lb (3.5-5.5 kg)', '12-18 years (indoor)',
    ['Dental disease', 'Obesity', 'Chronic kidney disease (senior)', 'Hyperthyroidism (senior)', 'Lower urinary tract disease (FLUTD/FIC)'],
    'Weekly brushing for most coats; nail trims and dental home care as advised by the veterinarian.',
    'Variable mixed-breed temperaments; typically adaptable companion cats with individual energy levels.'),
  dog('french-bulldog', 'French Bulldog', 'small', '16-28 lb (7-13 kg)', '10-12 years',
    ['Brachycephalic obstructive airway syndrome (BOAS)', 'Intervertebral disc disease (IVDD) risk', 'Allergic skin disease', 'Hip dysplasia', 'Heat intolerance'],
    'Clean facial folds regularly; short coat needs light brushing. Monitor skin fold dermatitis.',
    'Affectionate companion breed; low exercise tolerance compared with sporting breeds; needs heat and airway awareness.'
    ),

  dog('golden-retriever', 'Golden Retriever', 'large', '55-75 lb (25-34 kg)', '10-12 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Cancer risk (breed-associated)', 'Hypothyroidism', 'Ear infections'],
    'Daily to every-other-day brushing; heavy seasonal shed.',
    'Friendly, eager-to-please sporting breed with high social drive.'),
  dog('german-shepherd', 'German Shepherd', 'large', '50-90 lb (23-41 kg)', '9-13 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Degenerative myelopathy', 'Exocrine pancreatic insufficiency', 'Bloat (GDV) risk'],
    'Heavy double coat; brush several times weekly.',
    'Loyal working breed that needs a job, training, and structured exercise.'),
  dog('poodle-standard', 'Standard Poodle', 'large', '40-70 lb (18-32 kg)', '12-15 years',
    ['Hip dysplasia', 'Progressive retinal atrophy (PRA)', 'Addison disease risk', 'Sebaceous adenitis', 'Bloat (GDV) risk'],
    'Professional clips every 6-8 weeks; non-shedding coat mats without care.',
    'Intelligent, active companion that thrives on training and mental work.'),
  dog('poodle-miniature', 'Miniature Poodle', 'small', '10-15 lb (4.5-7 kg)', '13-15 years',
    ['Progressive retinal atrophy (PRA)', 'Patellar luxation', 'Legg-Calve-Perthes risk', 'Dental crowding', 'Ear infections'],
    'Regular clipping and ear care; coat mats easily.',
    'Bright, people-oriented small companion with high trainability.'),
  dog('poodle-toy', 'Toy Poodle', 'toy', '4-6 lb (1.8-2.7 kg)', '13-15 years',
    ['Patellar luxation', 'Dental disease', 'Tracheal collapse risk', 'Progressive retinal atrophy (PRA)', 'Hypoglycemia risk when young'],
    'Frequent professional grooming; protect from rough play due to size.',
    'Alert toy companion; needs careful handling and dental attention.'),
  dog('bulldog', 'Bulldog', 'medium', '40-50 lb (18-23 kg)', '8-10 years',
    ['Brachycephalic obstructive airway syndrome (BOAS)', 'Hip dysplasia', 'Cherry eye', 'Skin fold dermatitis', 'Heat intolerance'],
    'Daily fold cleaning; short coat, low brush need.',
    'Calm companion; limited exercise tolerance; avoid heat and overexertion.'),
  dog('beagle', 'Beagle', 'small', '20-30 lb (9-14 kg)', '12-15 years',
    ['Ear infections', 'Obesity', 'Intervertebral disc disease (IVDD) risk', 'Hypothyroidism', 'Cherry eye'],
    'Weekly brush; check ears after fieldwork.',
    'Scent-driven hound; needs secure fencing and mental work.'),
  dog('rottweiler', 'Rottweiler', 'large', '80-135 lb (36-61 kg)', '8-10 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Osteosarcoma risk', 'Heart disease screening needs', 'Cranial cruciate ligament injury'],
    'Weekly brush; seasonal shed.',
    'Confident working breed needing early socialization and firm, fair training.'),
  dog('yorkshire-terrier', 'Yorkshire Terrier', 'toy', '4-7 lb (1.8-3.2 kg)', '13-16 years',
    ['Dental disease', 'Tracheal collapse', 'Patellar luxation', 'Portosystemic shunt risk', 'Hypoglycemia risk when young'],
    'Daily coat care if kept long; many owners keep a puppy cut.',
    'Bold toy terrier; fragile trachea means harness over collar for many dogs.'),
  dog('boxer', 'Boxer', 'large', '50-80 lb (23-36 kg)', '10-12 years',
    ['Cancer risk (breed-associated)', 'Cardiomyopathy / arrhythmia screening', 'Hip dysplasia', 'Allergic skin disease', 'Bloat (GDV) risk'],
    'Weekly brush; wipe facial folds.',
    'Playful, high-drive guardian/companion needing firm exercise outlets.'),
  dog('dachshund', 'Dachshund', 'small', '16-32 lb (7-14.5 kg)', '12-16 years',
    ['Intervertebral disc disease (IVDD)', 'Obesity-related spinal stress', 'Dental disease', 'Patellar luxation', 'Ear infections (long coats)'],
    'Coat varies by variety; avoid jump-offs furniture for back safety.',
    'Curious hound; stairs and jumping are spinal risk management issues.'),
  dog('siberian-husky', 'Siberian Husky', 'medium', '35-60 lb (16-27 kg)', '12-14 years',
    ['Hip dysplasia', 'Eye issues (cataracts/corneal dystrophy risk)', 'Zinc-responsive dermatosis risk', 'Hypothyroidism', 'Escape artist injury risk'],
    'Heavy shed twice yearly; brush through blowouts.',
    'High-energy sled breed; needs secure containment and real mileage.'),
  dog('great-dane', 'Great Dane', 'giant', '110-175 lb (50-79 kg)', '7-10 years',
    ['Bloat (GDV)', 'Cardiomyopathy screening needs', 'Hip dysplasia', 'Wobbler syndrome risk', 'Osteosarcoma risk'],
    'Short coat, weekly wipe-down; watch pressure sores on hard floors.',
    'Gentle giant; growth must stay lean; raised bowls and GDV awareness matter.'),
  dog('doberman-pinscher', 'Doberman Pinscher', 'large', '60-100 lb (27-45 kg)', '10-13 years',
    ['Dilated cardiomyopathy risk', 'Von Willebrand disease', 'Hip dysplasia', 'Hypothyroidism', 'Wobbler syndrome risk'],
    'Short coat, minimal brush; nail care matters for active dogs.',
    'Athletic working breed; cardiac screening conversations are breed-normal.'),
  dog('australian-shepherd', 'Australian Shepherd', 'medium', '40-65 lb (18-29 kg)', '12-15 years',
    ['Hip dysplasia', 'MDR1 drug sensitivity risk', 'Eye anomalies (CEA risk)', 'Epilepsy risk', 'Allergic skin disease'],
    'Medium coat; brush 2-3x weekly; mats behind ears.',
    'High-drive herding breed; under-exercised Aussies invent jobs you will not like.'),
  dog('pembroke-welsh-corgi', 'Pembroke Welsh Corgi', 'small', '24-30 lb (11-14 kg)', '12-13 years',
    ['Intervertebral disc disease (IVDD)', 'Hip dysplasia', 'Degenerative myelopathy risk', 'Obesity', 'Progressive retinal atrophy (PRA)'],
    'Double coat blowouts; brush through shed seasons.',
    'Herding companion; long back means jump and weight control discipline.'),
  dog('cavalier-king-charles-spaniel', 'Cavalier King Charles Spaniel', 'small', '13-18 lb (6-8 kg)', '9-14 years',
    ['Mitral valve disease', 'Syringomyelia / Chiari-like risk', 'Hip dysplasia', 'Ear infections', 'Eye issues'],
    'Daily brush; ears need frequent checks.',
    'Affectionate companion; cardiac screening is a breed conversation, not optional trivia.'),
  dog('shih-tzu', 'Shih Tzu', 'small', '9-16 lb (4-7 kg)', '10-16 years',
    ['Brachycephalic airway concerns', 'Dental disease', 'Intervertebral disc disease (IVDD) risk', 'Eye proptosis risk', 'Ear infections'],
    'Daily coat care or keep short; clean facial folds.',
    'Companion breed; heat and rough play around the eyes need caution.'),
  dog('boston-terrier', 'Boston Terrier', 'small', '12-25 lb (5-11 kg)', '11-13 years',
    ['Brachycephalic obstructive airway syndrome (BOAS)', 'Eye injuries / corneal ulcers', 'Patellar luxation', 'Allergies', 'Heat intolerance'],
    'Wipe face folds; short coat.',
    'Lively companion; airway and eye protection beat marathon jogging.'),
  dog('pomeranian', 'Pomeranian', 'toy', '3-7 lb (1.4-3.2 kg)', '12-16 years',
    ['Dental disease', 'Tracheal collapse', 'Patellar luxation', 'Alopecia X risk', 'Heart disease screening needs'],
    'Thick coat needs frequent brushing to prevent mats.',
    'Alert toy companion; harness walking protects a delicate trachea.'),
  dog('havanese', 'Havanese', 'small', '7-13 lb (3-6 kg)', '14-16 years',
    ['Patellar luxation', 'Dental disease', 'Heart murmur screening needs', 'Legg-Calve-Perthes risk', 'Ear infections'],
    'Daily brush or keep a shorter pet cut.',
    'Social companion; thrives with people time and gentle training.'),
  dog('shetland-sheepdog', 'Shetland Sheepdog', 'small', '15-25 lb (7-11 kg)', '12-14 years',
    ['MDR1 drug sensitivity risk', 'Collie eye anomaly risk', 'Hip dysplasia', 'Dermatomyositis risk', 'Thyroid disease'],
    'Double coat; brush through seasonal sheds.',
    'Sensitive herding breed; thrives on training and calm handling.'),
  dog('miniature-schnauzer', 'Miniature Schnauzer', 'small', '11-20 lb (5-9 kg)', '12-15 years',
    ['Pancreatitis risk', 'Urinary stones risk', 'Dental disease', 'Eye issues', 'Liver shunt risk in some lines'],
    'Regular hand-strip or clip; beard needs daily wipe.',
    'Spirited terrier-type companion; diet fat content often matters clinically.'),
  dog('cocker-spaniel', 'Cocker Spaniel', 'medium', '20-30 lb (9-14 kg)', '10-14 years',
    ['Ear infections', 'Eye issues (cataracts/glaucoma risk)', 'Hip dysplasia', 'Allergic skin disease', 'Hypothyroidism'],
    'Ears and coat need frequent maintenance.',
    'Merry sporting companion; ear care is non-negotiable.'),
  dog('border-collie', 'Border Collie', 'medium', '30-55 lb (14-25 kg)', '12-15 years',
    ['Hip dysplasia', 'Collie eye anomaly risk', 'Epilepsy risk', 'MDR1 risk in some lines', 'Obsessive work drive injuries'],
    'Dense coat; brush weekly.',
    'Extreme working drive; mental work is medical welfare for this breed.'),
  dog('chihuahua', 'Chihuahua', 'toy', '3-6 lb (1.4-2.7 kg)', '14-16 years',
    ['Dental disease', 'Patellar luxation', 'Heart disease screening needs', 'Tracheal collapse risk', 'Hydrocephalus risk in some lines'],
    'Coat varies; dental home care is the real grooming priority.',
    'Bold toy dog; fragile in cold and rough handling.'),
  dog('pug', 'Pug', 'small', '14-18 lb (6-8 kg)', '12-15 years',
    ['Brachycephalic obstructive airway syndrome (BOAS)', 'Eye proptosis / corneal ulcers', 'Obesity', 'Skin fold dermatitis', 'Heat intolerance'],
    'Clean facial wrinkles daily; short coat.',
    'Companion clown; heat and airway limits define exercise plans.'),
  dog('mastiff', 'Mastiff', 'giant', '120-230 lb (54-104 kg)', '6-10 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Bloat (GDV)', 'Cardiomyopathy screening needs', 'Cruciate ligament injury'],
    'Short coat; watch skin folds and pressure sores.',
    'Guardian breed; keep lean through growth; joint load is everything.'),
  dog('bernese-mountain-dog', 'Bernese Mountain Dog', 'giant', '70-115 lb (32-52 kg)', '7-10 years',
    ['Cancer risk (breed-associated)', 'Hip dysplasia', 'Elbow dysplasia', 'Bloat (GDV) risk', 'Histocytosis risk'],
    'Thick coat; brush several times weekly.',
    'Gentle working companion; shorter lifespan means earlier senior screening talks.'),
  dog('newfoundland', 'Newfoundland', 'giant', '100-150 lb (45-68 kg)', '8-10 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Cardiac screening (SAS risk)', 'Cystinuria risk', 'Hot-spot skin issues'],
    'Heavy coat; expect professional grooming help.',
    'Water-loving gentle giant; joint and heart screening conversations are breed-normal.'),
  dog('saint-bernard', 'Saint Bernard', 'giant', '120-180 lb (54-82 kg)', '8-10 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Bloat (GDV)', 'Ectropic/entropic eyelid issues', 'Osteosarcoma risk'],
    'Dense coat; drool management is part of home care.',
    'Rescue heritage companion; keep cool and lean.'),
  dog('akita', 'Akita', 'large', '70-130 lb (32-59 kg)', '10-14 years',
    ['Hip dysplasia', 'Autoimmune thyroid risk', 'VKH-like syndrome risk', 'Bloat (GDV) risk', 'Progressive retinal atrophy (PRA)'],
    'Double coat blowouts twice yearly.',
    'Reserved guardian; needs experienced handling and early socialization.'),
  dog('shiba-inu', 'Shiba Inu', 'small', '17-23 lb (8-10 kg)', '12-15 years',
    ['Allergies', 'Glaucoma risk', 'Hip dysplasia', 'Patellar luxation', 'Dental tartar'],
    'Heavy seasonal shed; brush through blowouts.',
    'Independent spitz; escape artist; needs patient training.'),
  dog('weimaraner', 'Weimaraner', 'large', '55-90 lb (25-41 kg)', '10-13 years',
    ['Bloat (GDV)', 'Hip dysplasia', 'Hypertrophic osteodystrophy risk in puppies', 'Distichiasis risk', 'Behavioral separation stress'],
    'Short coat, weekly wipe.',
    'High-drive hunting breed; under-exercise shows up as behavior problems.'),
  dog('vizsla', 'Vizsla', 'medium', '45-65 lb (20-29 kg)', '12-14 years',
    ['Hip dysplasia', 'Epilepsy risk', 'Lymphoma risk', 'Allergies', 'Sensitivity to anesthesia notes in some lines'],
    'Short coat; sunburn risk on thin coat.',
    'Velcro sporting breed; needs mileage and closeness to people.'),
  dog('rhodesian-ridgeback', 'Rhodesian Ridgeback', 'large', '70-85 lb (32-39 kg)', '10-12 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Dermoid sinus risk', 'Hypothyroidism', 'Bloat (GDV) risk'],
    'Short coat, weekly brush.',
    'Athletic hound; ridge checks in puppies matter for dermoid sinus.'),
  dog('basset-hound', 'Basset Hound', 'medium', '40-65 lb (18-29 kg)', '12-13 years',
    ['Ear infections', 'Intervertebral disc disease (IVDD) risk', 'Glaucoma risk', 'Obesity', 'Gastric dilatation risk'],
    'Long ears need cleaning; nails grow fast.',
    'Scent hound; keep lean to spare the back and joints.'),
  dog('bloodhound', 'Bloodhound', 'large', '80-110 lb (36-50 kg)', '10-12 years',
    ['Ear infections', 'Skin fold dermatitis', 'Hip dysplasia', 'Eyelid issues', 'Bloat (GDV) risk'],
    'Ears and folds need routine cleaning.',
    'Trailing specialist; needs space and scent work.'),
  dog('maltese', 'Maltese', 'toy', '4-7 lb (1.8-3.2 kg)', '12-15 years',
    ['Dental disease', 'Patellar luxation', 'Tracheal collapse risk', 'Shunt risk in some lines', 'Tear staining dermatitis'],
    'Daily coat care or short pet cut; face cleaning.',
    'Companion toy; dental disease shows early without home care.'),
  dog('papillon', 'Papillon', 'toy', '5-10 lb (2-4.5 kg)', '13-15 years',
    ['Patellar luxation', 'Dental disease', 'Progressive retinal atrophy (PRA)', 'Open fontanelle risk in some lines', 'Liver shunt risk'],
    'Ears need gentle brush; coat otherwise light.',
    'Athletic toy; loves training more than lap-only life.'),
  dog('bichon-frise', 'Bichon Frise', 'small', '12-18 lb (5-8 kg)', '14-15 years',
    ['Dental disease', 'Patellar luxation', 'Allergies', 'Bladder stones risk', 'Cataracts risk'],
    'Regular professional grooming; coat mats without brushing.',
    'Cheerful companion; allergies and teeth dominate adult care.'),
  dog('west-highland-white-terrier', 'West Highland White Terrier', 'small', '15-20 lb (7-9 kg)', '12-16 years',
    ['Allergic skin disease', 'Dental disease', 'Legg-Calve-Perthes risk', 'Copper hepatopathy risk', 'Pulmonary fibrosis risk'],
    'Regular grooming; skin care often outranks coat fashion.',
    'Terrier attitude; itchy Westies need dermatology plans, not only shampoo roulette.'),
  dog('scottish-terrier', 'Scottish Terrier', 'small', '18-22 lb (8-10 kg)', '11-13 years',
    ['Bladder cancer risk', 'Craniomandibular osteopathy risk', 'Von Willebrand risk', 'Patellar luxation', 'Dental disease'],
    'Hand-strip or clip; beard hygiene.',
    'Independent terrier; urinary changes in seniors deserve urgency.'),
  dog('airedale-terrier', 'Airedale Terrier', 'large', '40-65 lb (18-29 kg)', '11-14 years',
    ['Hip dysplasia', 'Hypothyroidism', 'Gastric dilatation risk', 'Skin allergies', 'Umbilical hernia risk'],
    'Wire coat needs stripping or clipping.',
    'Versatile terrier; needs work and consistent training.'),
  dog('soft-coated-wheaten-terrier', 'Soft Coated Wheaten Terrier', 'medium', '30-40 lb (14-18 kg)', '12-14 years',
    ['Protein-losing nephropathy risk', 'Protein-losing enteropathy risk', 'Hip dysplasia', 'Allergies', 'Addison risk'],
    'Daily soft-coat brushing.',
    'Happy terrier; renal/protein-losing disease awareness is breed-specific.'),
  dog('irish-setter', 'Irish Setter', 'large', '50-70 lb (23-32 kg)', '12-15 years',
    ['Hip dysplasia', 'Progressive retinal atrophy (PRA)', 'Hypothyroidism', 'Epilepsy risk', 'Bloat (GDV) risk'],
    'Long coat mats without regular brush-outs.',
    'Birdy sporting breed; needs real running room.'),
  dog('english-springer-spaniel', 'English Springer Spaniel', 'medium', '40-50 lb (18-23 kg)', '12-14 years',
    ['Hip dysplasia', 'Ear infections', 'Phosphofructokinase deficiency risk', 'Eye issues', 'Rage syndrome rare reports'],
    'Feathers mat; ears need cleaning.',
    'Working spaniel energy; underworked Springers invent chaos.'),
  dog('brittany', 'Brittany', 'medium', '30-40 lb (14-18 kg)', '12-14 years',
    ['Hip dysplasia', 'Epilepsy risk', 'Hypothyroidism', 'Ear infections', 'Allergies'],
    'Medium coat; brush weekly.',
    'Compact bird dog; high stamina, needs outlets.'),
  dog('pointer', 'Pointer', 'large', '45-75 lb (20-34 kg)', '12-17 years',
    ['Hip dysplasia', 'Entropion risk', 'Deafness risk in some colors', 'Allergies', 'Bloat (GDV) risk'],
    'Short coat.',
    'Specialist hunter; needs structured field or sport work.'),
  dog('dalmatian', 'Dalmatian', 'large', '45-70 lb (20-32 kg)', '11-13 years',
    ['Urinary stones (urate)', 'Deafness risk', 'Allergies', 'Hip dysplasia', 'Skin issues'],
    'Short coat sheds heavily.',
    'High-energy coach dog; water intake and urate stone prevention matter.'),
  dog('samoyed', 'Samoyed', 'large', '35-65 lb (16-29 kg)', '12-14 years',
    ['Hip dysplasia', 'Diabetes risk', 'Progressive retinal atrophy (PRA)', 'Cardiac screening needs', 'Skin allergies'],
    'Dense white coat; expect serious grooming time.',
    'Smiling spitz; heat intolerance and coat care define ownership.'),
  dog('alaskan-malamute', 'Alaskan Malamute', 'large', '75-100 lb (34-45 kg)', '10-14 years',
    ['Hip dysplasia', 'Chondrodysplasia risk', 'Zinc-responsive dermatosis', 'Bloat (GDV) risk', 'Hypothyroidism'],
    'Heavy shed; brush through blowouts.',
    'Freighting breed; not an apartment sprinter substitute for a Husky.'),
  dog('cane-corso', 'Cane Corso', 'large', '88-110 lb (40-50 kg)', '9-12 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Demodex risk', 'Bloat (GDV) risk', 'Eyelid issues'],
    'Short coat.',
    'Guardian mastiff type; needs experienced socialization.'),
  dog('bullmastiff', 'Bullmastiff', 'giant', '100-130 lb (45-59 kg)', '7-9 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Cancer risk', 'Bloat (GDV)', 'Entropion'],
    'Short coat; watch heat.',
    'Quiet guardian; shorter lifespan means earlier screening.'),
  dog('italian-greyhound', 'Italian Greyhound', 'toy', '7-14 lb (3-6 kg)', '14-15 years',
    ['Dental disease', 'Leg fractures from jump-downs', 'Progressive retinal atrophy (PRA)', 'Hypothyroidism', 'Anesthesia sensitivity notes'],
    'Thin coat; needs coats in cold weather.',
    'Fragile sighthound toy; soft landings and dental care dominate.'),
  dog('whippet', 'Whippet', 'medium', '25-40 lb (11-18 kg)', '12-15 years',
    ['Heart screening needs', 'Dental disease', 'Anesthesia sensitivity notes', 'Skin tears', 'Eye issues'],
    'Short coat; cold weather coats help.',
    'Quiet house dog, explosive athlete outdoors.'),
  dog('greyhound', 'Greyhound', 'large', '60-70 lb (27-32 kg)', '10-14 years',
    ['Dental disease', 'Osteosarcoma risk', 'Anesthesia sensitivity', 'Hypothyroidism', 'Corns on feet'],
    'Thin skin and coat; bedding matters.',
    'Retired racers need soft beds, dental care, and thoughtful anesthesia plans.'),
  dog('basenji', 'Basenji', 'small', '22-24 lb (10-11 kg)', '13-14 years',
    ['Fanconi syndrome risk', 'Progressive retinal atrophy (PRA)', 'Hip dysplasia', 'Hypothyroidism', 'IBD risk'],
    'Low shed; wipe coat.',
    'Barkless but not silent; independent hound with metabolic screening needs.'),
  dog('chow-chow', 'Chow Chow', 'medium', '45-70 lb (20-32 kg)', '8-12 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Entropion', 'Hypothyroidism', 'Bloat (GDV) risk'],
    'Dense coat; professional grooming often required.',
    'Aloof spitz; heat stroke risk with heavy coat.'),
  dog('shar-pei', 'Chinese Shar-Pei', 'medium', '45-60 lb (20-27 kg)', '8-12 years',
    ['Familial Shar-Pei fever risk', 'Skin fold infections', 'Entropin', 'Amyloidosis risk', 'Hip dysplasia'],
    'Fold care is medical, not cosmetic.',
    'Independent guardian; fever and kidney sequelae are breed-specific watch items.'),
  dog('lhasa-apso', 'Lhasa Apso', 'small', '12-18 lb (5-8 kg)', '12-15 years',
    ['Kidney disease risk', 'Intervertebral disc disease (IVDD) risk', 'Eye issues', 'Allergies', 'Dental disease'],
    'Long coat daily care or puppy cut.',
    'Watchful companion; renal screening talks matter in adults/seniors.'),
  dog('pekingese', 'Pekingese', 'small', '7-14 lb (3-6 kg)', '12-14 years',
    ['Brachycephalic airway concerns', 'Intervertebral disc disease (IVDD) risk', 'Eye injuries', 'Heat intolerance', 'Dental disease'],
    'Heavy coat; face and eye care daily.',
    'Palace companion; stairs and heat are management problems.'),
  dog('japanese-chin', 'Japanese Chin', 'toy', '4-9 lb (1.8-4 kg)', '10-12 years',
    ['Heart disease screening needs', 'Patellar luxation', 'Eye injuries', 'Brachycephalic concerns', 'Dental disease'],
    'Soft coat brushing; face cleaning.',
    'Catlike toy companion; cardiac and eye vigilance.'),
  dog('brussels-griffon', 'Brussels Griffon', 'toy', '8-10 lb (3.5-4.5 kg)', '12-15 years',
    ['Brachycephalic concerns', 'Patellar luxation', 'Eye injuries', 'Dental disease', 'Hip dysplasia'],
    'Wire or smooth coat care; face folds.',
    'Big personality toy; eyes and airway define risk.'),
  dog('affenpinscher', 'Affenpinscher', 'toy', '7-10 lb (3-4.5 kg)', '12-15 years',
    ['Patellar luxation', 'Dental disease', 'Hip dysplasia', 'Heart murmur screening', 'Anesthesia size risks'],
    'Wire coat stripping or clipping.',
    'Monkey-faced toy terrier; dental care early.'),
  dog('miniature-pinscher', 'Miniature Pinscher', 'toy', '8-11 lb (3.5-5 kg)', '12-16 years',
    ['Patellar luxation', 'Legg-Calve-Perthes risk', 'Heart disease screening', 'Dental disease', 'Leg fractures from jumps'],
    'Short coat.',
    'High-station toy; protect from high couches.'),
  dog('manchester-terrier', 'Manchester Terrier', 'small', '12-22 lb (5-10 kg)', '15-17 years',
    ['Von Willebrand risk', 'Pattern baldness', 'Dental disease', 'Legg-Calve-Perthes risk', 'Eye issues'],
    'Short coat.',
    'Sleek vermin hunter; long-lived with dental attention.'),
  dog('cairn-terrier', 'Cairn Terrier', 'small', '13-14 lb (6 kg)', '13-15 years',
    ['Allergies', 'Portosystemic shunt risk', 'Legg-Calve-Perthes risk', 'Ocular lens luxation risk', 'Dental disease'],
    'Wiry coat hand-strip preferred.',
    'Busy earthdog; itchy skin is common adult work.'),
  dog('norfolk-terrier', 'Norfolk Terrier', 'small', '11-12 lb (5 kg)', '12-16 years',
    ['Patellar luxation', 'Dental disease', 'Hip dysplasia', 'Eye issues', 'Allergies'],
    'Wire coat care.',
    'Drop-ear terrier; sturdy for size, still dental-prone.'),
  dog('norwich-terrier', 'Norwich Terrier', 'small', '11-12 lb (5 kg)', '12-16 years',
    ['Upper airway syndrome risk', 'Patellar luxation', 'Dental disease', 'Hip dysplasia', 'Allergies'],
    'Wire coat care.',
    'Prick-ear terrier; some lines need airway evaluation.'),
  dog('border-terrier', 'Border Terrier', 'small', '11-15 lb (5-7 kg)', '12-15 years',
    ['Canine epileptoid cramping syndrome risk', 'Hip dysplasia', 'Dental disease', 'Allergies', 'Heart screening needs'],
    'Wiry coat; hand-strip.',
    'Tough working terrier; note cramping syndrome discussions in breed circles.'),
  dog('staffordshire-bull-terrier', 'Staffordshire Bull Terrier', 'medium', '24-38 lb (11-17 kg)', '12-14 years',
    ['Hip dysplasia', 'L-2-HGA risk', 'Cataracts risk', 'Skin allergies', 'Cruciate injury'],
    'Short coat; skin care if allergic.',
    'Muscular companion; genetic testing conversations exist for L-2-HGA.'),
  dog('american-staffordshire-terrier', 'American Staffordshire Terrier', 'medium', '40-70 lb (18-32 kg)', '12-16 years',
    ['Hip dysplasia', 'Cerebellar ataxia risk', 'Skin allergies', 'Cruciate injury', 'Heart screening needs'],
    'Short coat.',
    'Strong companion; needs training and fair outlets.'),
  dog('bull-terrier', 'Bull Terrier', 'medium', '45-70 lb (20-32 kg)', '11-14 years',
    ['Deafness risk (especially white)', 'Kidney disease risk', 'Skin allergies', 'Heart screening needs', 'Luxating patellas'],
    'Short coat; sunburn on white dogs.',
    'Egg-head companion; deafness and renal watch items are breed-known.'),
  dog('miniature-bull-terrier', 'Miniature Bull Terrier', 'small', '25-33 lb (11-15 kg)', '11-13 years',
    ['Primary lens luxation risk', 'Deafness risk', 'Heart issues', 'Skin allergies', 'Kidney disease risk'],
    'Short coat.',
    'Compact bull type; eye disease screening talks matter.'),
  dog('american-bully', 'American Bully', 'medium', '30-80 lb (14-36 kg)', '10-12 years',
    ['Hip dysplasia', 'Skin allergies', 'Brachycephalic concerns in extreme types', 'Cherry eye', 'Cruciate injury'],
    'Short coat; folds if present need cleaning.',
    'Companion bully type; extreme conformation raises airway risk.'
    ),
  dog('pit-bull-type', 'Pit Bull Type (American)', 'medium', '30-60 lb (14-27 kg)', '12-14 years',
    ['Hip dysplasia', 'Skin allergies', 'Cruciate injury', 'Heartworm risk if prevention lapses', 'Demodex risk'],
    'Short coat.',
    'People-oriented type label covering mixed registry dogs; individual screening beats stereotypes.'
    ),
  dog('collie-rough', 'Collie (Rough)', 'large', '50-75 lb (23-34 kg)', '12-14 years',
    ['MDR1 drug sensitivity', 'Collie eye anomaly', 'Dermatomyositis risk', 'Hip dysplasia', 'Bloat (GDV) risk'],
    'Long coat daily care.',
    'Classic herding breed; MDR1 status before certain drugs.'),
  dog('collie-smooth', 'Collie (Smooth)', 'large', '50-75 lb (23-34 kg)', '12-14 years',
    ['MDR1 drug sensitivity', 'Collie eye anomaly', 'Hip dysplasia', 'Dermatomyositis risk', 'Gastric dilatation risk'],
    'Shorter coat than rough; still sheds.',
    'Same medical themes as Rough Collie with easier coat care.'),
  dog('bearded-collie', 'Bearded Collie', 'medium', '45-55 lb (20-25 kg)', '12-14 years',
    ['Hip dysplasia', 'Hypothyroidism', 'Addison disease risk', 'Eye issues', 'Autoimmune skin risk'],
    'Long coat high maintenance.',
    'Bouncy herder; endocrine autoimmune themes appear in breed health surveys.'),
  dog('old-english-sheepdog', 'Old English Sheepdog', 'large', '60-100 lb (27-45 kg)', '10-12 years',
    ['Hip dysplasia', 'Deafness risk', 'Cataracts risk', 'Thyroid disease', 'Bloat (GDV) risk'],
    'Heavy coat; often clipped for pet homes.',
    'Big herder; coat care or clip is a health hygiene issue.'),
  dog('briard', 'Briard', 'large', '55-100 lb (25-45 kg)', '10-12 years',
    ['Hip dysplasia', 'Stationary night blindness risk', 'Gastric dilatation risk', 'Hypothyroidism', 'Ear infections'],
    'Long coat daily work.',
    'Big herding guardian; night vision issues discussed in breed.'),
  dog('belgian-malinois', 'Belgian Malinois', 'large', '40-80 lb (18-36 kg)', '14-16 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Eye issues', 'Sensitivity/high drive injuries', 'Gastric dilatation risk'],
    'Short coat.',
    'Elite working breed; most pet homes underestimate drive.'),
  dog('belgian-tervuren', 'Belgian Tervuren', 'large', '45-75 lb (20-34 kg)', '12-14 years',
    ['Hip dysplasia', 'Epilepsy risk', 'Eye issues', 'Thyroid disease', 'Gastric dilatation risk'],
    'Longer coat than Malinois; brush regularly.',
    'Elegant Belgian; epilepsy appears in breed health conversations.'),
  dog('belgian-sheepdog', 'Belgian Sheepdog (Groenendael)', 'large', '45-75 lb (20-34 kg)', '12-14 years',
    ['Hip dysplasia', 'Epilepsy risk', 'Eye issues', 'Thyroid disease', 'Gastric dilatation risk'],
    'Long black coat care.',
    'Working Belgian; similar medical themes to Tervuren.'),
  dog('dutch-shepherd', 'Dutch Shepherd', 'large', '42-75 lb (19-34 kg)', '11-14 years',
    ['Hip dysplasia', 'Inflammatory myopathy risk', 'Allergies', 'Eye issues', 'High-drive soft tissue injuries'],
    'Coat varies by variety.',
    'Working shepherd; not a casual first dog for most homes.'),
  dog('anatolian-shepherd', 'Anatolian Shepherd', 'giant', '80-150 lb (36-68 kg)', '11-13 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Entropion', 'Hypothyroidism', 'Sensitivity to anesthesia notes'],
    'Short to rough coat.',
    'Livestock guardian; independent; joint load management.'),
  dog('great-pyrenees', 'Great Pyrenees', 'giant', '85-160 lb (39-73 kg)', '10-12 years',
    ['Hip dysplasia', 'Patellar luxation', 'Entropin', 'Hot spots', 'Bloat (GDV) risk'],
    'Heavy white coat; mats and moisture dermatitis.',
    'Night bark livestock guardian; coat and heat management.'),
  dog('kuvasz', 'Kuvasz', 'giant', '70-115 lb (32-52 kg)', '10-12 years',
    ['Hip dysplasia', 'Osteosarcoma risk', 'Thyroid disease', 'Deafness risk', 'Bloat (GDV) risk'],
    'White coat care.',
    'Hungarian guardian; reserved with strangers.'),
  dog('komondor', 'Komondor', 'giant', '80-130 lb (36-59 kg)', '10-12 years',
    ['Hip dysplasia', 'Entropin', 'Hot spots under cords', 'Bloat (GDV) risk', 'Ear infections'],
    'Corded coat is a specialist skill.',
    'Corded guardian; skin under cords can hide infection.'),
  dog('tibetan-mastiff', 'Tibetan Mastiff', 'giant', '70-150 lb (32-68 kg)', '10-14 years',
    ['Hip dysplasia', 'Hypothyroidism', 'Entropin', 'Demodex risk', 'Heat intolerance'],
    'Massive coat; seasonal blowout.',
    'Primitive guardian; not a suburban jogger breed.'),
  dog('leonberger', 'Leonberger', 'giant', '90-170 lb (41-77 kg)', '7-9 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Leonberger polyneuropathy risk', 'Osteosarcoma risk', 'Bloat (GDV)'],
    'Lion coat brushing.',
    'Gentle giant; neuropathy testing exists in breed programs.'),
  dog('irish-wolfhound', 'Irish Wolfhound', 'giant', '105-180 lb (48-82 kg)', '6-8 years',
    ['Osteosarcoma risk', 'Dilated cardiomyopathy risk', 'Bloat (GDV)', 'Hip dysplasia', 'Liver shunt risk in some lines'],
    'Rough coat care.',
    'Towering sighthound; short lifespan drives early cardiac/cancer vigilance.'),
  dog('scottish-deerhound', 'Scottish Deerhound', 'giant', '75-110 lb (34-50 kg)', '8-11 years',
    ['Osteosarcoma risk', 'Heart disease screening', 'Bloat (GDV)', 'Cystinuria risk', 'Factor VII deficiency risk'],
    'Wiry coat.',
    'Hunting sighthound; cancer and GDV awareness.'),
  dog('borzoi', 'Borzoi', 'giant', '60-105 lb (27-48 kg)', '9-14 years',
    ['Gastric dilatation risk', 'Osteosarcoma risk', 'Heart screening needs', 'Thyroid disease', 'Sensitivity to anesthesia notes'],
    'Long coat care.',
    'Silent house sighthound; explosive outdoors.'),
  dog('afghan-hound', 'Afghan Hound', 'large', '50-60 lb (23-27 kg)', '12-14 years',
    ['Hip dysplasia', 'Allergies', 'Hypothyroidism', 'Cataracts risk', 'Sensitivity notes'],
    'High-maintenance silky coat.',
    'Aloof sighthound; coat care is daily labor.'),
  dog('saluki', 'Saluki', 'large', '40-65 lb (18-29 kg)', '12-14 years',
    ['Cancer risk conversations', 'Heart screening needs', 'Sensitivity to anesthesia', 'Autoimmune issues', 'Thin skin injuries'],
    'Feathering needs brush-outs.',
    'Desert sighthound; soft beds and careful drug dosing.'),
  dog('ibizan-hound', 'Ibizan Hound', 'large', '45-50 lb (20-23 kg)', '11-14 years',
    ['Allergies', 'Deafness risk', 'Axonal dystrophy rare reports', 'Hip dysplasia', 'Eye issues'],
    'Short or wire coat.',
    'Rabbit hunter; huge vertical jump means fence height matters.'),
  dog('pharaoh-hound', 'Pharaoh Hound', 'medium', '45-55 lb (20-25 kg)', '11-14 years',
    ['Allergies', 'Demodex risk', 'Patellar luxation', 'Hip dysplasia', 'Anesthesia sensitivity notes'],
    'Short coat; blushes when excited.',
    'Keen hunter; surprisingly sensitive skin for a short coat.'),
  dog('norwegian-elkhound', 'Norwegian Elkhound', 'medium', '48-55 lb (22-25 kg)', '12-15 years',
    ['Hip dysplasia', 'Progressive retinal atrophy (PRA)', 'Fanconi-like syndrome risk', 'Hypothyroidism', 'Kidney disease risk'],
    'Dense grey coat shed.',
    'Spitz hunter; metabolic and eye issues appear in breed notes.'),
  dog('finnish-spitz', 'Finnish Spitz', 'medium', '20-33 lb (9-15 kg)', '13-15 years',
    ['Hip dysplasia', 'Patellar luxation', 'Epilepsy risk', 'Eye issues', 'Diabetes risk'],
    'Fox-like coat brush-outs.',
    'Bark pointer; expect vocal living.'),
  dog('keeshond', 'Keeshond', 'medium', '35-45 lb (16-20 kg)', '12-15 years',
    ['Hip dysplasia', 'Primary hyperparathyroidism risk', 'Heart disease screening', 'Epilepsy risk', 'Skin issues'],
    'Fluffy coat mats without brushing.',
    'Barge dog companion; endocrine quirks show up in breed health.'),
  dog('schipperke', 'Schipperke', 'small', '10-16 lb (4.5-7 kg)', '13-15 years',
    ['Legg-Calve-Perthes risk', 'Dental disease', 'MPS IIIb risk', 'Hypothyroidism', 'Eye issues'],
    'Fox coat; seasonal shed.',
    'Little captain; genetic disease testing exists in serious breeding programs.'),
  dog('swedish-vallhund', 'Swedish Vallhund', 'small', '20-35 lb (9-16 kg)', '12-15 years',
    ['Retinopathy risk', 'Hip dysplasia', 'Intervertebral disc disease (IVDD) risk', 'Patellar luxation', 'Allergies'],
    'Harsh coat.',
    'Viking corgi cousin; eye disease is a known breed topic.'),
  dog('finnish-lapphund', 'Finnish Lapphund', 'medium', '33-53 lb (15-24 kg)', '12-15 years',
    ['Hip dysplasia', 'Progressive retinal atrophy (PRA)', 'Pompe disease risk', 'Epilepsy risk', 'Allergies'],
    'Thick coat.',
    'Reindeer herder; PRA testing common in breed clubs.'),
  dog('icelandic-sheepdog', 'Icelandic Sheepdog', 'medium', '20-30 lb (9-14 kg)', '12-14 years',
    ['Hip dysplasia', 'Patellar luxation', 'Eye issues', 'Cryptorchidism risk', 'Allergies'],
    'Double coat shed.',
    'Vocal Nordic herder; hips and eyes on the watch list.'),
  dog('portuguese-water-dog', 'Portuguese Water Dog', 'medium', '35-60 lb (16-27 kg)', '11-13 years',
    ['Hip dysplasia', 'GM1 storage disease risk', 'JDCM cardiac risk', 'Progressive retinal atrophy (PRA)', 'Addison risk'],
    'Curly or wavy coat clips.',
    'Working water dog; genetic cardiac and storage disease testing exists.'),
  dog('spanish-water-dog', 'Spanish Water Dog', 'medium', '31-49 lb (14-22 kg)', '12-14 years',
    ['Hip dysplasia', 'Progressive retinal atrophy (PRA)', 'Hypothyroidism', 'Allergies', 'Ear infections'],
    'Wool coat corded or clipped.',
    'Versatile herder/hunter; PRA appears in breed testing.'),
  dog('barbet', 'Barbet', 'medium', '35-65 lb (16-29 kg)', '13-15 years',
    ['Hip dysplasia', 'Ear infections', 'Progressive retinal atrophy (PRA)', 'Elbow dysplasia', 'Allergies'],
    'Woolly coat high maintenance.',
    'French water dog; ears under coat hide infection.'),
  dog('lagotto-romagnolo', 'Lagotto Romagnolo', 'medium', '24-35 lb (11-16 kg)', '15-17 years',
    ['Hip dysplasia', 'Juvenile epilepsy risk', 'Storage disease risk', 'Lysosomal storage testing themes', 'Allergies'],
    'Curly truffle coat clips.',
    'Truffle dog; juvenile epilepsy is a known breed discussion.'),
  dog('wirehaired-pointing-griffon', 'Wirehaired Pointing Griffon', 'medium', '50-70 lb (23-32 kg)', '12-14 years',
    ['Hip dysplasia', 'Ear infections', 'Eye issues', 'Hypothyroidism', 'Allergies'],
    'Wiry coat handwork.',
    'Versatile gun dog; ear care after water work.'),
  dog('german-shorthaired-pointer', 'German Shorthaired Pointer', 'large', '45-70 lb (20-32 kg)', '10-12 years',
    ['Hip dysplasia', 'Lymphedema risk', 'Von Willebrand risk', 'Eye issues', 'Bloat (GDV) risk'],
    'Short coat.',
    'High-octane gun dog; needs serious exercise.'),
  dog('german-wirehaired-pointer', 'German Wirehaired Pointer', 'large', '50-70 lb (23-32 kg)', '14-16 years',
    ['Hip dysplasia', 'Hypothyroidism', 'Ear infections', 'Eye issues', 'Bloat (GDV) risk'],
    'Wire coat care.',
    'Tough versatile hunter; coat and ears after fieldwork.'),
  dog('spinone-italiano', 'Spinone Italiano', 'large', '61-86 lb (28-39 kg)', '10-12 years',
    ['Hip dysplasia', 'Cerebellar ataxia risk', 'Bloat (GDV)', 'Entropion', 'Hypothyroidism'],
    'Wire coat; beard hygiene.',
    'Patient gun dog; ataxia testing in breed programs.'),
  dog('bracco-italiano', 'Bracco Italiano', 'large', '55-90 lb (25-41 kg)', '10-14 years',
    ['Hip dysplasia', 'Ear infections', 'Eyelid issues', 'Kidney issues rare reports', 'Bloat (GDV) risk'],
    'Short coat; ear care.',
    'Ancient pointer; ears and lids need watching.'),
  dog('catahoula-leopard-dog', 'Catahoula Leopard Dog', 'large', '50-95 lb (23-43 kg)', '10-14 years',
    ['Hip dysplasia', 'Deafness risk (especially double merle)', 'Eye anomalies', 'Cruciate injury', 'Allergies'],
    'Short coat.',
    'Working cur; merle breeding mistakes cause deafness/eye risk.'
    ),
  dog('australian-cattle-dog', 'Australian Cattle Dog', 'medium', '30-50 lb (14-23 kg)', '12-16 years',
    ['Hip dysplasia', 'Progressive retinal atrophy (PRA)', 'Deafness risk', 'Elbow dysplasia', 'High-drive soft tissue injuries'],
    'Weatherproof coat; seasonal shed.',
    'Heelers invent jobs; deafness and PRA are breed-known.'),
  dog('australian-kelpie', 'Australian Kelpie', 'medium', '31-46 lb (14-21 kg)', '10-14 years',
    ['Hip dysplasia', 'Progressive retinal atrophy (PRA)', 'Collie eye anomaly risk', 'High-drive injuries', 'Allergies'],
    'Short coat.',
    'Farm rocket; not a couch potato.'),
  dog('mudi', 'Mudi', 'medium', '18-29 lb (8-13 kg)', '13-14 years',
    ['Hip dysplasia', 'Epilepsy risk', 'Eye issues', 'Patellar luxation', 'Allergies'],
    'Wavy/curly coat.',
    'Hungarian herder; rare breed epilepsy notes exist.'),
  dog('pumi', 'Pumi', 'medium', '22-29 lb (10-13 kg)', '12-13 years',
    ['Hip dysplasia', 'Primary lens luxation risk', 'Degenerative myelopathy risk', 'Patellar luxation', 'Allergies'],
    'Curly coat clips.',
    'Talkative Hungarian herder; lens luxation is discussed in breed.'),
  dog('pulik', 'Puli', 'medium', '25-35 lb (11-16 kg)', '10-15 years',
    ['Hip dysplasia', 'Degenerative myelopathy risk', 'Eye issues', 'Allergies', 'Hot spots under cords'],
    'Corded coat specialist care.',
    'Corded herder; skin under cords hides problems.'),
  dog('bergamasco', 'Bergamasco Sheepdog', 'large', '57-84 lb (26-38 kg)', '13-15 years',
    ['Hip dysplasia', 'Eye issues', 'Bloat (GDV) risk', 'Skin under flocks', 'Allergies'],
    'Flocked coat unique care.',
    'Italian herder; coat flocks need knowledgeable owners.'),
  dog('entlebucher-mountain-dog', 'Entlebucher Mountain Dog', 'medium', '40-55 lb (18-25 kg)', '11-13 years',
    ['Hip dysplasia', 'Progressive retinal atrophy (PRA)', 'Ectopic ureter risk', 'Hemolytic anemia risk', 'Allergies'],
    'Short tricolor coat.',
    'Smallest Swiss mountain dog; urinary ectopic ureter appears in breed.'),
  dog('appenzeller-sennenhund', 'Appenzeller Sennenhund', 'medium', '48-70 lb (22-32 kg)', '12-14 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Eye issues', 'High-drive injuries', 'Bloat (GDV) risk'],
    'Short double coat.',
    'Agile Swiss herder; needs work.'),
  dog('greater-swiss-mountain-dog', 'Greater Swiss Mountain Dog', 'giant', '85-140 lb (39-64 kg)', '8-11 years',
    ['Hip dysplasia', 'Elbow dysplasia', 'Gastric dilatation risk', 'Osteosarcoma risk', 'Lick granuloma / boredom issues'],
    'Short coat; heavy shed.',
    'Draft dog; joint and GDV vigilance.'),
  dog('cardigan-welsh-corgi', 'Cardigan Welsh Corgi', 'small', '25-38 lb (11-17 kg)', '12-15 years',
    ['Intervertebral disc disease (IVDD)', 'Progressive retinal atrophy (PRA)', 'Hip dysplasia', 'Degenerative myelopathy risk', 'Obesity'],
    'Double coat shed.',
    'Longer-tailed corgi; same spinal weight rules as Pembroke.'),
  dog('norwegian-buhund', 'Norwegian Buhund', 'medium', '26-40 lb (12-18 kg)', '12-15 years',
    ['Hip dysplasia', 'Hereditary cataracts risk', 'Fanconi risk reports', 'Epilepsy risk', 'Allergies'],
    'Spitz coat shed.',
    'Farm spitz; cataracts discussed in breed.'),
  dog('danish-swedish-farmdog', 'Danish-Swedish Farmdog', 'small', '15-20 lb (7-9 kg)', '11-13 years',
    ['Hip dysplasia', 'Patellar luxation', 'Dental disease', 'Allergies', 'Eye issues'],
    'Short coat.',
    'Compact farm companion; still building deep health datasets.'
    ),
  dog('rat-terrier', 'Rat Terrier', 'small', '10-25 lb (4.5-11 kg)', '12-18 years',
    ['Patellar luxation', 'Dental disease', 'Allergies', 'Legg-Calve-Perthes risk', 'Heart murmurs'],
    'Short coat.',
    'American farm terrier; long-lived with dental care.'),
  dog('toy-fox-terrier', 'Toy Fox Terrier', 'toy', '3.5-7 lb (1.6-3.2 kg)', '13-15 years',
    ['Patellar luxation', 'Dental disease', 'Legg-Calve-Perthes risk', 'Demodex risk', 'Hypoglycemia risk young'],
    'Short coat.',
    'Tiny hunter; fragile legs and teeth.'),
  dog('smooth-fox-terrier', 'Smooth Fox Terrier', 'small', '15-20 lb (7-9 kg)', '12-15 years',
    ['Deafness risk', 'Patellar luxation', 'Eye lens luxation risk', 'Allergies', 'Dental disease'],
    'Short coat.',
    'Classic earthdog; deafness can appear.'),
  dog('wire-fox-terrier', 'Wire Fox Terrier', 'small', '15-20 lb (7-9 kg)', '12-15 years',
    ['Patellar luxation', 'Eye lens luxation risk', 'Allergies', 'Dental disease', 'Legg-Calve-Perthes risk'],
    'Wire coat strip.',
    'Same job as Smooth with jacket care.'),
  dog('lakeland-terrier', 'Lakeland Terrier', 'small', '15-17 lb (7-8 kg)', '12-15 years',
    ['Legg-Calve-Perthes risk', 'Patellar luxation', 'Eye issues', 'Dental disease', 'Allergies'],
    'Wire coat.',
    'Fell terrier; compact and busy.'),
  dog('welsh-terrier', 'Welsh Terrier', 'small', '20 lb (9 kg)', '12-15 years',
    ['Primary lens luxation risk', 'Allergy skin disease', 'Dental disease', 'Patellar luxation', 'Hip dysplasia'],
    'Wire coat.',
    'Compact Airedale lookalike; lens luxation watch.'),
  dog('irish-terrier', 'Irish Terrier', 'medium', '25-27 lb (11-12 kg)', '13-15 years',
    ['Hyperkeratosis risk', 'Cystinuria risk', 'Hip dysplasia', 'Allergies', 'Dental disease'],
    'Wire coat.',
    'Daredevil terrier; footpad hyperkeratosis known in breed.'),
  dog('kerry-blue-terrier', 'Kerry Blue Terrier', 'medium', '33-40 lb (15-18 kg)', '12-15 years',
    ['Hip dysplasia', 'Eye issues', 'Spiculosis risk', 'Hypothyroidism', 'Soft tissue cancers risk talks'],
    'Soft wavy coat clips.',
    'Irish farm terrier; coat never stops growing.'),
  dog('bedlington-terrier', 'Bedlington Terrier', 'small', '17-23 lb (8-10 kg)', '11-16 years',
    ['Copper toxicosis risk', 'Eye issues', 'Patellar luxation', 'Kidney disease risk', 'Dental disease'],
    'Lamb coat clips.',
    'Copper storage disease is a defining breed medical topic.'),
  dog('dandie-dinmont-terrier', 'Dandie Dinmont Terrier', 'small', '18-24 lb (8-11 kg)', '12-15 years',
    ['Intervertebral disc disease (IVDD) risk', 'Glaucoma risk', 'Hip dysplasia', 'Hypothyroidism', 'Dental disease'],
    'Unique topknot coat care.',
    'Long-backed terrier; glaucoma and spine awareness.'),
  dog('skye-terrier', 'Skye Terrier', 'medium', '25-40 lb (11-18 kg)', '12-14 years',
    ['Orthopedic disease risk', 'Cancer risk talks', 'Dental disease', 'Allergies', 'Ear infections under coat'],
    'Floor-length coat specialist care.',
    'Rare long-coated terrier; coat hides skin and ear disease.'),
  dog('cesky-terrier', 'Cesky Terrier', 'small', '14-24 lb (6-11 kg)', '12-15 years',
    ['Scottie cramp risk', 'Dental disease', 'Allergies', 'Patellar luxation', 'Heart screening needs'],
    'Silky clip coat.',
    'Czech hunting terrier; cramping syndrome discussed.'),
  dog('sealyham-terrier', 'Sealyham Terrier', 'small', '23-24 lb (10-11 kg)', '12-14 years',
    ['Primary lens luxation risk', 'Dental disease', 'Allergies', 'Deafness risk', 'Patellar luxation'],
    'Wire coat.',
    'Low white terrier; lens luxation is key.'),
  dog('glen-of-imaal-terrier', 'Glen of Imaal Terrier', 'small', '32-40 lb (14.5-18 kg)', '10-14 years',
    ['Progressive retinal atrophy (PRA)', 'Hip dysplasia', 'Allergies', 'Dental disease', 'Wobbler rare reports'],
    'Wiry coat.',
    'Irish big-boned terrier; PRA testing common.'),
  dog('american-hairless-terrier', 'American Hairless Terrier', 'small', '12-16 lb (5-7 kg)', '14-16 years',
    ['Skin sunburn risk', 'Allergies', 'Patellar luxation', 'Dental disease', 'Legg-Calve-Perthes risk'],
    'Skin care instead of coat; sunscreen as advised.',
    'Hairless or coated varieties; UV protection for hairless.'),
  dog('chinese-crested', 'Chinese Crested', 'toy', '8-12 lb (3.5-5.5 kg)', '13-18 years',
    ['Dental disease', 'Patellar luxation', 'Legg-Calve-Perthes risk', 'Skin issues', 'Progressive retinal atrophy (PRA)'],
    'Hairless skin care or powderpuff coat care.',
    'Hairless needs climate and dental vigilance.'),
  dog('xoloitzcuintli', 'Xoloitzcuintli', 'medium', '10-60 lb (4.5-27 kg)', '13-18 years',
    ['Dental disease', 'Acne-like skin issues', 'Patellar luxation', 'Heart screening needs', 'Sunburn risk'],
    'Hairless skin oil balance; coated variety sheds less.',
    'Ancient hairless; sizes toy to standard vary risks.'),
  dog('peruvian-inca-orchid', 'Peruvian Inca Orchid', 'medium', '8-55 lb (3.5-25 kg)', '12-14 years',
    ['Dental disease', 'Skin issues', 'Patellar luxation', 'Sunburn risk', 'Allergies'],
    'Hairless skin care.',
    'Another hairless sighthound-ish companion; dental and UV care.'
    ),
  dog('thai-ridgeback', 'Thai Ridgeback', 'large', '35-75 lb (16-34 kg)', '12-13 years',
    ['Hip dysplasia', 'Dermoid sinus risk', 'Allergies', 'Mouth tumors risk talks', 'Thin skin injuries'],
    'Short coat.',
    'Independent ridgeback; dermoid sinus like Rhodesian discussions.'),
  dog('azawakh', 'Azawakh', 'large', '33-55 lb (15-25 kg)', '12-15 years',
    ['Hypothyroidism', 'Seizures risk talks', 'Sensitivity to anesthesia', 'Muscle injuries', 'Thin skin'],
    'Ultra-short coat; cold protection.',
    'West African sighthound; lean body is normal, not underweight by Lab standards.'),
  dog('sloughi', 'Sloughi', 'large', '35-50 lb (16-23 kg)', '10-15 years',
    ['Progressive retinal atrophy (PRA)', 'Sensitivity notes', 'Hypothyroidism', 'Gastric issues', 'Thin skin'],
    'Short coat.',
    'North African sighthound; PRA testing in clubs.'),
  dog('cirneco-dell-etna', 'Cirneco dell\'Etna', 'medium', '17-26 lb (8-12 kg)', '12-14 years',
    ['Patellar luxation', 'Eye issues', 'Allergies', 'Dental disease', 'Thin skin injuries'],
    'Short coat.',
    'Sicilian rabbit hunter; rare breed sparse data.'
    ),
  dog('podenco', 'Podenco (type)', 'medium', '20-55 lb (9-25 kg)', '12-14 years',
    ['Allergies', 'Dental disease', 'Ear issues', 'Thin skin injuries', 'High-drive soft tissue injuries'],
    'Short or wire coat.',
    'Spanish warren hound type label; individuals vary.'
    ),
  dog('carolina-dog', 'Carolina Dog', 'medium', '30-65 lb (14-29 kg)', '12-14 years',
    ['Dental disease', 'Parasite exposure if free-roaming history', 'Allergies', 'Hip dysplasia', 'Ear infections'],
    'Short coat.',
    'Primitive village dog type; health data still emerging.'
    ),
  dog('canaan-dog', 'Canaan Dog', 'medium', '35-55 lb (16-25 kg)', '12-13 years',
    ['Hip dysplasia', 'Progressive retinal atrophy (PRA)', 'Hypothyroidism', 'Allergies', 'Elbow dysplasia'],
    'Short double coat.',
    'Israeli pariah breed; reserved and territorial.'),
  dog('new-guinea-singing-dog', 'New Guinea Singing Dog', 'small', '17-30 lb (8-14 kg)', '15-20 years',
    ['Dental disease', 'Limited clinical dataset', 'Parasite risk if wild-type husbandry', 'Allergies', 'Reproductive quirks'],
    'Fox-like coat.',
    'Rare; clinical norms poorly standardized.'
    ),

  // Cats (~50 to push toward 220 total)
  cat('persian', 'Persian', 'medium', '7-12 lb (3-5.5 kg)', '10-15 years',
    ['Brachycephalic airway concerns', 'Polycystic kidney disease (PKD) risk', 'Dental disease', 'Eye tear drainage issues', 'Heat intolerance'],
    'Daily coat brushing; face cleaning.',
    'Quiet lap cat; PKD screening conversations are breed-normal.'),
  cat('maine-coon', 'Maine Coon', 'large', '9-18 lb (4-8 kg)', '10-13 years',
    ['Hypertrophic cardiomyopathy (HCM) risk', 'Hip dysplasia', 'Spinal muscular atrophy risk', 'Dental disease', 'Obesity if indoor-idle'],
    'Long coat 2-3x weekly brush.',
    'Dog-like gentle giant cat; HCM screening is a breed staple.'),
  cat('ragdoll', 'Ragdoll', 'large', '10-20 lb (4.5-9 kg)', '12-17 years',
    ['Hypertrophic cardiomyopathy (HCM) risk', 'Obesity', 'Urinary issues', 'Dental disease', 'Joint strain if overweight'],
    'Semi-long coat brush weekly.',
    'Relaxed companion; HCM and weight control dominate adult care.'),
  cat('siamese', 'Siamese', 'medium', '8-14 lb (3.5-6.5 kg)', '11-15 years',
    ['Dental disease', 'Amyloidosis risk', 'Asthma / respiratory sensitivity', 'Progressive retinal atrophy risk talks', 'Hyperesthesia reports'],
    'Short coat; weekly wipe.',
    'Vocal, people-oriented; dental disease often early.'),
  cat('bengal', 'Bengal', 'medium', '8-15 lb (3.5-7 kg)', '12-16 years',
    ['Hypertrophic cardiomyopathy (HCM) risk', 'Progressive retinal atrophy (PRA-b) risk', 'Flat-chested kitten syndrome rare', 'Urinary issues', 'High-energy soft tissue strain'],
    'Short glitter coat; weekly brush.',
    'High-drive athletic cat; needs vertical space and play.'),
  cat('british-shorthair', 'British Shorthair', 'medium', '9-17 lb (4-8 kg)', '12-17 years',
    ['Hypertrophic cardiomyopathy (HCM) risk', 'Obesity', 'Dental disease', 'Polycystic kidney disease risk in some lines', 'Joint strain if heavy'],
    'Dense coat weekly brush.',
    'Easygoing; calories and HCM screening matter.'),
  cat('scottish-fold', 'Scottish Fold', 'medium', '6-13 lb (2.7-6 kg)', '11-15 years',
    ['Osteochondrodysplasia (fold ear cartilage disease)', 'Arthritis secondary to cartilage dysplasia', 'Hypertrophic cardiomyopathy (HCM) risk', 'Dental disease', 'Obesity'],
    'Coat varies; joint comfort over aesthetics.',
    'Fold ears come with cartilage disease risk; many clinics urge caution.'
    ),
  cat('sphynx', 'Sphynx', 'medium', '6-12 lb (2.7-5.5 kg)', '8-14 years',
    ['Hypertrophic cardiomyopathy (HCM) risk', 'Skin oil / yeast issues', 'Dental disease', 'Temperature sensitivity', 'Urinary issues'],
    'Bathe/wipe skin; no coat insulation.',
    'Hairless companion; HCM and skin care are the job.'),
  cat('abyssinian', 'Abyssinian', 'medium', '6-10 lb (2.7-4.5 kg)', '9-15 years',
    ['Progressive retinal atrophy risk', 'Renal amyloidosis risk', 'Dental disease', 'Patellar luxation', 'Hyperesthesia reports'],
    'Short coat.',
    'Busy athlete; kidney amyloidosis is a historical breed concern.'),
  cat('somali', 'Somali', 'medium', '6-12 lb (2.7-5.5 kg)', '11-16 years',
    ['Dental disease', 'Renal amyloidosis risk', 'Progressive retinal atrophy risk', 'Allergies', 'Obesity less common than couch breeds'],
    'Semi-long coat brush.',
    'Aby with a coat; similar medical themes.'),
  cat('devon-rex', 'Devon Rex', 'small', '5-10 lb (2.3-4.5 kg)', '9-15 years',
    ['Hypertrophic cardiomyopathy (HCM) risk', 'Patellar luxation', 'Hereditary myopathy risk', 'Dental disease', 'Skin oil issues'],
    'Wave coat sparse; skin care.',
    'Pixie-faced acrobat; HCM and muscle disease talks exist.'),
  cat('cornish-rex', 'Cornish Rex', 'small', '6-10 lb (2.7-4.5 kg)', '11-15 years',
    ['Hypertrophic cardiomyopathy (HCM) risk', 'Patellar luxation', 'Dental disease', 'Skin irritation', 'Hypotrichosis-related chill'],
    'Thin coat; needs warmth.',
    'High-energy rex; heat-seeking on laptops is stereotype with truth.'),
  cat('oriental-shorthair', 'Oriental Shorthair', 'medium', '7-14 lb (3-6.5 kg)', '10-15 years',
    ['Dental disease', 'Amyloidosis risk', 'Liver issues talks', 'Asthma sensitivity', 'Hyperesthesia reports'],
    'Short coat.',
    'Siamese cousin; dental and amyloid themes.'),
  cat('birman', 'Birman', 'medium', '7-12 lb (3-5.5 kg)', '12-16 years',
    ['Hypertrophic cardiomyopathy (HCM) risk', 'Congenital hypotrichosis rare', 'Dental disease', 'Obesity', 'Kidney disease senior'],
    'Silky coat brush.',
    'Gentle colorpoint; HCM screening common.'),
  cat('norwegian-forest-cat', 'Norwegian Forest Cat', 'large', '9-16 lb (4-7 kg)', '12-16 years',
    ['Hypertrophic cardiomyopathy (HCM) risk', 'Glycogen storage disease IV risk', 'Hip dysplasia', 'Dental disease', 'Mats in pants coat'],
    'Thick coat; brush underskirt.',
    'Skogkatt; GSD IV testing in serious programs.'),
  cat('siberian', 'Siberian', 'large', '8-17 lb (3.5-8 kg)', '11-15 years',
    ['Hypertrophic cardiomyopathy (HCM) risk', 'Dental disease', 'Urinary issues', 'Obesity if idle', 'Mats in long coat'],
    'Triple coat seasonal care.',
    'Forest cat type; HCM screening; often marketed for allergy households (verify individually).'),
  cat('american-shorthair', 'American Shorthair', 'medium', '8-12 lb (3.5-5.5 kg)', '15-20 years',
    ['Hypertrophic cardiomyopathy (HCM) risk', 'Obesity', 'Dental disease', 'Polycystic kidney disease rare', 'Urinary crystals'],
    'Short coat weekly.',
    'Working-cat heritage; easy keeper who gains weight fast.'),
  cat('exotic-shorthair', 'Exotic Shorthair', 'medium', '7-14 lb (3-6.5 kg)', '10-15 years',
    ['Brachycephalic concerns', 'Polycystic kidney disease (PKD) risk', 'Dental disease', 'Eye stain dermatitis', 'Heat intolerance'],
    'Dense coat; face cleaning.',
    'Persian in a short coat; same airway and PKD themes.'),
  cat('russian-blue', 'Russian Blue', 'medium', '7-12 lb (3-5.5 kg)', '15-20 years',
    ['Dental disease', 'Obesity if free-fed', 'Bladder issues', 'Allergies', 'Shy-stress cystitis risk'],
    'Silver coat weekly brush.',
    'Reserved; stress and urinary signs often travel together.'),
  cat('tonkinese', 'Tonkinese', 'medium', '6-12 lb (2.7-5.5 kg)', '10-16 years',
    ['Dental disease', 'Amyloidosis risk talks', 'Asthma sensitivity', 'Obesity less typical', 'Hyperesthesia reports'],
    'Short coat.',
    'Siamese-Burmese mix energy; dental vigilance.'),
  cat('burmese', 'Burmese', 'medium', '8-12 lb (3.5-5.5 kg)', '10-17 years',
    ['Diabetes risk', 'Hypokalemia risk (some lines)', 'Cranial deformities rare historical', 'Dental disease', 'Obesity'],
    'Short satin coat.',
    'People glue; diabetes risk higher in some populations.'),
  cat('bombay', 'Bombay', 'medium', '8-15 lb (3.5-7 kg)', '12-16 years',
    ['Dental disease', 'Hypertrophic cardiomyopathy (HCM) risk talks', 'Obesity', 'Respiratory noise if extreme face', 'Allergies'],
    'Short coat.',
    'Patent-leather Burmese type; watch weight.'),
  cat('chartreux', 'Chartreux', 'medium', '7-16 lb (3-7 kg)', '11-15 years',
    ['Patellar luxation', 'Dental disease', 'Polycystic kidney disease rare reports', 'Obesity', 'Joint strain'],
    'Woolly short coat.',
    'Quiet blue French cat; solid build hides weight gain.'),
  cat('turkish-angora', 'Turkish Angora', 'medium', '5-10 lb (2.3-4.5 kg)', '12-18 years',
    ['Deafness risk (especially white/blue-eyed)', 'Hypertrophic cardiomyopathy (HCM) risk talks', 'Dental disease', 'Ataxia rare genetic', 'Allergies'],
    'Semi-long coat.',
    'Elegant; deafness risk in white cats is classic.'),
  cat('turkish-van', 'Turkish Van', 'large', '7-15 lb (3-7 kg)', '12-17 years',
    ['Hypertrophic cardiomyopathy (HCM) risk talks', 'Dental disease', 'Obesity', 'Urinary issues', 'Coat mats on pants'],
    'Cashmere-like coat.',
    'Swimming stereotype aside, still needs HCM and dental plans.'),
  cat('manx', 'Manx', 'medium', '8-12 lb (3.5-5.5 kg)', '8-14 years',
    ['Manx syndrome (spinal/neural tube issues)', 'Arthritis secondary to sacral issues', 'Dental disease', 'Obesity', 'Constipation risk'],
    'Coat varies.',
    'Tailless gene can affect spine; ethical breeding avoids extremes.'
    ),
  cat('cymric', 'Cymric', 'medium', '8-13 lb (3.5-6 kg)', '8-14 years',
    ['Manx syndrome risk', 'Arthritis', 'Dental disease', 'Obesity', 'Mats in long coat'],
    'Long coat brush.',
    'Longhaired Manx type; same spinal caveats.'
    ),
  cat('japanese-bobtail', 'Japanese Bobtail', 'medium', '6-10 lb (2.7-4.5 kg)', '9-15 years',
    ['Dental disease', 'Patellar luxation', 'Allergies', 'Tail trauma rare', 'Obesity if idle'],
    'Coat varies.',
    'Pom-pom tail natural; generally hardy with dental care.'),
  cat('american-curl', 'American Curl', 'medium', '5-10 lb (2.3-4.5 kg)', '12-16 years',
    ['Ear cartilage care (not infection by default)', 'Dental disease', 'Patellar luxation', 'Hypertrophic cardiomyopathy (HCM) talks', 'Allergies'],
    'Coat varies; handle curled ears gently.',
    'Ears curl back; clean carefully without forcing.'),
  cat('american-bobtail', 'American Bobtail', 'large', '7-16 lb (3-7 kg)', '11-15 years',
    ['Hip dysplasia', 'Dental disease', 'Obesity', 'Allergies', 'Tail sensitivity'],
    'Shaggy coat brush.',
    'Bobbed working look; hips and weight matter.'),
  cat('himalayan', 'Himalayan', 'medium', '7-14 lb (3-6.5 kg)', '9-15 years',
    ['Polycystic kidney disease (PKD) risk', 'Brachycephalic concerns', 'Dental disease', 'Eye stain dermatitis', 'Heat intolerance'],
    'Long coat daily; face cleaning.',
    'Colorpoint Persian type; PKD and airway themes.'),
  cat('ragamuffin', 'RagaMuffin', 'large', '10-20 lb (4.5-9 kg)', '12-16 years',
    ['Hypertrophic cardiomyopathy (HCM) risk', 'Obesity', 'Dental disease', 'Urinary issues', 'Joint strain'],
    'Long coat brush.',
    'Related to Ragdoll history; weight and HCM watch.'),
  cat('nebelung', 'Nebelung', 'medium', '7-15 lb (3-7 kg)', '11-16 years',
    ['Dental disease', 'Obesity if indoor', 'Urinary stress cystitis', 'Allergies', 'Mats in pants'],
    'Blue long coat care.',
    'Reserved Russian Blue relative; shy stress shows in litter box.'),
  cat('egyptian-mau', 'Egyptian Mau', 'medium', '6-14 lb (2.7-6.5 kg)', '9-13 years',
    ['Leukodystrophy rare reports', 'Dental disease', 'Patellar luxation', 'Allergies', 'High-speed injuries'],
    'Spot coat weekly.',
    'Fast spotted athlete; enrichment prevents boredom damage.'),
  cat('ocicat', 'Ocicat', 'medium', '6-15 lb (2.7-7 kg)', '10-15 years',
    ['Dental disease', 'Gingivitis risk', 'Hypertrophic cardiomyopathy (HCM) talks', 'Obesity', 'Allergies'],
    'Short spotted coat.',
    'Dog-like spotted companion; dental disease common complaint.'),
  cat('savannah', 'Savannah', 'large', '12-25 lb (5.5-11 kg)', '12-20 years',
    ['Limited long-term clinical dataset by filial generation', 'Hypertrophic cardiomyopathy (HCM) talks', 'Dental disease', 'High-drive injuries', 'Urinary issues'],
    'Short coat.',
    'Hybrid serval descendant; husbandry and legality vary; health data incomplete.'
    ),
  cat('savannah-f4-plus', 'Savannah (F4+ pet type)', 'large', '10-20 lb (4.5-9 kg)', '12-18 years',
    ['Dental disease', 'Hypertrophic cardiomyopathy (HCM) talks', 'High-energy soft tissue strain', 'Urinary issues', 'Allergies'],
    'Short coat.',
    'Later-generation Savannahs are more cat-like; still high drive.'),
  cat('toyger', 'Toyger', 'medium', '7-15 lb (3-7 kg)', '10-15 years',
    ['Hypertrophic cardiomyopathy (HCM) talks', 'Dental disease', 'Obesity', 'Allergies', 'Urinary issues'],
    'Short coat.',
    'Tiger-striped domestic; still mostly domestic health patterns.'),
  cat('selkirk-rex', 'Selkirk Rex', 'medium', '7-16 lb (3-7 kg)', '10-15 years',
    ['Hypertrophic cardiomyopathy (HCM) risk', 'Polycystic kidney disease risk talks', 'Dental disease', 'Skin issues', 'Obesity'],
    'Curly coat brush gently.',
    'Large rex; HCM appears in breed discussions.'),
  cat('la-perm', 'LaPerm', 'medium', '5-10 lb (2.3-4.5 kg)', '10-15 years',
    ['Dental disease', 'Patellar luxation', 'Allergies', 'Hypertrophic cardiomyopathy (HCM) talks', 'Skin under curls'],
    'Curly coat care.',
    'Rex coat mutant; generally hardy with dental care.'),
  cat('lykoi', 'Lykoi', 'medium', '4-8 lb (1.8-3.6 kg)', '10-15 years',
    ['Dental disease', 'Skin/coat density issues', 'Limited long-term dataset', 'Allergies', 'Temperature sensitivity'],
    'Partial hairlessness care.',
    'Werewolf cat; newer breed, dataset still thin.'
    ),
  cat('minskin', 'Minskin', 'small', '4-8 lb (1.8-3.6 kg)', '10-14 years',
    ['Short-leg orthopedic stress', 'Dental disease', 'Skin care needs', 'Limited dataset', 'Temperature sensitivity'],
    'Sparse coat/skin care.',
    'Short-legged hairless mix; conformation risks.'
    ),
  cat('munchkin', 'Munchkin', 'small', '5-9 lb (2.3-4 kg)', '10-14 years',
    ['Lordosis / chest issues debated', 'Osteoarthritis risk', 'Dental disease', 'Obesity impact on short legs', 'Limited ethical consensus'],
    'Coat varies.',
    'Short legs are controversial; monitor mobility honestly.'
    ),
  cat('napoleon', 'Napoleon (Minuet)', 'small', '5-9 lb (2.3-4 kg)', '10-14 years',
    ['Short-leg orthopedic stress', 'Brachycephalic concerns from Persian influence', 'Dental disease', 'Polycystic kidney disease risk talks', 'Obesity'],
    'Coat varies; face cleaning if brachy.',
    'Munchkin x Persian type; stacked conformation risks.'
    ),
  cat('domestic-longhair', 'Domestic Longhair', 'medium', '8-15 lb (3.5-7 kg)', '12-18 years (indoor)',
    ['Dental disease', 'Obesity', 'Chronic kidney disease (senior)', 'Hyperthyroidism (senior)', 'Mats and skin undercoat issues'],
    'Daily to every-other-day brush to prevent mats.',
    'Mixed-breed longhair; same general feline senior diseases as DSH with coat labor.'),
  cat('siamese-mix', 'Siamese Mix', 'medium', '7-14 lb (3-6.5 kg)', '11-16 years',
    ['Dental disease', 'Asthma sensitivity', 'Amyloidosis risk talks if heavily Siamese', 'Obesity variable', 'Hyperesthesia reports'],
    'Short coat.',
    'Common shelter label; treat the individual, note Siamese-leaning risks.'),
  cat('calico-domestic', 'Calico Domestic (phenotype)', 'medium', '7-12 lb (3-5.5 kg)', '12-18 years',
    ['Dental disease', 'Obesity', 'Chronic kidney disease (senior)', 'Hyperthyroidism (senior)', 'Urinary issues'],
    'Coat length varies.',
    'Color pattern not a breed; health follows domestic baselines.'),
  cat('tuxedo-domestic', 'Tuxedo Domestic (phenotype)', 'medium', '8-14 lb (3.5-6.5 kg)', '12-18 years',
    ['Dental disease', 'Obesity', 'Chronic kidney disease (senior)', 'Hyperthyroidism (senior)', 'Urinary issues'],
    'Usually short coat.',
    'Pattern label; use domestic preventive care norms.'),

  // Pad to 220 with additional established breeds
  dog('english-bulldog', 'English Bulldog', 'medium', '40-50 lb (18-23 kg)', '8-10 years',
    ['Brachycephalic obstructive airway syndrome (BOAS)', 'Hip dysplasia', 'Skin fold dermatitis', 'Cherry eye', 'Heat intolerance'],
    'Daily fold cleaning.',
    'Same medical family as Bulldog entries; conformation limits exercise.'),
  dog('french-spaniel', 'French Spaniel', 'large', '44-60 lb (20-27 kg)', '10-14 years',
    ['Hip dysplasia', 'Ear infections', 'Eye issues', 'Allergies', 'Hypothyroidism'],
    'Medium coat and ear care.',
    'Continental gun dog; ears after fieldwork.'
    ),
  dog('field-spaniel', 'Field Spaniel', 'medium', '35-50 lb (16-23 kg)', '12-14 years',
    ['Hip dysplasia', 'Ear infections', 'Hypothyroidism', 'Eye issues', 'Allergies'],
    'Feathering brush-outs; ear cleaning.',
    'Quiet working spaniel; ear disease common.'),
  dog('sussex-spaniel', 'Sussex Spaniel', 'medium', '35-45 lb (16-20 kg)', '11-13 years',
    ['Intervertebral disc disease (IVDD) risk', 'Ear infections', 'Heart screening needs', 'Hip dysplasia', 'Obesity'],
    'Dense golden coat; ear care.',
    'Low long spaniel; weight and back management.'),
  dog('clumber-spaniel', 'Clumber Spaniel', 'large', '55-85 lb (25-39 kg)', '10-12 years',
    ['Hip dysplasia', 'Ear infections', 'Eye issues', 'Hypothyroidism', 'Obesity'],
    'Heavy coat and ears.',
    'Heavy spaniel; keep lean for joints.'),
  dog('irish-water-spaniel', 'Irish Water Spaniel', 'large', '45-65 lb (20-29 kg)', '12-13 years',
    ['Hip dysplasia', 'Ear infections', 'Hypothyroidism', 'Eye issues', 'Allergies'],
    'Dense curly coat clips.',
    'Rat-tail water dog; ears under curls hide infection.'),
  dog('american-water-spaniel', 'American Water Spaniel', 'medium', '25-45 lb (11-20 kg)', '10-14 years',
    ['Hip dysplasia', 'Ear infections', 'Eye issues', 'Hypothyroidism', 'Allergies'],
    'Curly coat care.',
    'Compact US water dog; ear vigilance.'),
  dog('boykin-spaniel', 'Boykin Spaniel', 'medium', '25-40 lb (11-18 kg)', '10-14 years',
    ['Hip dysplasia', 'Exercise-induced collapse risk talks', 'Ear infections', 'Eye issues', 'Allergies'],
    'Wavy coat; ear cleaning.',
    'South Carolina gun dog; EIC discussions appear in breed.'),
  dog('nova-scotia-duck-tolling-retriever', 'Nova Scotia Duck Tolling Retriever', 'medium', '35-50 lb (16-23 kg)', '12-14 years',
    ['Hip dysplasia', 'Progressive retinal atrophy (PRA)', 'Autoimmune thyroid risk', 'Addison disease risk', 'Collie eye anomaly risk'],
    'Medium coat brush.',
    'Toller; autoimmune and eye themes in breed health.'),
  dog('chesapeake-bay-retriever', 'Chesapeake Bay Retriever', 'large', '55-80 lb (25-36 kg)', '10-13 years',
    ['Hip dysplasia', 'Progressive retinal atrophy (PRA)', 'Exercise-induced collapse risk', 'Hypothyroidism', 'Bloat (GDV) risk'],
    'Oily water coat; brush.',
    'Tough water retriever; EIC and PRA testing common.'),
  dog('flat-coated-retriever', 'Flat-Coated Retriever', 'large', '55-80 lb (25-36 kg)', '8-10 years',
    ['Cancer risk (breed-associated)', 'Hip dysplasia', 'Glaucoma risk', 'Bloat (GDV) risk', 'Ear infections'],
    'Flat coat brush-outs.',
    'Optimistic retriever; cancer vigilance is breed-defining.'),
  dog('curly-coated-retriever', 'Curly-Coated Retriever', 'large', '60-95 lb (27-43 kg)', '10-12 years',
    ['Hip dysplasia', 'Glycogen storage disease risk', 'Eye issues', 'Cancer risk talks', 'Bloat (GDV) risk'],
    'Curl coat care.',
    'Oldest retriever type; storage disease testing exists.'),
  dog('gordon-setter', 'Gordon Setter', 'large', '45-80 lb (20-36 kg)', '10-12 years',
    ['Hip dysplasia', 'Progressive retinal atrophy (PRA)', 'Hypothyroidism', 'Cerebellar degeneration risk', 'Bloat (GDV) risk'],
    'Long black-tan coat.',
    'Stylish setter; PRA and hip programs in clubs.'),
  dog('english-setter', 'English Setter', 'large', '45-80 lb (20-36 kg)', '11-12 years',
    ['Hip dysplasia', 'Deafness risk', 'Hypothyroidism', 'Allergies', 'Ear infections'],
    'Feathering mats without brushing.',
    'Gentleman gun dog; deafness can appear.'),
  dog('irish-red-and-white-setter', 'Irish Red and White Setter', 'large', '50-75 lb (23-34 kg)', '11-13 years',
    ['Hip dysplasia', 'Canine leukocyte adhesion deficiency risk', 'Progressive retinal atrophy (PRA)', 'Hypothyroidism', 'Bloat (GDV) risk'],
    'Feathered coat care.',
    'CLAD testing historically important in setters.'),
];

export function dogVaccineSchedule() {
  return [
    { vaccine: 'DA2PP / DHPP (distemper, adenovirus, parvovirus, parainfluenza)', age_weeks: 8 },
    { vaccine: 'DA2PP / DHPP booster', age_weeks: 12 },
    { vaccine: 'DA2PP / DHPP booster (complete series at or after 16 weeks)', age_weeks: 16 },
    { vaccine: 'Rabies (per local law; typically first dose at or after 12 weeks)', age_weeks: 16 },
  ];
}

export function catVaccineSchedule() {
  return [
    { vaccine: 'FVRCP (feline viral rhinotracheitis, calicivirus, panleukopenia)', age_weeks: 8 },
    { vaccine: 'FVRCP booster', age_weeks: 12 },
    { vaccine: 'FVRCP booster (complete kitten series)', age_weeks: 16 },
    { vaccine: 'Rabies (per local law; typically at or after 12 weeks)', age_weeks: 16 },
  ];
}
