import { forwardRef } from 'react';
import { createPortal } from 'react-dom';
import type { VetVisitExportData } from '@/services/vetVisitExport/buildVetVisitExportData';
import { formatVetVisitRecordLine } from '@/services/vetVisitExport/buildVetVisitExportData';
import type { HealthRecord } from '@/services/healthRecords/healthRecordTypes';
import styles from './VetVisitExportSheet.module.css';

type VetVisitExportSheetProps = {
  data: VetVisitExportData;
};

export const VetVisitExportSheet = forwardRef<HTMLDivElement, VetVisitExportSheetProps>(
  function VetVisitExportSheet({ data }, ref) {
    const sheet = (
      <div ref={ref} className={styles.sheet} aria-hidden="true">
        <header className={styles.header}>
          <p className={styles.kicker}>PetClues · Prepare for a vet visit</p>
          <h1 className={styles.title}>{data.petName}</h1>
          <p className={styles.meta}>
            {data.species} · {data.breed} · {data.age}
          </p>
          <p className={styles.generated}>Prepared {data.generatedAtLabel}</p>
        </header>

        <p className={styles.summary}>
          Summary exported from your PetClues records for an upcoming veterinary visit. Not a
          diagnosis — confirm details with your clinic.
        </p>

        <RecordBlock title="Vaccination history" records={data.vaccinations} />
        <RecordBlock title="Current medications" records={data.medications} />
        <RecordBlock title="Known allergies" records={data.allergies} critical />

        <section className={styles.block}>
          <h2 className={styles.blockTitle}>Weight trend · last 90 days</h2>
          <p className={styles.weightSummary}>{data.weightTrend.summary}</p>
          {data.weightTrend.points.length === 0 ? (
            <p className={styles.empty}>No dated weight entries in this window.</p>
          ) : (
            <table className={styles.weightTable}>
              <thead>
                <tr>
                  <th scope="col">Date</th>
                  <th scope="col">Weight</th>
                  <th scope="col">Source</th>
                </tr>
              </thead>
              <tbody>
                {data.weightTrend.points.map((point) => (
                  <tr key={point.id}>
                    <td>{point.dateLabel}</td>
                    <td>{point.value}</td>
                    <td>{point.source === 'check-in' ? 'Daily check-in' : 'Health record'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </section>

        <section className={styles.block}>
          <h2 className={styles.blockTitle}>Recent symptom logs · last 90 days</h2>
          {data.symptomLogs.length === 0 ? (
            <p className={styles.empty}>No structured symptom logs in the last 90 days.</p>
          ) : (
            <div>
              {data.symptomLogs.map((log) => (
                <article key={log.id} className={styles.noteItem}>
                  <p className={styles.noteDate}>{log.dateLabel}</p>
                  <p className={styles.noteTitle}>
                    {log.symptoms.length > 0 ? log.symptoms.join(', ') : 'Symptom log'}
                  </p>
                  <p className={styles.noteDetail}>{log.summary}</p>
                  {log.hasPhoto && <p className={styles.noteDetail}>Photo attached in PetClues.</p>}
                </article>
              ))}
            </div>
          )}
        </section>

        <section className={styles.block}>
          <h2 className={styles.blockTitle}>Recent wellness notes · last 90 days</h2>
          {data.wellnessNotes.length === 0 ? (
            <p className={styles.empty}>No wellness notes recorded in the last 90 days.</p>
          ) : (
            <div>
              {data.wellnessNotes.map((note) => (
                <article key={note.id} className={styles.noteItem}>
                  <p className={styles.noteDate}>{note.dateLabel}</p>
                  <p className={styles.noteTitle}>{note.title}</p>
                  {note.detail && <p className={styles.noteDetail}>{note.detail}</p>}
                </article>
              ))}
            </div>
          )}
        </section>

        <footer className={styles.footer}>
          Generated by PetClues for {data.petName}&apos;s veterinary visit · {data.generatedAtLabel}
          <p className={styles.disclaimer}>
            For informational use only. PetClues does not provide medical advice. Bring original
            records or lab results when your clinic requests them.
          </p>
        </footer>
      </div>
    );

    return createPortal(sheet, document.body);
  },
);

function RecordBlock({
  title,
  records,
  critical = false,
}: {
  title: string;
  records: HealthRecord[];
  critical?: boolean;
}) {
  return (
    <section className={`${styles.block} ${critical ? styles.blockCritical : ''}`}>
      <h2 className={styles.blockTitle}>{title}</h2>
      {records.length === 0 ? (
        <p className={styles.empty}>None recorded.</p>
      ) : (
        <ul className={styles.list}>
          {records.map((record) => (
            <li key={record.id} className={styles.listItem}>
              {formatVetVisitRecordLine(record)}
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
