import type { Breed, CareGuideline, Species } from '@/types/speciesIntelligence';

const now = new Date().toISOString();

export const MOCK_SPECIES: Species[] = [
  { id: 'sp-dog', slug: 'dog', name: 'Dog', description: 'Domestic dogs — highly variable by breed; preventive care and vaccination cadence are essential.', createdAt: now, updatedAt: now },
  { id: 'sp-cat', slug: 'cat', name: 'Cat', description: 'Domestic cats — independent companions with species-specific nutrition and litter-related health needs.', createdAt: now, updatedAt: now },
  { id: 'sp-bird', slug: 'bird', name: 'Bird', description: 'Companion birds — sensitive respiratory systems; weight and environment monitoring matter.', createdAt: now, updatedAt: now },
  { id: 'sp-rabbit', slug: 'rabbit', name: 'Rabbit', description: 'Domestic rabbits — herbivores with dental and GI health as primary concerns.', createdAt: now, updatedAt: now },
  { id: 'sp-reptile', slug: 'reptile', name: 'Reptile', description: 'Common pet reptiles — habitat parameters (temperature, humidity, UVB) directly affect health.', createdAt: now, updatedAt: now },
];

export const MOCK_BREEDS: Breed[] = [
  { id: 'br-lab', speciesId: 'sp-dog', slug: 'labrador-retriever', name: 'Labrador Retriever', description: 'Friendly, active retriever; prone to joint and weight issues.', sizeCategory: 'large', createdAt: now, updatedAt: now },
  { id: 'br-golden', speciesId: 'sp-dog', slug: 'golden-retriever', name: 'Golden Retriever', description: 'Social family dog; regular grooming and exercise.', sizeCategory: 'large', createdAt: now, updatedAt: now },
  { id: 'br-dog-mix', speciesId: 'sp-dog', slug: 'mixed-breed', name: 'Mixed Breed Dog', description: 'Genetic diversity; tailor care to observed size and energy.', sizeCategory: 'variable', createdAt: now, updatedAt: now },
  { id: 'br-dsh', speciesId: 'sp-cat', slug: 'domestic-shorthair', name: 'Domestic Shorthair', description: 'Common adaptable house cat.', sizeCategory: 'medium', createdAt: now, updatedAt: now },
  { id: 'br-maine', speciesId: 'sp-cat', slug: 'maine-coon', name: 'Maine Coon', description: 'Large, long-haired cat; cardiac screening may be advised.', sizeCategory: 'large', createdAt: now, updatedAt: now },
  { id: 'br-parakeet', speciesId: 'sp-bird', slug: 'parakeet', name: 'Parakeet (Budgie)', description: 'Small parrot; seed-only diets are insufficient long-term.', sizeCategory: 'small', createdAt: now, updatedAt: now },
  { id: 'br-cockatiel', speciesId: 'sp-bird', slug: 'cockatiel', name: 'Cockatiel', description: 'Gentle companion bird; social and vocal.', sizeCategory: 'small', createdAt: now, updatedAt: now },
  { id: 'br-holland', speciesId: 'sp-rabbit', slug: 'holland-lop', name: 'Holland Lop', description: 'Small lop-eared rabbit; hay-based diet is critical.', sizeCategory: 'small', createdAt: now, updatedAt: now },
  { id: 'br-beardie', speciesId: 'sp-reptile', slug: 'bearded-dragon', name: 'Bearded Dragon', description: 'Popular lizard; requires UVB and controlled heat gradient.', sizeCategory: 'medium', createdAt: now, updatedAt: now },
];

const SOURCE = 'PetClues Species Intelligence v1';

export const MOCK_CARE_GUIDELINES: CareGuideline[] = [
  {
    id: 'cg-dog',
    speciesId: 'sp-dog',
    breedId: null,
    lifespan: { minYears: 10, maxYears: 13, notes: 'Varies widely by size; giant breeds often shorter.' },
    diet: { summary: 'Complete, balanced commercial or vet-formulated diet matched to life stage.', feedingFrequency: 'Typically 2 meals/day for adults.', restrictions: ['Chocolate', 'Grapes/raisins', 'Xylitol', 'Onions/garlic'], notes: 'Adjust calories for neuter status and activity.' },
    exerciseNeeds: { level: 'moderate', minutesPerDay: 45, activities: ['Walks', 'Fetch', 'Sniff enrichment'], notes: 'Puppies need controlled exercise to protect joints.' },
    commonConditions: [
      { name: 'Dental disease', description: 'Plaque leads to pain and systemic infection.', prevalence: 'common' },
      { name: 'Obesity', description: 'Excess weight worsens arthritis and metabolic disease.', prevalence: 'common' },
    ],
    vaccinationGuidance: { core: ['DHPP (distemper combo)', 'Rabies'], optional: ['Bordetella', 'Leptospirosis', 'Lyme (region-dependent)'], scheduleNotes: 'Puppy series every 3–4 weeks until ~16 weeks.', boosterNotes: 'Titers or boosters per local law and lifestyle.' },
    seasonalConsiderations: [{ season: 'summer', title: 'Heat safety', considerations: ['Avoid hot pavement', 'Never leave in parked car'] }],
    source: SOURCE,
    version: 1,
    status: 'published',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cg-lab',
    speciesId: 'sp-dog',
    breedId: 'br-lab',
    lifespan: { minYears: 10, maxYears: 12, notes: 'Prone to obesity; lifespan linked to lean body condition.' },
    diet: { summary: 'Large-breed appropriate diet; monitor calories strictly.', feedingFrequency: '2 meals/day; weigh monthly.', restrictions: ['Table scraps', 'Excess treats'] },
    exerciseNeeds: { level: 'high', minutesPerDay: 60, activities: ['Swimming', 'Retrieving', 'Long walks'], notes: 'Under-exercise contributes to destructive behavior.' },
    commonConditions: [
      { name: 'Hip dysplasia', description: 'Screening advised for breeding lines.', prevalence: 'common' },
      { name: 'Obesity', description: 'Very common; joint stress multiplier.', prevalence: 'common' },
    ],
    vaccinationGuidance: { core: ['DHPP', 'Rabies'], optional: ['Bordetella if daycare/boarding'], scheduleNotes: 'Same core schedule as species.' },
    seasonalConsiderations: [{ season: 'summer', title: 'Swimming safety', considerations: ['Rinse chlorine after pools'] }],
    source: SOURCE,
    version: 1,
    status: 'published',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cg-cat',
    speciesId: 'sp-cat',
    breedId: null,
    lifespan: { minYears: 12, maxYears: 18, notes: 'Indoor cats often live longer with routine preventive care.' },
    diet: { summary: 'High-protein, moisture-rich diet; wet food helps hydration.', feedingFrequency: '2–4 small meals or measured free-feed per vet advice.', restrictions: ['Lilies (toxic)', 'Onions'] },
    exerciseNeeds: { level: 'low', minutesPerDay: 20, activities: ['Interactive play', 'Vertical climbing'] },
    commonConditions: [{ name: 'Chronic kidney disease', description: 'Common in seniors; early labs help.', prevalence: 'common' }],
    vaccinationGuidance: { core: ['FVRCP', 'Rabies'], optional: ['FeLV for at-risk cats'], scheduleNotes: 'Kitten series then boosters.' },
    seasonalConsiderations: [{ season: 'year-round', title: 'Litter & environment', considerations: ['One more box than cats', 'Reduce multi-cat stress'] }],
    source: SOURCE,
    version: 1,
    status: 'published',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cg-dsh',
    speciesId: 'sp-cat',
    breedId: 'br-dsh',
    lifespan: { minYears: 12, maxYears: 16, notes: 'Indoor DSH often exceeds outdoor averages.' },
    diet: { summary: 'Portion-controlled wet + dry or all-wet per vet.', feedingFrequency: 'Measured meals 2x/day.' },
    exerciseNeeds: { level: 'low', minutesPerDay: 15, activities: ['Wand toys'] },
    commonConditions: [{ name: 'Urinary issues', description: 'Stress and hydration affect FLUTD risk.', prevalence: 'occasional' }],
    vaccinationGuidance: { core: ['FVRCP', 'Rabies'], scheduleNotes: 'Indoor cats: discuss reduced exposure protocol with vet.' },
    seasonalConsiderations: [],
    source: SOURCE,
    version: 1,
    status: 'published',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cg-bird',
    speciesId: 'sp-bird',
    breedId: null,
    lifespan: { minYears: 5, maxYears: 15, notes: 'Lifespan varies greatly by species.' },
    diet: { summary: 'Pelleted base diet plus vegetables; limit seed mixes.', feedingFrequency: 'Fresh food daily.', restrictions: ['Avocado', 'Chocolate', 'Teflon fumes'] },
    exerciseNeeds: { level: 'moderate', minutesPerDay: 30, activities: ['Flight time in safe room', 'Foraging toys'] },
    commonConditions: [{ name: 'Respiratory illness', description: 'Drafts, smoke, and poor air quality are triggers.', prevalence: 'common' }],
    vaccinationGuidance: { core: [], scheduleNotes: 'Annual avian wellness exam recommended.' },
    seasonalConsiderations: [{ season: 'winter', title: 'Dry air & heating', considerations: ['Humidify room slightly'] }],
    source: SOURCE,
    version: 1,
    status: 'published',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cg-rabbit',
    speciesId: 'sp-rabbit',
    breedId: null,
    lifespan: { minYears: 8, maxYears: 12, notes: 'Spayed/neutered rabbits often live longer.' },
    diet: { summary: 'Unlimited timothy hay; limited pellets; leafy greens daily.', restrictions: ['Iceberg lettuce', 'Avocado'] },
    exerciseNeeds: { level: 'moderate', minutesPerDay: 30, activities: ['Hop space', 'Tunnel play'] },
    commonConditions: [{ name: 'GI stasis', description: 'Appetite loss needs same-day vet care.', prevalence: 'common' }],
    vaccinationGuidance: { core: ['RHDV2 where endemic'], scheduleNotes: 'RHDV2 per regional vet guidance.' },
    seasonalConsiderations: [{ season: 'summer', title: 'Heat stress', considerations: ['Rabbits overheat easily'] }],
    source: SOURCE,
    version: 1,
    status: 'published',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cg-reptile',
    speciesId: 'sp-reptile',
    breedId: null,
    lifespan: { minYears: 8, maxYears: 12, notes: 'Highly species-dependent.' },
    diet: { summary: 'Insect + plant offerings per species; calcium with D3 when UVB is inadequate.', feedingFrequency: 'Juveniles daily; adults every 1–2 days.' },
    exerciseNeeds: { level: 'low', minutesPerDay: 15, notes: 'Enrichment via habitat complexity.' },
    commonConditions: [{ name: 'Metabolic bone disease', description: 'UVB/lighting and calcium balance prevent MBD.', prevalence: 'common' }],
    vaccinationGuidance: { core: [], scheduleNotes: 'Parasite screens and husbandry review at wellness visits.' },
    seasonalConsiderations: [{ season: 'year-round', title: 'Habitat stability', considerations: ['Replace UVB bulbs per schedule'] }],
    source: SOURCE,
    version: 1,
    status: 'published',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cg-beardie',
    speciesId: 'sp-reptile',
    breedId: 'br-beardie',
    lifespan: { minYears: 8, maxYears: 12 },
    diet: { summary: 'Gut-loaded insects + salad greens; calcium dusting per age.', feedingFrequency: 'Juveniles: insects daily; adults: 2–3x/week insects + daily greens.' },
    exerciseNeeds: { level: 'low', minutesPerDay: 10, activities: ['Climbing branches'], notes: 'Brumation may reduce appetite seasonally.' },
    commonConditions: [
      { name: 'Impaction', description: 'Loose substrate risk.', prevalence: 'common' },
      { name: 'MBD', description: 'Weak jaw/legs if UVB/calcium insufficient.', prevalence: 'common' },
    ],
    vaccinationGuidance: { core: [], scheduleNotes: 'Fecal parasite exam annually.' },
    seasonalConsiderations: [{ season: 'winter', title: 'Brumation awareness', considerations: ['Appetite drop may be normal', 'Weigh weekly'] }],
    source: SOURCE,
    version: 1,
    status: 'published',
    createdAt: now,
    updatedAt: now,
  },
];
