/* eslint-disable */
// AUTO-GENERATED by scripts/generate-dominance-image-mappings.mjs
export const DOMINANCE_BLOG_IMAGE_FILE: Record<string, string> = {
  "how-much-does-vet-visit-cost-2026": "blog-pet-records.webp",
  "decoding-vet-bill-cbc-chem-17": "blog-vet-bill-organizer.webp",
  "dog-teeth-cleaning-costs-dental-surgery": "blog-dog-dental-care.webp",
  "mri-vs-x-ray-dogs-costs": "blog-pet-records.webp",
  "emergency-vet-costs-urgent-care": "blog-emergency-passport.webp",
  "spay-neuter-dog-cost-2026": "blog-puppy-checklist.webp",
  "tplo-surgery-cost-torn-acl-dogs": "blog-labrador-joint-care.webp",
  "cat-bloodwork-cost-overcharged": "blog-cat-health-records.webp",
  "pet-insurance-vs-out-of-pocket-2026": "blog-vet-bill-organizer.webp",
  "hidden-costs-vet-invoices": "blog-vet-bill-organizer.webp",
  "how-to-negotiate-vet-bills-payment-plans": "blog-vet-bill-organizer.webp",
  "euthanasia-cremation-cost-end-of-life": "blog-senior-dog.webp",
  "heartworm-treatment-cost-prevention": "blog-heartworm-prevention.webp",
  "parvovirus-treatment-costs-survival-rates": "blog-puppy-vaccination.webp",
  "dog-allergy-treatment-costs-cytopoint-apoquel": "blog-pet-allergy-tracker.webp",
  "feline-leukemia-testing-vaccine-costs": "blog-cat-vaccination.webp",
  "fecal-float-test-cost-why-vets-push-it": "blog-flea-tick-prevention.webp",
  "dog-tumor-removal-oncology-costs": "blog-pet-records.webp",
  "iv-fluids-cats-kidney-disease-costs": "blog-senior-cat-care.webp",
  "why-emergency-vets-cost-3x-more": "blog-emergency-passport.webp",
  "veterinary-prescriptions-overpaying-pet-meds": "blog-medication-reminder.webp",
  "french-bulldog-surgery-costs-boas-ivdd": "blog-french-bulldog-health.webp",
  "ultrasound-costs-dogs-cats": "blog-cat-health-records.webp",
  "cat-uti-blockage-treatment-costs": "blog-senior-cat-care.webp",
  "rabies-titer-test-international-travel-cost": "blog-microchip-registration.webp",
  "diabetes-treatment-cost-dogs-cats": "blog-medication-reminder.webp",
  "snake-bite-vet-bills-antivenom-costs": "blog-emergency-passport.webp",
  "dog-toxic-ingestion-treatment-costs": "blog-emergency-passport.webp",
  "cruciate-ligament-tear-conservative-vs-surgery-costs": "blog-labrador-joint-care.webp",
  "wellness-plans-banfield-vca-independent-vets": "blog-vet-bill-organizer.webp",
  "golden-retriever-first-year-cost-guide": "blog-labrador-joint-care.webp",
  "best-apartment-dogs-9-to-5-workers": "blog-daily-checkin.webp",
  "low-maintenance-pets-busy-professionals-2026": "blog-life-stage-care.webp",
  "hypoallergenic-dogs-fact-vs-fiction": "blog-pet-allergy-tracker.webp",
  "maine-coon-cost-guide-purchase-food-vet": "blog-maine-coon-health.webp",
  "french-bulldog-vet-costs-reality-check": "blog-french-bulldog-health.webp",
  "best-cat-breeds-for-dog-people": "blog-cat-health-records.webp",
  "shelter-dog-vs-breeder-puppy-financial-differences": "blog-puppy-checklist.webp",
  "high-energy-dogs-marathon-running-partners": "blog-german-shepherd-hip.webp",
  "best-guard-dogs-families-small-children": "blog-german-shepherd-hip.webp",
  "most-expensive-dog-breeds-to-insure": "blog-vet-bill-organizer.webp",
  "easiest-reptiles-beginners-setup-vet-costs": "blog-snake-care.webp",
  "sphynx-cat-care-costs-lotions-heart-scans": "blog-cat-health-records.webp",
  "dog-breeds-most-prone-to-cancer": "blog-senior-dog.webp",
  "best-emotional-support-animal-breeds-documentation": "blog-life-stage-care.webp",
  "true-cost-owning-parrot-50-year-commitment": "blog-bird-care.webp",
  "doodle-breeds-grooming-costs-health-quirks": "blog-poodle-grooming-health.webp",
  "working-breeds-apartment-husky-city-life": "blog-german-shepherd-hip.webp",
  "bengal-cat-ownership-energy-diet-vet-costs": "blog-siamese-cat-wellness.webp",
  "brachycephalic-breeds-cargo-travel-ban": "blog-french-bulldog-health.webp",
  "senior-rescue-dogs-adoption-costs-rewards": "blog-senior-dog.webp",
  "dog-breeds-that-shed-least-grooming-costs": "blog-poodle-grooming-health.webp",
  "large-breed-vs-giant-breed-great-dane-feeding-costs": "blog-dog-weight-tracker.webp",
  "most-vocal-cat-breeds-siamese-bengal-oriental": "blog-siamese-cat-wellness.webp",
  "apartment-friendly-cats-no-outdoor-access": "blog-cat-health-records.webp",
  "dog-breeds-separation-anxiety-daycare-costs": "blog-pet-boarding.webp",
  "best-pets-seniors-limited-mobility": "blog-senior-dog.webp",
  "corgi-spine-health-ivdd-ramps-reality": "blog-dachshund-mobility.webp",
  "male-vs-female-puppy-health-behavior-trends": "blog-puppy-checklist.webp",
  "petclues-lifestyle-quiz-breed-fit": "blog-life-stage-care.webp",
  "dog-throwing-up-yellow-bile-morning": "blog-dog-vaccination-guide.webp",
  "cat-limping-front-leg-when-to-call-vet": "blog-cat-health-records.webp",
  "dog-diarrhea-mucus-blood-fasting-emergency": "blog-emergency-passport.webp",
  "reverse-sneezing-dogs-choking-allergies": "blog-pet-allergy-tracker.webp",
  "cat-bad-breath-dental-disease-stages": "blog-dog-dental-care.webp",
  "dog-panting-heavily-at-night": "blog-senior-dog.webp",
  "cat-not-drinking-water-kidney-failure": "blog-senior-cat-care.webp",
  "kennel-cough-symptoms-contagious-how-long": "blog-dog-vaccination-guide.webp",
  "dog-dragging-back-legs-ivdd-emergency": "blog-dachshund-mobility.webp",
  "dog-licking-paws-constantly-yeast-allergies": "blog-pet-allergy-tracker.webp",
  "cat-peeing-outside-litter-box-flutd": "blog-senior-cat-care.webp",
  "how-to-tell-if-dog-has-fever-without-thermometer": "blog-dog-vaccination-guide.webp",
  "lethargic-puppy-parvovirus-warning-signs": "blog-puppy-vaccination.webp",
  "dog-cloudy-eyes-nuclear-sclerosis-vs-cataracts": "blog-senior-dog.webp",
  "cat-vomiting-hairballs-gi-blockage": "blog-cat-health-records.webp",
  "dog-scooting-carpet-anal-glands-parasites": "blog-flea-tick-prevention.webp",
  "swollen-dog-ear-aural-hematoma": "blog-dog-vaccination-guide.webp",
  "pale-gums-dogs-capillary-refill-time": "blog-emergency-passport.webp",
  "feline-asthma-cough-vs-hairball": "blog-cat-health-records.webp",
  "dog-drinking-too-much-water-cushings-diabetes-kidney": "blog-dog-weight-tracker.webp",
  "cat-losing-weight-eating-hyperthyroidism": "blog-senior-cat-care.webp",
  "dog-seizures-first-3-minutes-protocol": "blog-emergency-passport.webp",
  "hot-spots-dogs-home-remedies-vet-treatments": "blog-pet-allergy-tracker.webp",
  "cat-hiding-recognizing-pain": "blog-cat-health-records.webp",
  "dog-shaking-trembling-toxic-shock": "blog-emergency-passport.webp",
  "ringworm-cats-symptoms-contagion-woods-lamp": "blog-cat-health-records.webp",
  "tick-on-dog-removal-symptoms-to-track": "blog-flea-tick-prevention.webp",
  "cherry-eye-dogs-surgery-alternatives": "blog-puppy-checklist.webp",
  "cat-drooling-excessively-nausea-poison": "blog-cat-health-records.webp",
  "track-pet-symptoms-petclues-health-foresight-ai": "blog-best-pet-health-app.webp",
  "flying-domestically-dog-2026-airline-rules-carrier-sizes": "blog-travel-pets.webp",
  "moving-eu-pet-2026-rabies-titer-microchip-guide": "blog-microchip-registration.webp",
  "moving-uk-dog-defra-regulations": "blog-travel-pets.webp",
  "create-shareable-digital-emergency-pet-passport": "blog-emergency-passport.webp",
  "leaving-dog-rover-sitter-digital-handoff": "blog-pet-sitter-instructions.webp",
  "flying-cat-cabin-tsa-gabapentin-carrier-tips": "blog-flying-with-cats.webp",
  "pet-shipping-companies-cost-why-need-one": "blog-travel-pets.webp",
  "usda-health-certificate-pet-travel-timeline-fees": "blog-travel-pets.webp",
  "pet-travel-hawaii-quarantine-laws": "blog-travel-pets.webp",
  "traveling-mexico-dog-senasica-requirements-2026": "blog-travel-pets.webp",
  "pet-medical-emergency-road-trip": "blog-emergency-passport.webp",
  "essential-documents-dog-walker-before-work": "blog-pet-sitter-instructions.webp",
  "digital-vaccine-proof-doggy-daycare-boarding": "blog-pet-boarding.webp",
  "find-english-speaking-vet-abroad": "blog-travel-pets.webp",
  "hotel-pet-policies-2026-marriott-hilton-boutique-fees": "blog-travel-pets.webp",
  "camping-dogs-flea-tick-leptospirosis-protocols": "blog-flea-tick-prevention.webp",
  "luxury-boarding-facility-health-requirements": "blog-pet-boarding.webp",
  "cargo-travel-stress-safe-large-dogs": "blog-travel-pets.webp",
  "pet-relocation-scams-verify-safe-transport": "blog-travel-pets.webp",
  "flying-canada-dog-border-rules-cbsa-checks": "blog-travel-pets.webp",
  "esa-vs-service-dog-travel-rules-airlines": "blog-travel-pets.webp",
  "road-tripping-cats-litter-box-anxiety-meds": "blog-flying-with-cats.webp",
  "sedating-pet-air-travel-vets-recommend-against": "blog-flying-with-cats.webp",
  "one-click-medical-profile-pet-boarder": "blog-pet-sitter-instructions.webp",
  "traveling-diabetic-pets-insulin-syringes": "blog-medication-reminder.webp",
  "pet-emergency-kit-hurricanes-wildfires": "blog-emergency-passport.webp",
  "pet-first-aid-kit-hiking": "blog-emergency-passport.webp",
  "crossing-state-lines-horses-livestock-coggins-health-certs": "blog-travel-pets.webp",
  "sync-pet-microchip-digital-medical-record": "blog-microchip-registration.webp",
  "five-minute-checklist-leaving-pet-neighbor": "blog-pet-sitter-instructions.webp",
  "best-pet-tech-gadgets-2026-smart-feeders-ai-trackers": "blog-best-pet-health-app.webp",
  "apple-airtag-vs-fi-collar-vs-whistle-pet-tracker": "blog-best-pet-health-app.webp",
  "ai-diagnose-dog-future-veterinary-medicine": "blog-best-pet-health-app.webp",
  "cost-canine-longevity-supplements-rapamycin-diets": "blog-senior-dog.webp",
  "smart-litter-boxes-worth-500-cat-uti-detection": "blog-senior-cat-care.webp",
  "wearable-tech-dogs-sleep-heart-rate-scratching": "blog-best-pet-health-app.webp",
  "raw-vs-fresh-cooked-vs-kibble-2026-vet-consensus": "blog-dog-weight-tracker.webp",
  "microbiome-testing-pets-gut-health-dog-allergies": "blog-pet-allergy-tracker.webp",
  "automatic-cat-feeders-microchipped-multi-pet-homes": "blog-cat-health-records.webp",
  "cbd-dogs-arthritis-2026-clinical-studies-dosage": "blog-senior-dog.webp",
  "telehealth-pets-when-use-when-drive-er": "blog-best-pet-health-app.webp",
  "ai-decoding-veterinary-bills-saving-money": "blog-vet-bill-organizer.webp",
  "librela-solensia-monthly-injections-pet-arthritis": "blog-senior-dog.webp",
  "dna-testing-dogs-embark-vs-wisdom-panel-accuracy": "blog-puppy-checklist.webp",
  "at-home-urine-tests-cats-kidney-issues-early": "blog-senior-cat-care.webp",
  "subscription-pet-meds-chewy-petmed-vs-local-vets": "blog-medication-reminder.webp",
  "chatgpt-understand-pet-bloodwork-results": "blog-pet-records.webp",
  "hydrotherapy-laser-therapy-senior-dogs-tech-help": "blog-senior-dog.webp",
  "smart-pet-doors-microchip-access-curfew": "blog-microchip-registration.webp",
  "pet-cameras-treat-dispensers-furbo-vs-wyze": "blog-best-pet-health-app.webp",
  "dental-water-additives-vs-brushing-plaque-removal": "blog-dog-dental-care.webp",
  "science-dog-goggles-rex-specs-hearing-protection": "blog-dog-vaccination-guide.webp",
  "alternative-therapies-acupuncture-chiropractic-pets": "blog-senior-dog.webp",
  "high-tech-aquariums-automated-dosing-monitoring": "blog-exotic-pet-records.webp",
  "air-purifiers-pet-dander-allergic-owners": "blog-pet-allergy-tracker.webp",
  "build-digital-living-archive-pet-life": "blog-pet-records-timeline.webp",
  "preventative-pet-care-shift-away-reactive-vet-visits": "blog-dog-vaccination-guide.webp",
  "gene-editing-future-hereditary-dog-diseases": "blog-puppy-vaccination.webp",
  "ethics-pet-cloning-2026-costs-reality": "blog-life-stage-care.webp",
  "paper-pet-records-dead-rise-biological-pet-os": "blog-pet-records-timeline.webp"
};

export const DOMINANCE_BLOG_IMAGE_PAIRS: Record<string, { hero: string; inline: string }> = {
  "how-much-does-vet-visit-cost-2026": {
    "hero": "blog-pet-records.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "decoding-vet-bill-cbc-chem-17": {
    "hero": "blog-vet-bill-organizer.webp",
    "inline": "blog-pet-records.webp"
  },
  "dog-teeth-cleaning-costs-dental-surgery": {
    "hero": "blog-dog-dental-care.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "mri-vs-x-ray-dogs-costs": {
    "hero": "blog-pet-records.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "emergency-vet-costs-urgent-care": {
    "hero": "blog-emergency-passport.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "spay-neuter-dog-cost-2026": {
    "hero": "blog-puppy-checklist.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "tplo-surgery-cost-torn-acl-dogs": {
    "hero": "blog-labrador-joint-care.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "cat-bloodwork-cost-overcharged": {
    "hero": "blog-cat-health-records.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "pet-insurance-vs-out-of-pocket-2026": {
    "hero": "blog-vet-bill-organizer.webp",
    "inline": "blog-pet-records.webp"
  },
  "hidden-costs-vet-invoices": {
    "hero": "blog-vet-bill-organizer.webp",
    "inline": "blog-pet-records-timeline.webp"
  },
  "how-to-negotiate-vet-bills-payment-plans": {
    "hero": "blog-vet-bill-organizer.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "euthanasia-cremation-cost-end-of-life": {
    "hero": "blog-senior-dog.webp",
    "inline": "blog-pet-records-timeline.webp"
  },
  "heartworm-treatment-cost-prevention": {
    "hero": "blog-heartworm-prevention.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "parvovirus-treatment-costs-survival-rates": {
    "hero": "blog-puppy-vaccination.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "dog-allergy-treatment-costs-cytopoint-apoquel": {
    "hero": "blog-pet-allergy-tracker.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "feline-leukemia-testing-vaccine-costs": {
    "hero": "blog-cat-vaccination.webp",
    "inline": "blog-cat-health-records.webp"
  },
  "fecal-float-test-cost-why-vets-push-it": {
    "hero": "blog-flea-tick-prevention.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "dog-tumor-removal-oncology-costs": {
    "hero": "blog-pet-records.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "iv-fluids-cats-kidney-disease-costs": {
    "hero": "blog-senior-cat-care.webp",
    "inline": "blog-medication-reminder.webp"
  },
  "why-emergency-vets-cost-3x-more": {
    "hero": "blog-emergency-passport.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "veterinary-prescriptions-overpaying-pet-meds": {
    "hero": "blog-medication-reminder.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "french-bulldog-surgery-costs-boas-ivdd": {
    "hero": "blog-french-bulldog-health.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "ultrasound-costs-dogs-cats": {
    "hero": "blog-cat-health-records.webp",
    "inline": "blog-pet-records.webp"
  },
  "cat-uti-blockage-treatment-costs": {
    "hero": "blog-senior-cat-care.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "rabies-titer-test-international-travel-cost": {
    "hero": "blog-microchip-registration.webp",
    "inline": "blog-travel-pets.webp"
  },
  "diabetes-treatment-cost-dogs-cats": {
    "hero": "blog-medication-reminder.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "snake-bite-vet-bills-antivenom-costs": {
    "hero": "blog-emergency-passport.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "dog-toxic-ingestion-treatment-costs": {
    "hero": "blog-emergency-passport.webp",
    "inline": "blog-puppy-checklist.webp"
  },
  "cruciate-ligament-tear-conservative-vs-surgery-costs": {
    "hero": "blog-labrador-joint-care.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "wellness-plans-banfield-vca-independent-vets": {
    "hero": "blog-vet-bill-organizer.webp",
    "inline": "blog-dog-vaccination-guide.webp"
  },
  "golden-retriever-first-year-cost-guide": {
    "hero": "blog-labrador-joint-care.webp",
    "inline": "blog-puppy-checklist.webp"
  },
  "best-apartment-dogs-9-to-5-workers": {
    "hero": "blog-daily-checkin.webp",
    "inline": "blog-puppy-checklist.webp"
  },
  "low-maintenance-pets-busy-professionals-2026": {
    "hero": "blog-life-stage-care.webp",
    "inline": "blog-daily-checkin.webp"
  },
  "hypoallergenic-dogs-fact-vs-fiction": {
    "hero": "blog-pet-allergy-tracker.webp",
    "inline": "blog-poodle-grooming-health.webp"
  },
  "maine-coon-cost-guide-purchase-food-vet": {
    "hero": "blog-maine-coon-health.webp",
    "inline": "blog-cat-health-records.webp"
  },
  "french-bulldog-vet-costs-reality-check": {
    "hero": "blog-french-bulldog-health.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "best-cat-breeds-for-dog-people": {
    "hero": "blog-cat-health-records.webp",
    "inline": "blog-siamese-cat-wellness.webp"
  },
  "shelter-dog-vs-breeder-puppy-financial-differences": {
    "hero": "blog-puppy-checklist.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "high-energy-dogs-marathon-running-partners": {
    "hero": "blog-german-shepherd-hip.webp",
    "inline": "blog-dog-weight-tracker.webp"
  },
  "best-guard-dogs-families-small-children": {
    "hero": "blog-german-shepherd-hip.webp",
    "inline": "blog-puppy-checklist.webp"
  },
  "most-expensive-dog-breeds-to-insure": {
    "hero": "blog-vet-bill-organizer.webp",
    "inline": "blog-french-bulldog-health.webp"
  },
  "easiest-reptiles-beginners-setup-vet-costs": {
    "hero": "blog-snake-care.webp",
    "inline": "blog-exotic-pet-records.webp"
  },
  "sphynx-cat-care-costs-lotions-heart-scans": {
    "hero": "blog-cat-health-records.webp",
    "inline": "blog-maine-coon-health.webp"
  },
  "dog-breeds-most-prone-to-cancer": {
    "hero": "blog-senior-dog.webp",
    "inline": "blog-pet-records-timeline.webp"
  },
  "best-emotional-support-animal-breeds-documentation": {
    "hero": "blog-life-stage-care.webp",
    "inline": "blog-pet-records.webp"
  },
  "true-cost-owning-parrot-50-year-commitment": {
    "hero": "blog-bird-care.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "doodle-breeds-grooming-costs-health-quirks": {
    "hero": "blog-poodle-grooming-health.webp",
    "inline": "blog-pet-allergy-tracker.webp"
  },
  "working-breeds-apartment-husky-city-life": {
    "hero": "blog-german-shepherd-hip.webp",
    "inline": "blog-daily-checkin.webp"
  },
  "bengal-cat-ownership-energy-diet-vet-costs": {
    "hero": "blog-siamese-cat-wellness.webp",
    "inline": "blog-cat-health-records.webp"
  },
  "brachycephalic-breeds-cargo-travel-ban": {
    "hero": "blog-french-bulldog-health.webp",
    "inline": "blog-travel-pets.webp"
  },
  "senior-rescue-dogs-adoption-costs-rewards": {
    "hero": "blog-senior-dog.webp",
    "inline": "blog-puppy-checklist.webp"
  },
  "dog-breeds-that-shed-least-grooming-costs": {
    "hero": "blog-poodle-grooming-health.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "large-breed-vs-giant-breed-great-dane-feeding-costs": {
    "hero": "blog-dog-weight-tracker.webp",
    "inline": "blog-puppy-checklist.webp"
  },
  "most-vocal-cat-breeds-siamese-bengal-oriental": {
    "hero": "blog-siamese-cat-wellness.webp",
    "inline": "blog-maine-coon-health.webp"
  },
  "apartment-friendly-cats-no-outdoor-access": {
    "hero": "blog-cat-health-records.webp",
    "inline": "blog-new-kitten-checklist.webp"
  },
  "dog-breeds-separation-anxiety-daycare-costs": {
    "hero": "blog-pet-boarding.webp",
    "inline": "blog-daily-checkin.webp"
  },
  "best-pets-seniors-limited-mobility": {
    "hero": "blog-senior-dog.webp",
    "inline": "blog-senior-cat-care.webp"
  },
  "corgi-spine-health-ivdd-ramps-reality": {
    "hero": "blog-dachshund-mobility.webp",
    "inline": "blog-labrador-joint-care.webp"
  },
  "male-vs-female-puppy-health-behavior-trends": {
    "hero": "blog-puppy-checklist.webp",
    "inline": "blog-puppy-vaccination.webp"
  },
  "petclues-lifestyle-quiz-breed-fit": {
    "hero": "blog-life-stage-care.webp",
    "inline": "blog-best-pet-health-app.webp"
  },
  "dog-throwing-up-yellow-bile-morning": {
    "hero": "blog-dog-vaccination-guide.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "cat-limping-front-leg-when-to-call-vet": {
    "hero": "blog-cat-health-records.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "dog-diarrhea-mucus-blood-fasting-emergency": {
    "hero": "blog-emergency-passport.webp",
    "inline": "blog-dog-vaccination-guide.webp"
  },
  "reverse-sneezing-dogs-choking-allergies": {
    "hero": "blog-pet-allergy-tracker.webp",
    "inline": "blog-dog-vaccination-guide.webp"
  },
  "cat-bad-breath-dental-disease-stages": {
    "hero": "blog-dog-dental-care.webp",
    "inline": "blog-cat-health-records.webp"
  },
  "dog-panting-heavily-at-night": {
    "hero": "blog-senior-dog.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "cat-not-drinking-water-kidney-failure": {
    "hero": "blog-senior-cat-care.webp",
    "inline": "blog-medication-reminder.webp"
  },
  "kennel-cough-symptoms-contagious-how-long": {
    "hero": "blog-dog-vaccination-guide.webp",
    "inline": "blog-pet-boarding.webp"
  },
  "dog-dragging-back-legs-ivdd-emergency": {
    "hero": "blog-dachshund-mobility.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "dog-licking-paws-constantly-yeast-allergies": {
    "hero": "blog-pet-allergy-tracker.webp",
    "inline": "blog-dog-vaccination-guide.webp"
  },
  "cat-peeing-outside-litter-box-flutd": {
    "hero": "blog-senior-cat-care.webp",
    "inline": "blog-cat-health-records.webp"
  },
  "how-to-tell-if-dog-has-fever-without-thermometer": {
    "hero": "blog-dog-vaccination-guide.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "lethargic-puppy-parvovirus-warning-signs": {
    "hero": "blog-puppy-vaccination.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "dog-cloudy-eyes-nuclear-sclerosis-vs-cataracts": {
    "hero": "blog-senior-dog.webp",
    "inline": "blog-dog-vaccination-guide.webp"
  },
  "cat-vomiting-hairballs-gi-blockage": {
    "hero": "blog-cat-health-records.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "dog-scooting-carpet-anal-glands-parasites": {
    "hero": "blog-flea-tick-prevention.webp",
    "inline": "blog-dog-vaccination-guide.webp"
  },
  "swollen-dog-ear-aural-hematoma": {
    "hero": "blog-dog-vaccination-guide.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "pale-gums-dogs-capillary-refill-time": {
    "hero": "blog-emergency-passport.webp",
    "inline": "blog-dog-vaccination-guide.webp"
  },
  "feline-asthma-cough-vs-hairball": {
    "hero": "blog-cat-health-records.webp",
    "inline": "blog-senior-cat-care.webp"
  },
  "dog-drinking-too-much-water-cushings-diabetes-kidney": {
    "hero": "blog-dog-weight-tracker.webp",
    "inline": "blog-medication-reminder.webp"
  },
  "cat-losing-weight-eating-hyperthyroidism": {
    "hero": "blog-senior-cat-care.webp",
    "inline": "blog-cat-health-records.webp"
  },
  "dog-seizures-first-3-minutes-protocol": {
    "hero": "blog-emergency-passport.webp",
    "inline": "blog-medication-reminder.webp"
  },
  "hot-spots-dogs-home-remedies-vet-treatments": {
    "hero": "blog-pet-allergy-tracker.webp",
    "inline": "blog-dog-vaccination-guide.webp"
  },
  "cat-hiding-recognizing-pain": {
    "hero": "blog-cat-health-records.webp",
    "inline": "blog-senior-cat-care.webp"
  },
  "dog-shaking-trembling-toxic-shock": {
    "hero": "blog-emergency-passport.webp",
    "inline": "blog-pet-allergy-tracker.webp"
  },
  "ringworm-cats-symptoms-contagion-woods-lamp": {
    "hero": "blog-cat-health-records.webp",
    "inline": "blog-flea-tick-prevention.webp"
  },
  "tick-on-dog-removal-symptoms-to-track": {
    "hero": "blog-flea-tick-prevention.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "cherry-eye-dogs-surgery-alternatives": {
    "hero": "blog-puppy-checklist.webp",
    "inline": "blog-dog-vaccination-guide.webp"
  },
  "cat-drooling-excessively-nausea-poison": {
    "hero": "blog-cat-health-records.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "track-pet-symptoms-petclues-health-foresight-ai": {
    "hero": "blog-best-pet-health-app.webp",
    "inline": "blog-pet-records-timeline.webp"
  },
  "flying-domestically-dog-2026-airline-rules-carrier-sizes": {
    "hero": "blog-travel-pets.webp",
    "inline": "blog-pet-boarding.webp"
  },
  "moving-eu-pet-2026-rabies-titer-microchip-guide": {
    "hero": "blog-microchip-registration.webp",
    "inline": "blog-travel-pets.webp"
  },
  "moving-uk-dog-defra-regulations": {
    "hero": "blog-travel-pets.webp",
    "inline": "blog-microchip-registration.webp"
  },
  "create-shareable-digital-emergency-pet-passport": {
    "hero": "blog-emergency-passport.webp",
    "inline": "blog-pet-sitter-instructions.webp"
  },
  "leaving-dog-rover-sitter-digital-handoff": {
    "hero": "blog-pet-sitter-instructions.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "flying-cat-cabin-tsa-gabapentin-carrier-tips": {
    "hero": "blog-flying-with-cats.webp",
    "inline": "blog-travel-pets.webp"
  },
  "pet-shipping-companies-cost-why-need-one": {
    "hero": "blog-travel-pets.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "usda-health-certificate-pet-travel-timeline-fees": {
    "hero": "blog-travel-pets.webp",
    "inline": "blog-microchip-registration.webp"
  },
  "pet-travel-hawaii-quarantine-laws": {
    "hero": "blog-travel-pets.webp",
    "inline": "blog-pet-boarding.webp"
  },
  "traveling-mexico-dog-senasica-requirements-2026": {
    "hero": "blog-travel-pets.webp",
    "inline": "blog-microchip-registration.webp"
  },
  "pet-medical-emergency-road-trip": {
    "hero": "blog-emergency-passport.webp",
    "inline": "blog-travel-pets.webp"
  },
  "essential-documents-dog-walker-before-work": {
    "hero": "blog-pet-sitter-instructions.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "digital-vaccine-proof-doggy-daycare-boarding": {
    "hero": "blog-pet-boarding.webp",
    "inline": "blog-puppy-vaccination.webp"
  },
  "find-english-speaking-vet-abroad": {
    "hero": "blog-travel-pets.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "hotel-pet-policies-2026-marriott-hilton-boutique-fees": {
    "hero": "blog-travel-pets.webp",
    "inline": "blog-pet-boarding.webp"
  },
  "camping-dogs-flea-tick-leptospirosis-protocols": {
    "hero": "blog-flea-tick-prevention.webp",
    "inline": "blog-travel-pets.webp"
  },
  "luxury-boarding-facility-health-requirements": {
    "hero": "blog-pet-boarding.webp",
    "inline": "blog-pet-sitter-instructions.webp"
  },
  "cargo-travel-stress-safe-large-dogs": {
    "hero": "blog-travel-pets.webp",
    "inline": "blog-german-shepherd-hip.webp"
  },
  "pet-relocation-scams-verify-safe-transport": {
    "hero": "blog-travel-pets.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "flying-canada-dog-border-rules-cbsa-checks": {
    "hero": "blog-travel-pets.webp",
    "inline": "blog-microchip-registration.webp"
  },
  "esa-vs-service-dog-travel-rules-airlines": {
    "hero": "blog-travel-pets.webp",
    "inline": "blog-pet-sitter-instructions.webp"
  },
  "road-tripping-cats-litter-box-anxiety-meds": {
    "hero": "blog-flying-with-cats.webp",
    "inline": "blog-travel-pets.webp"
  },
  "sedating-pet-air-travel-vets-recommend-against": {
    "hero": "blog-flying-with-cats.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "one-click-medical-profile-pet-boarder": {
    "hero": "blog-pet-sitter-instructions.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "traveling-diabetic-pets-insulin-syringes": {
    "hero": "blog-medication-reminder.webp",
    "inline": "blog-travel-pets.webp"
  },
  "pet-emergency-kit-hurricanes-wildfires": {
    "hero": "blog-emergency-passport.webp",
    "inline": "blog-travel-pets.webp"
  },
  "pet-first-aid-kit-hiking": {
    "hero": "blog-emergency-passport.webp",
    "inline": "blog-flea-tick-prevention.webp"
  },
  "crossing-state-lines-horses-livestock-coggins-health-certs": {
    "hero": "blog-travel-pets.webp",
    "inline": "blog-microchip-registration.webp"
  },
  "sync-pet-microchip-digital-medical-record": {
    "hero": "blog-microchip-registration.webp",
    "inline": "blog-pet-records-timeline.webp"
  },
  "five-minute-checklist-leaving-pet-neighbor": {
    "hero": "blog-pet-sitter-instructions.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "best-pet-tech-gadgets-2026-smart-feeders-ai-trackers": {
    "hero": "blog-best-pet-health-app.webp",
    "inline": "blog-daily-checkin.webp"
  },
  "apple-airtag-vs-fi-collar-vs-whistle-pet-tracker": {
    "hero": "blog-best-pet-health-app.webp",
    "inline": "blog-microchip-registration.webp"
  },
  "ai-diagnose-dog-future-veterinary-medicine": {
    "hero": "blog-best-pet-health-app.webp",
    "inline": "blog-pet-records.webp"
  },
  "cost-canine-longevity-supplements-rapamycin-diets": {
    "hero": "blog-senior-dog.webp",
    "inline": "blog-dog-weight-tracker.webp"
  },
  "smart-litter-boxes-worth-500-cat-uti-detection": {
    "hero": "blog-senior-cat-care.webp",
    "inline": "blog-best-pet-health-app.webp"
  },
  "wearable-tech-dogs-sleep-heart-rate-scratching": {
    "hero": "blog-best-pet-health-app.webp",
    "inline": "blog-dog-weight-tracker.webp"
  },
  "raw-vs-fresh-cooked-vs-kibble-2026-vet-consensus": {
    "hero": "blog-dog-weight-tracker.webp",
    "inline": "blog-daily-checkin.webp"
  },
  "microbiome-testing-pets-gut-health-dog-allergies": {
    "hero": "blog-pet-allergy-tracker.webp",
    "inline": "blog-best-pet-health-app.webp"
  },
  "automatic-cat-feeders-microchipped-multi-pet-homes": {
    "hero": "blog-cat-health-records.webp",
    "inline": "blog-best-pet-health-app.webp"
  },
  "cbd-dogs-arthritis-2026-clinical-studies-dosage": {
    "hero": "blog-senior-dog.webp",
    "inline": "blog-medication-reminder.webp"
  },
  "telehealth-pets-when-use-when-drive-er": {
    "hero": "blog-best-pet-health-app.webp",
    "inline": "blog-emergency-passport.webp"
  },
  "ai-decoding-veterinary-bills-saving-money": {
    "hero": "blog-vet-bill-organizer.webp",
    "inline": "blog-best-pet-health-app.webp"
  },
  "librela-solensia-monthly-injections-pet-arthritis": {
    "hero": "blog-senior-dog.webp",
    "inline": "blog-medication-reminder.webp"
  },
  "dna-testing-dogs-embark-vs-wisdom-panel-accuracy": {
    "hero": "blog-puppy-checklist.webp",
    "inline": "blog-best-pet-health-app.webp"
  },
  "at-home-urine-tests-cats-kidney-issues-early": {
    "hero": "blog-senior-cat-care.webp",
    "inline": "blog-cat-health-records.webp"
  },
  "subscription-pet-meds-chewy-petmed-vs-local-vets": {
    "hero": "blog-medication-reminder.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "chatgpt-understand-pet-bloodwork-results": {
    "hero": "blog-pet-records.webp",
    "inline": "blog-best-pet-health-app.webp"
  },
  "hydrotherapy-laser-therapy-senior-dogs-tech-help": {
    "hero": "blog-senior-dog.webp",
    "inline": "blog-labrador-joint-care.webp"
  },
  "smart-pet-doors-microchip-access-curfew": {
    "hero": "blog-microchip-registration.webp",
    "inline": "blog-best-pet-health-app.webp"
  },
  "pet-cameras-treat-dispensers-furbo-vs-wyze": {
    "hero": "blog-best-pet-health-app.webp",
    "inline": "blog-pet-sitter-instructions.webp"
  },
  "dental-water-additives-vs-brushing-plaque-removal": {
    "hero": "blog-dog-dental-care.webp",
    "inline": "blog-daily-checkin.webp"
  },
  "science-dog-goggles-rex-specs-hearing-protection": {
    "hero": "blog-dog-vaccination-guide.webp",
    "inline": "blog-best-pet-health-app.webp"
  },
  "alternative-therapies-acupuncture-chiropractic-pets": {
    "hero": "blog-senior-dog.webp",
    "inline": "blog-labrador-joint-care.webp"
  },
  "high-tech-aquariums-automated-dosing-monitoring": {
    "hero": "blog-exotic-pet-records.webp",
    "inline": "blog-best-pet-health-app.webp"
  },
  "air-purifiers-pet-dander-allergic-owners": {
    "hero": "blog-pet-allergy-tracker.webp",
    "inline": "blog-best-pet-health-app.webp"
  },
  "build-digital-living-archive-pet-life": {
    "hero": "blog-pet-records-timeline.webp",
    "inline": "blog-best-pet-health-app.webp"
  },
  "preventative-pet-care-shift-away-reactive-vet-visits": {
    "hero": "blog-dog-vaccination-guide.webp",
    "inline": "blog-pet-records-timeline.webp"
  },
  "gene-editing-future-hereditary-dog-diseases": {
    "hero": "blog-puppy-vaccination.webp",
    "inline": "blog-pet-records.webp"
  },
  "ethics-pet-cloning-2026-costs-reality": {
    "hero": "blog-life-stage-care.webp",
    "inline": "blog-vet-bill-organizer.webp"
  },
  "paper-pet-records-dead-rise-biological-pet-os": {
    "hero": "blog-pet-records-timeline.webp",
    "inline": "blog-best-pet-health-app.webp"
  }
};
